import { contextBridge,ipcRenderer } from 'electron';

type OverlayAction='exit'|'pause-toggle'|'seek'|'volume'|'next'|'live-prev'|'live-next';
type OverlayState={requestId:string;domain:'vod'|'live'|null;paused:boolean;position:number;duration:number;volume:number;channelId?:string;routeIndex?:number;routeCount?:number};
let current:OverlayState={requestId:'',domain:null,paused:false,position:0,duration:0,volume:100};let hideTimer:ReturnType<typeof setTimeout>|undefined;
function send(action:OverlayAction,value?:number):void{if(!current.requestId)return;void ipcRenderer.invoke('fullscreen-overlay:action',{action,requestId:current.requestId,...(value===undefined?{}:{value})});}
contextBridge.exposeInMainWorld('fndFullscreenOverlay',{action:(action:OverlayAction,value?:number)=>send(action,value)});
function formatTime(value:number):string{const total=Math.max(0,Math.floor(value||0)),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return(h?`${h.toString().padStart(2,'0')}:`:'')+`${m.toString().padStart(2,'0')}:${s.toString().padStart(2,'0')}`;}
function byId<T extends HTMLElement>(id:string):T|undefined{return document.getElementById(id) as T|null??undefined;}
function reveal():void{const controls=byId<HTMLElement>('controls');controls?.classList.remove('hidden');if(hideTimer)clearTimeout(hideTimer);hideTimer=setTimeout(()=>controls?.classList.add('hidden'),3000);}
function render(state:OverlayState):void{current=state;const body=document.body,title=byId<HTMLElement>('title'),meta=byId<HTMLElement>('meta'),time=byId<HTMLElement>('time'),progress=byId<HTMLInputElement>('progress'),volume=byId<HTMLInputElement>('volume'),pause=byId<HTMLButtonElement>('pause');body.classList.toggle('is-live',state.domain==='live');body.classList.toggle('is-vod',state.domain==='vod');if(title)title.textContent=state.domain==='live'?(state.channelId?`直播 · ${state.channelId}`:'直播'):'点播';if(meta)meta.textContent=state.domain==='live'&&state.routeIndex!==undefined?`线路 ${state.routeIndex+1}/${Math.max(1,state.routeCount??1)}`:'';if(time)time.textContent=`${formatTime(state.position)} / ${formatTime(state.duration)}`;if(progress){progress.max=String(Math.max(1,state.duration));if(document.activeElement!==progress)progress.value=String(Math.min(Math.max(0,state.position),Math.max(1,state.duration)));progress.disabled=state.domain==='live'&&state.duration<=0;}if(volume&&document.activeElement!==volume)volume.value=String(Math.round(state.volume));if(pause)pause.textContent=state.paused?'▶':'Ⅱ';}
ipcRenderer.on('fullscreen-overlay:state',(_event,state:OverlayState)=>{if(state&&typeof state==='object')render(state);});
window.addEventListener('DOMContentLoaded',()=>{byId<HTMLButtonElement>('pause')?.addEventListener('click',()=>send('pause-toggle'));byId<HTMLButtonElement>('exit')?.addEventListener('click',()=>send('exit'));byId<HTMLButtonElement>('nextVod')?.addEventListener('click',()=>send('next'));byId<HTMLButtonElement>('prev')?.addEventListener('click',()=>send('live-prev'));byId<HTMLButtonElement>('nextLive')?.addEventListener('click',()=>send('live-next'));byId<HTMLInputElement>('progress')?.addEventListener('change',event=>send('seek',Number((event.currentTarget as HTMLInputElement).value)));byId<HTMLInputElement>('volume')?.addEventListener('change',event=>send('volume',Number((event.currentTarget as HTMLInputElement).value)));for(const name of['mousemove','pointerdown','keydown','focusin'] as const)window.addEventListener(name,reveal,true);window.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();send('exit');}},true);reveal();});
