import { contextBridge,ipcRenderer } from 'electron';

const isUiSmoke=()=>process.env.FND_UI_SMOKE==='1'||process.argv.includes('--ui-smoke');
type LivePlayRequest={sourceId:string;channelId:string;routeIndex?:number;allowFallback?:boolean};
type LivePlayResult={ok:boolean;detail?:string;routeIndex:number;routeCount:number;attempts?:Array<{index:number;ok:boolean;detail?:string}>};
type LiveRouteSpeed={index:number;ok:boolean;latencyMs:number;bytes:number;kbps:number;message?:string};
type LiveChannelLite={id:string;name:string;group:string};
type LiveGroupLite={name:string;channels:LiveChannelLite[]};
type PlayerStatsLite={position?:number;paused?:boolean;pausedForCache?:boolean;fullscreen?:boolean;pip?:boolean;inputKey?:string;inputSequence?:number;domain?:'vod'|'live'|'music'|null;requestId?:string;sessionGeneration?:number;sessionStatus?:string;sessionLoadId?:string};
type RuntimeSession={generation:number;sessionId?:string;requestId:string;domain:'vod'|'live'|'music'|null;status:string;loadId?:string;sourceId?:string;channelId?:string;videoId?:string;episodeId?:string;trackId?:string;updatedAt:number};
type RouteChanged={sourceId:string;channelId:string;routeIndex:number;routeCount:number;reason:'play'|'auto-switch'|'channel-switch'};
type ActiveLiveSession={requestId:string;sourceId:string;channelId:string;routeIndex:number;routeCount:number;startedAt:number;lastProgressAt:number;lastPosition:number;positionObserved:boolean;lastSwitchAt:number;switchTimes:number[];stallStartedAt:number;switching:boolean;autoFallback:boolean};
type OverlayRendererAction={action:'next';requestId:string};

const liveGroupsCache=new Map<string,LiveGroupLite[]>();
const routeSpeedCache=new Map<string,{at:number;speeds:LiveRouteSpeed[]}>();
const quarantinedRoutes=new Map<string,number>();
const lastKnownGoodRoutes=new Map<string,number>();
const liveChannelIndexes=new Map<string,{channels:LiveChannelLite[];indexById:Map<string,number>}>();
const fullscreenListeners=new Set<(value:boolean)=>void>();
const routeChangedListeners=new Set<(value:RouteChanged)=>void>();
const runtimeSessionListeners=new Set<(value:RuntimeSession)=>void>();
const overlayActionListeners=new Set<(value:OverlayRendererAction)=>void>();
let activeLive:ActiveLiveSession|undefined;
let liveGeneration=0;
let playbackKind:'live'|'vod'|'music'|undefined;
let fullscreen=false;
let lastWindowSync:Record<string,unknown>|undefined;
let lastInputSequence=0;
let runtimeSession:RuntimeSession={generation:0,requestId:'',domain:null,status:'idle',updatedAt:Date.now()};

function routeKey(sourceId:string,channelId:string){return `${sourceId}\u0000${channelId}`;}
function routeQuarantineKey(sourceId:string,channelId:string,index:number){return `${routeKey(sourceId,channelId)}\u0000${index}`;}
function notifyFullscreen(value:boolean){if(fullscreen===value)return;fullscreen=value;for(const listener of fullscreenListeners)try{listener(value);}catch{/* renderer listener is best effort */}}
function notifyRouteChanged(value:RouteChanged){for(const listener of routeChangedListeners)try{listener(value);}catch{/* renderer listener is best effort */}}
function notifyRuntimeSession(value:RuntimeSession){if(value.generation<runtimeSession.generation)return;if(value.generation===runtimeSession.generation&&value.requestId===runtimeSession.requestId&&value.updatedAt<runtimeSession.updatedAt)return;runtimeSession=value;if(value.domain)playbackKind=value.domain;if(value.domain!=='live')activeLive=undefined;for(const listener of runtimeSessionListeners)try{listener(value);}catch{/* renderer listener is best effort */}}
function notifyOverlayAction(value:OverlayRendererAction){for(const listener of overlayActionListeners)try{listener(value);}catch{/* renderer listener is best effort */}}
function rankedRoutes(speeds:LiveRouteSpeed[]):LiveRouteSpeed[]{return[...speeds].sort((a,b)=>Number(!a.ok)-Number(!b.ok)||(a.latencyMs||Number.MAX_SAFE_INTEGER)-(b.latencyMs||Number.MAX_SAFE_INTEGER)||(b.kbps||0)-(a.kbps||0)||a.index-b.index);}
function cleanQuarantine(){const now=Date.now();for(const[key,until]of quarantinedRoutes)if(until<=now)quarantinedRoutes.delete(key);}
function recordMetric(metric:string,value:number):void{void ipcRenderer.invoke('diagnostics:recordPerformance',{metric,value}).catch(()=>undefined);}
function indexLiveGroups(sourceId:string,groups:LiveGroupLite[]):void{const channels=groups.flatMap(group=>group.channels);liveChannelIndexes.set(sourceId,{channels,indexById:new Map(channels.map((channel,index)=>[channel.id,index]))});}
async function speedTest(sourceId:string,channelId:string,force=false):Promise<LiveRouteSpeed[]>{const key=routeKey(sourceId,channelId),cached=routeSpeedCache.get(key);if(!force&&cached&&Date.now()-cached.at<5*60_000)return cached.speeds;const result=await ipcRenderer.invoke('live:speedTest',{sourceId,channelId}) as LiveRouteSpeed[];const speeds=Array.isArray(result)?result:[];routeSpeedCache.set(key,{at:Date.now(),speeds});return speeds;}
async function showOsd(text:string,durationMs=2500):Promise<void>{await ipcRenderer.invoke('playback:control',{command:'osd-text',value:text,durationMs}).catch(()=>undefined);}
function supersededError():Error{return new Error('[PLAYBACK_SUPERSEDED] 播放请求已被新的播放操作替代');}
function assertLiveGeneration(generation:number):void{if(generation!==liveGeneration)throw supersededError();}
async function authoritativeSession():Promise<RuntimeSession>{const value=await ipcRenderer.invoke('playback:runtimeSession') as RuntimeSession;if(value)notifyRuntimeSession(value);return value;}
async function assertLiveIntent(requestId:string,generation:number,session?:ActiveLiveSession):Promise<void>{assertLiveGeneration(generation);const current=await authoritativeSession();assertLiveGeneration(generation);if(current.domain!=='live'||current.requestId!==requestId||(session&&activeLive!==session))throw supersededError();}

async function rankedLiveCandidates(request:LivePlayRequest,generation:number,requestId:string,exclude=new Set<number>()):Promise<number[]>{
  await assertLiveIntent(requestId,generation);cleanQuarantine();let speeds:LiveRouteSpeed[]=[];const probeStarted=performance.now();
  try{speeds=rankedRoutes(await speedTest(request.sourceId,request.channelId));await assertLiveIntent(requestId,generation);}catch(error){if(error instanceof Error&&error.message.includes('PLAYBACK_SUPERSEDED'))throw error;}finally{recordMetric('routeProbeMs',performance.now()-probeStarted);}
  await assertLiveIntent(requestId,generation);const healthy=speeds.filter(item=>item.ok).map(item=>item.index),other=speeds.filter(item=>!item.ok).map(item=>item.index);const ordered=[...healthy,...other].filter(index=>!exclude.has(index)&&!quarantinedRoutes.has(routeQuarantineKey(request.sourceId,request.channelId,index)));return request.allowFallback===false?ordered.slice(0,1):ordered;
}
async function invokeLiveRoute(request:LivePlayRequest,generation:number,requestId:string,candidate:number|undefined,reason:RouteChanged['reason'],attempts:Array<{index:number;ok:boolean;detail?:string}>):Promise<LivePlayResult>{
  await assertLiveIntent(requestId,generation);const result=await ipcRenderer.invoke('live:play',{sourceId:request.sourceId,channelId:request.channelId,requestId,initiator:'user',...(candidate===undefined?{}:{routeIndex:candidate}),allowFallback:false}) as LivePlayResult;await assertLiveIntent(requestId,generation);if(!result?.ok)throw new Error(result?.detail??'线路打开失败');const now=Date.now();activeLive={requestId,sourceId:request.sourceId,channelId:request.channelId,routeIndex:result.routeIndex,routeCount:Math.max(1,result.routeCount),startedAt:now,lastProgressAt:now,lastPosition:0,positionObserved:false,lastSwitchAt:now,switchTimes:[],stallStartedAt:0,switching:false,autoFallback:request.allowFallback!==false};lastKnownGoodRoutes.set(routeKey(request.sourceId,request.channelId),result.routeIndex);notifyRouteChanged({sourceId:request.sourceId,channelId:request.channelId,routeIndex:result.routeIndex,routeCount:result.routeCount,reason});return{...result,attempts:[...attempts,...(result.attempts??[])]};
}
async function optimizedLivePlay(input:unknown,reason:RouteChanged['reason']='play'):Promise<LivePlayResult>{
  const request=(input&&typeof input==='object'?input:{}) as LivePlayRequest;if(!request.sourceId||!request.channelId)throw new Error('直播播放请求缺少 sourceId/channelId');const generation=++liveGeneration;playbackKind='live';activeLive=undefined;cleanQuarantine();
  const intent=await ipcRenderer.invoke('playback:beginIntent',{domain:'live',initiator:'user',sourceId:request.sourceId,channelId:request.channelId}) as RuntimeSession;assertLiveGeneration(generation);if(intent.domain!=='live'||!intent.requestId)throw new Error('无法建立直播播放会话');notifyRuntimeSession(intent);const requestId=intent.requestId;
  const attempts:Array<{index:number;ok:boolean;detail?:string}>=[],tried=new Set<number>();let lastError='没有可播放线路';
  try{
    const tryCandidate=async(candidate:number|undefined):Promise<LivePlayResult|undefined>=>{try{return await invokeLiveRoute(request,generation,requestId,candidate,reason,attempts);}catch(error){const message=error instanceof Error?error.message:String(error);if(message.includes('PLAYBACK_SUPERSEDED'))throw error;lastError=message;if(candidate!==undefined){tried.add(candidate);attempts.push({index:candidate,ok:false,detail:message});quarantinedRoutes.set(routeQuarantineKey(request.sourceId,request.channelId,candidate),Date.now()+120_000);if(lastKnownGoodRoutes.get(routeKey(request.sourceId,request.channelId))===candidate)lastKnownGoodRoutes.delete(routeKey(request.sourceId,request.channelId));}return undefined;}};
    if(request.routeIndex!==undefined){const direct=await tryCandidate(request.routeIndex);if(direct)return direct;if(request.allowFallback===false)throw new Error(`指定直播线路不可用：${lastError}`);}else{const remembered=lastKnownGoodRoutes.get(routeKey(request.sourceId,request.channelId));if(remembered!==undefined&&!quarantinedRoutes.has(routeQuarantineKey(request.sourceId,request.channelId,remembered))){const fast=await tryCandidate(remembered);if(fast)return fast;if(request.allowFallback===false)throw new Error(`最近可用直播线路失效：${lastError}`);}else{const optimistic=await tryCandidate(0);if(optimistic)return optimistic;}}
    await assertLiveIntent(requestId,generation);const selectStarted=performance.now(),ranked=await rankedLiveCandidates(request,generation,requestId,tried);recordMetric('routeSelectMs',performance.now()-selectStarted);await assertLiveIntent(requestId,generation);if(!ranked.length&&request.routeIndex===undefined&&!tried.size){const direct=await tryCandidate(undefined);if(direct)return direct;}for(const candidate of ranked){await assertLiveIntent(requestId,generation);const result=await tryCandidate(candidate);if(result)return result;if(request.allowFallback===false)break;}throw new Error(`所有直播线路均不可用：${lastError}`);
  }catch(error){const message=error instanceof Error?error.message:String(error);if(!message.includes('PLAYBACK_SUPERSEDED'))void ipcRenderer.invoke('playback:failIntent',{requestId,error:message}).catch(()=>undefined);throw error;}
}
async function autoSwitchLiveRoute():Promise<void>{
  const session=activeLive;if(!session||session.switching||!session.autoFallback)return;const now=Date.now();session.switchTimes=session.switchTimes.filter(time=>now-time<60_000);if(now-session.lastSwitchAt<15_000||session.switchTimes.length>=3)return;session.switching=true;const generation=++liveGeneration;
  try{
    await assertLiveIntent(session.requestId,generation,session);quarantinedRoutes.set(routeQuarantineKey(session.sourceId,session.channelId,session.routeIndex),now+120_000);if(lastKnownGoodRoutes.get(routeKey(session.sourceId,session.channelId))===session.routeIndex)lastKnownGoodRoutes.delete(routeKey(session.sourceId,session.channelId));const switchStarted=performance.now(),stallDuration=session.stallStartedAt?now-session.stallStartedAt:now-session.lastProgressAt;let speeds:LiveRouteSpeed[]=[];const probeStarted=performance.now();
    try{speeds=rankedRoutes(await speedTest(session.sourceId,session.channelId,true));await assertLiveIntent(session.requestId,generation,session);}catch(error){if(error instanceof Error&&error.message.includes('PLAYBACK_SUPERSEDED'))return;}finally{recordMetric('routeProbeMs',performance.now()-probeStarted);}
    await assertLiveIntent(session.requestId,generation,session);cleanQuarantine();const ranked=speeds.filter(item=>item.ok).map(item=>item.index),all=Array.from({length:session.routeCount},(_,index)=>index),candidates=[...new Set([...ranked,...all])].filter(index=>index!==session.routeIndex&&!quarantinedRoutes.has(routeQuarantineKey(session.sourceId,session.channelId,index)));
    for(const index of candidates){try{await assertLiveIntent(session.requestId,generation,session);const result=await ipcRenderer.invoke('live:play',{sourceId:session.sourceId,channelId:session.channelId,requestId:session.requestId,initiator:'auto-route',routeIndex:index,allowFallback:false}) as LivePlayResult;await assertLiveIntent(session.requestId,generation,session);if(!result?.ok)throw new Error(result?.detail??'线路切换失败');const previousRoute=session.routeIndex,switchedAt=Date.now();session.routeIndex=result.routeIndex;session.routeCount=result.routeCount;session.startedAt=switchedAt;session.lastProgressAt=switchedAt;session.lastPosition=0;session.positionObserved=false;session.lastSwitchAt=switchedAt;session.switchTimes.push(switchedAt);session.stallStartedAt=0;lastKnownGoodRoutes.set(routeKey(session.sourceId,session.channelId),result.routeIndex);routeSpeedCache.delete(routeKey(session.sourceId,session.channelId));recordMetric('routeSwitchMs',performance.now()-switchStarted);recordMetric('stallDurationMs',Math.max(0,stallDuration));recordMetric('automaticRouteSwitchCount',1);notifyRouteChanged({sourceId:session.sourceId,channelId:session.channelId,routeIndex:result.routeIndex,routeCount:result.routeCount,reason:'auto-switch'});void ipcRenderer.invoke('playback:recordRoute',{requestId:session.requestId,sourceId:session.sourceId,channelId:session.channelId,routeBefore:previousRoute,routeAfter:result.routeIndex,initiator:'auto-route'}).catch(()=>undefined);await showOsd(`线路卡顿，已自动切换到线路 ${result.routeIndex+1}/${result.routeCount}`);return;}catch(error){if(error instanceof Error&&error.message.includes('PLAYBACK_SUPERSEDED'))return;quarantinedRoutes.set(routeQuarantineKey(session.sourceId,session.channelId,index),Date.now()+120_000);}}
    await assertLiveIntent(session.requestId,generation,session);await showOsd('当前频道暂无更稳定的备用线路',3000);
  }finally{if(activeLive===session)session.switching=false;}
}
async function switchLiveChannel(offset:number):Promise<void>{const session=activeLive;if(!session)return;const indexed=liveChannelIndexes.get(session.sourceId);if(!indexed||indexed.channels.length<2)return;const current=indexed.indexById.get(session.channelId)??0,next=indexed.channels[(current+offset+indexed.channels.length)%indexed.channels.length];if(!next)return;try{const result=await optimizedLivePlay({sourceId:session.sourceId,channelId:next.id,allowFallback:session.autoFallback},'channel-switch');if(result.ok)await showOsd(`${next.name}\n线路 ${result.routeIndex+1}/${result.routeCount}`);}catch(error){if(!(error instanceof Error&&error.message.includes('PLAYBACK_SUPERSEDED')))await showOsd(`切换频道失败：${error instanceof Error?error.message:String(error)}`,3500);}}
async function showLiveChannelGuide():Promise<void>{const session=activeLive;if(!session)return;const indexed=liveChannelIndexes.get(session.sourceId);if(!indexed?.channels.length)return;const current=indexed.indexById.get(session.channelId)??0,rows:Array<string>=['频道列表（↑/↓ 切台，Esc 退出全屏）'];for(let delta=-2;delta<=2;delta+=1){const index=(current+delta+indexed.channels.length)%indexed.channels.length,channel=indexed.channels[index];if(channel)rows.push(`${delta===0?'▶':' '} ${channel.name}`);}await showOsd(rows.join('\n'),5000);}

async function playbackControl(command:unknown):Promise<{ok:boolean;detail?:string}>{const value=(command&&typeof command==='object'?command:{}) as Record<string,unknown>,fullscreenStarted=value.command==='fullscreen'?performance.now():0;const result=await ipcRenderer.invoke('playback:control',command) as {ok:boolean;detail?:string};if(result?.ok&&value.command==='window-sync')lastWindowSync={...value};if(result?.ok&&value.command==='fullscreen'){const next=value.value===true;notifyFullscreen(next);if(next){recordMetric('fullscreenEnterMs',performance.now()-fullscreenStarted);if(playbackKind==='live'&&activeLive)await showLiveChannelGuide();else await showOsd('空格：播放/暂停  ←/→：快退/快进  ↑/↓：音量  Esc：退出全屏',4000);}else{const restoreStarted=performance.now();if(lastWindowSync&&playbackKind!=='music')await ipcRenderer.invoke('playback:control',{...lastWindowSync,visible:true}).catch(()=>undefined);recordMetric('fullscreenExitRestoreMs',performance.now()-restoreStarted);}}return result;}
async function playbackQuery(query:'stats'|'tracks'|'load-status'){const result=await ipcRenderer.invoke('playback:query',query);if(query==='stats'&&result&&typeof result==='object'&&typeof(result as PlayerStatsLite).fullscreen==='boolean')notifyFullscreen(Boolean((result as PlayerStatsLite).fullscreen));return result;}
function consumeNativeInput(stats:PlayerStatsLite):void{const sequence=Number(stats.inputSequence??0);if(!sequence||sequence===lastInputSequence)return;lastInputSequence=sequence;if(!fullscreen||playbackKind!=='live'||!activeLive)return;if(stats.inputKey==='ArrowUp')void switchLiveChannel(-1);else if(stats.inputKey==='ArrowDown')void switchLiveChannel(1);else if(stats.inputKey==='Enter')void showLiveChannelGuide();}

setInterval(()=>{const session=activeLive;if(!session||playbackKind!=='live'||session.switching)return;void playbackQuery('stats').then(raw=>{if(activeLive!==session||!raw||typeof raw!=='object')return;const stats=raw as PlayerStatsLite,now=Date.now();consumeNativeInput(stats);if(stats.domain&&stats.domain!=='live'){activeLive=undefined;return;}if(stats.requestId&&stats.requestId!==session.requestId){activeLive=undefined;return;}if(stats.paused){session.stallStartedAt=0;session.lastProgressAt=now;return;}const position=Number(stats.position??0);if(position>session.lastPosition+.15){session.positionObserved=true;session.lastPosition=position;session.lastProgressAt=now;session.stallStartedAt=0;return;}if(stats.pausedForCache){if(!session.stallStartedAt)session.stallStartedAt=now;}else session.stallStartedAt=0;const cacheStall=session.stallStartedAt>0&&now-session.stallStartedAt>=5000,progressStall=session.positionObserved&&now-session.lastProgressAt>=6000;if(now-session.startedAt>=8000&&(cacheStall||progressStall))void autoSwitchLiveRoute();}).catch(()=>undefined);},1000);
setInterval(()=>{if(!fullscreen||playbackKind!=='live'||!activeLive)return;void playbackQuery('stats').then(raw=>{if(raw&&typeof raw==='object')consumeNativeInput(raw as PlayerStatsLite);}).catch(()=>undefined);},200);
window.addEventListener('keydown',event=>{const target=event.target as HTMLElement|null;if(target&&['INPUT','SELECT','TEXTAREA'].includes(target.tagName))return;if(event.key==='Escape'&&fullscreen){event.preventDefault();event.stopImmediatePropagation();void playbackControl({command:'fullscreen',value:false});return;}if(!fullscreen||playbackKind!=='live'||!activeLive)return;if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();event.stopImmediatePropagation();void switchLiveChannel(event.key==='ArrowUp'?-1:1);return;}if(event.key==='Enter'){event.preventDefault();event.stopImmediatePropagation();void showLiveChannelGuide();}},true);
ipcRenderer.on('playback:runtimeSessionChanged',(_event,value:RuntimeSession)=>{if(value&&typeof value==='object')notifyRuntimeSession(value);});
ipcRenderer.on('fullscreen-overlay:renderer-action',(_event,value:{action?:unknown;requestId?:unknown})=>{const requestId=typeof value?.requestId==='string'?value.requestId:'';if(!requestId||runtimeSession.requestId!==requestId)return;if(value.action==='live-prev'&&runtimeSession.domain==='live'&&activeLive){void switchLiveChannel(-1);return;}if(value.action==='live-next'&&runtimeSession.domain==='live'&&activeLive){void switchLiveChannel(1);return;}if(value.action==='next'&&runtimeSession.domain==='vod')notifyOverlayAction({action:'next',requestId});});

contextBridge.exposeInMainWorld('desktop',{
  app:{getInfo:()=>ipcRenderer.invoke('app:getInfo'),isUiSmoke,openRoute:(route:string)=>ipcRenderer.invoke('app:newWindow',route),action:(action:'reload'|'devtools'|'quit'|{copy:string})=>ipcRenderer.invoke('app:action',action),onNavigate:(listener:(path:string)=>void)=>{const handler=(_event:Electron.IpcRendererEvent,path:string)=>listener(path);ipcRenderer.on('app:navigate',handler);return()=>ipcRenderer.removeListener('app:navigate',handler);}},
  source:{ping:()=>ipcRenderer.invoke('source:ping'),list:()=>ipcRenderer.invoke('source:list'),save:(source:unknown)=>ipcRenderer.invoke('source:save',source),setEnabledBulk:(value:unknown)=>ipcRenderer.invoke('source:setEnabledBulk',value),remove:(sourceId:string)=>ipcRenderer.invoke('source:remove',{sourceId}),removeImportGroup:(importGroupId:string)=>ipcRenderer.invoke('source:removeImportGroup',{importGroupId}),checkImportGroup:(importGroupId:string)=>ipcRenderer.invoke('source:checkImportGroup',{importGroupId}),home:(sourceId:string,force=false)=>ipcRenderer.invoke('source:home',{sourceId,force}),category:(sourceId:string,categoryId:string,page=1,filters:Record<string,string>={},force=false)=>ipcRenderer.invoke('source:category',{sourceId,categoryId,page,filters,force}),search:(sourceId:string,keyword:string,page=1,force=false)=>ipcRenderer.invoke('source:search',{sourceId,keyword,page,force}),detail:(sourceId:string,ids:string[],force=false)=>ipcRenderer.invoke('source:detail',{sourceId,ids,force}),aggregateSearch:(keyword:string)=>ipcRenderer.invoke('source:aggregateSearch',keyword),cancelAggregateSearch:()=>ipcRenderer.invoke('source:cancelAggregateSearch'),audit:(sourceId:string)=>ipcRenderer.invoke('source:audit',{sourceId}),exportAudit:(sourceId:string)=>ipcRenderer.invoke('source:exportAudit',{sourceId}),health:()=>ipcRenderer.invoke('source:health'),onHealthChanged:(listener:(value:{ok:boolean;checkedAt:string})=>void)=>{const handler=(_event:Electron.IpcRendererEvent,value:{ok:boolean;checkedAt:string})=>listener(value);ipcRenderer.on('source:healthChanged',handler);return()=>ipcRenderer.removeListener('source:healthChanged',handler);}},
  config:{importText:(text:string)=>ipcRenderer.invoke('config:importText',text),importFile:()=>ipcRenderer.invoke('config:importFile')},
  live:{listSources:()=>ipcRenderer.invoke('live:listSources'),importFile:()=>ipcRenderer.invoke('live:importFile'),importUrl:(value:unknown)=>ipcRenderer.invoke('live:importUrl',value),saveSource:(source:unknown)=>ipcRenderer.invoke('live:saveSource',source),removeSource:(sourceId:string)=>ipcRenderer.invoke('live:removeSource',{sourceId}),channels:async(sourceId:string,force=false)=>{const groups=await ipcRenderer.invoke('live:channels',{sourceId,force}) as LiveGroupLite[];const safeGroups=Array.isArray(groups)?groups:[];liveGroupsCache.set(sourceId,safeGroups);indexLiveGroups(sourceId,safeGroups);return groups;},play:(request:unknown)=>optimizedLivePlay(request),speedTest:async(sourceId:string,channelId:string)=>speedTest(sourceId,channelId,true),favorites:()=>ipcRenderer.invoke('live:favorites'),toggleFavorite:(liveSourceId:string,channelId:string)=>ipcRenderer.invoke('live:toggleFavorite',{liveSourceId,channelId}),saveFavorite:(value:unknown)=>ipcRenderer.invoke('live:saveFavorite',value),removeFavorite:(liveSourceId:string,channelId:string)=>ipcRenderer.invoke('live:removeFavorite',{liveSourceId,channelId}),onRouteChanged:(listener:(value:RouteChanged)=>void)=>{routeChangedListeners.add(listener);return()=>routeChangedListeners.delete(listener);}},
  epg:{refresh:(liveSourceId:string)=>ipcRenderer.invoke('epg:refresh',{sourceId:liveSourceId}),list:(liveSourceId:string,channelId?:string)=>ipcRenderer.invoke('epg:list',{liveSourceId,channelId})},
  music:{listSources:()=>ipcRenderer.invoke('music:listSources'),addLocalSource:()=>ipcRenderer.invoke('music:addLocalSource'),addNetworkSource:(value:unknown)=>ipcRenderer.invoke('music:addNetworkSource',value),scan:(sourceId:string)=>ipcRenderer.invoke('music:scan',{sourceId}),cancelScan:(sourceId:string)=>ipcRenderer.invoke('music:cancelScan',{sourceId}),removeSource:(sourceId:string)=>ipcRenderer.invoke('music:removeSource',{sourceId}),listTracks:(sourceId?:string,query?:string,limit=5000)=>ipcRenderer.invoke('music:listTracks',{...(sourceId?{sourceId}:{}),...(query?{query}:{}),limit}),toggleFavorite:(trackId:string)=>ipcRenderer.invoke('music:toggleFavorite',{trackId}),artwork:(trackId:string,options?:{online?:boolean})=>ipcRenderer.invoke('music:artwork',{trackId,...options}),lyrics:(trackId:string)=>ipcRenderer.invoke('music:lyrics',{trackId}),capabilities:()=>ipcRenderer.invoke('music:capabilities'),play:(request:unknown)=>{liveGeneration+=1;activeLive=undefined;playbackKind='music';return ipcRenderer.invoke('music:play',request);}},
  playback:{play:(request:unknown)=>{playbackKind='vod';activeLive=undefined;liveGeneration+=1;const value=request&&typeof request==='object'?{...(request as Record<string,unknown>)}:{};if(value.initiator==='auto-next'&&runtimeSession.domain==='vod'&&runtimeSession.episodeId&&!value.fromEpisodeId)value.fromEpisodeId=runtimeSession.episodeId;return ipcRenderer.invoke('playback:play',value);},control:playbackControl,query:playbackQuery,runtimeSession:async()=>authoritativeSession(),claimNaturalEnd:(value:{loadId:string;requestId:string;domain:'vod'|'music'})=>ipcRenderer.invoke('playback:claimNaturalEnd',value),screenshot:()=>ipcRenderer.invoke('playback:screenshot'),smokeLoad:()=>ipcRenderer.invoke('playback:smokeLoad'),onStageChanged:(listener:(value:{stage:string;message:string;error?:string;at:number})=>void)=>{const handler=(_event:Electron.IpcRendererEvent,value:{stage:string;message:string;error?:string;at:number})=>{if(value.error?.includes('PLAYBACK_SUPERSEDED')||value.message.includes('PLAYBACK_SUPERSEDED'))return;listener(value);};ipcRenderer.on('playback:stageChanged',handler);return()=>ipcRenderer.removeListener('playback:stageChanged',handler);},onFullscreenChanged:(listener:(value:boolean)=>void)=>{fullscreenListeners.add(listener);listener(fullscreen);return()=>fullscreenListeners.delete(listener);},onRuntimeSessionChanged:(listener:(value:RuntimeSession)=>void)=>{runtimeSessionListeners.add(listener);listener(runtimeSession);return()=>runtimeSessionListeners.delete(listener);},onOverlayAction:(listener:(value:OverlayRendererAction)=>void)=>{overlayActionListeners.add(listener);return()=>overlayActionListeners.delete(listener);}},
  history:{list:(limit=20)=>ipcRenderer.invoke('history:list',limit),updateProgress:(id:string,position:number,duration:number)=>ipcRenderer.invoke('history:updateProgress',{id,position,duration}),remove:(id:string)=>ipcRenderer.invoke('history:remove',id),clear:()=>ipcRenderer.invoke('history:clear')},
  reservation:{list:()=>ipcRenderer.invoke('reservation:list'),save:(value:unknown)=>ipcRenderer.invoke('reservation:save',value),remove:(id:string)=>ipcRenderer.invoke('reservation:remove',id)},
  settings:{list:()=>ipcRenderer.invoke('settings:list'),set:(key:string,value:string)=>ipcRenderer.invoke('settings:set',{key,value})},
  cache:{stats:()=>ipcRenderer.invoke('cache:stats'),clear:(namespace?:string)=>ipcRenderer.invoke('cache:clear',namespace)},
  diagnostics:{get:()=>ipcRenderer.invoke('diagnostics:get'),events:(limit=20)=>ipcRenderer.invoke('diagnostics:events',limit),selfTestItem:(index:number)=>ipcRenderer.invoke('diagnostics:selfTestItem',index),export:()=>ipcRenderer.invoke('diagnostics:export'),recordPerformance:(metric:string,value:number)=>ipcRenderer.invoke('diagnostics:recordPerformance',{metric,value})},
  maintenance:{openPath:(kind:'logs'|'temp'|`cache:${string}`)=>ipcRenderer.invoke('maintenance:openPath',kind)},
  update:{check:(channel:'stable'|'daily'='stable')=>ipcRenderer.invoke('update:check',channel),openReleases:()=>ipcRenderer.invoke('update:openReleases')}
});
