import { contextBridge,ipcRenderer } from 'electron';
const isUiSmoke=()=>process.env.FND_UI_SMOKE==='1'||process.argv.includes('--ui-smoke');
contextBridge.exposeInMainWorld('desktop',{
  app:{getInfo:()=>ipcRenderer.invoke('app:getInfo'),isUiSmoke,openRoute:(route:string)=>ipcRenderer.invoke('app:newWindow',route),action:(action:'reload'|'devtools'|'quit'|{copy:string})=>ipcRenderer.invoke('app:action',action),onNavigate:(listener:(path:string)=>void)=>{const handler=(_event:Electron.IpcRendererEvent,path:string)=>listener(path);ipcRenderer.on('app:navigate',handler);return()=>ipcRenderer.removeListener('app:navigate',handler);}},
  source:{ping:()=>ipcRenderer.invoke('source:ping'),list:()=>ipcRenderer.invoke('source:list'),save:(source:unknown)=>ipcRenderer.invoke('source:save',source),setEnabledBulk:(value:unknown)=>ipcRenderer.invoke('source:setEnabledBulk',value),remove:(sourceId:string)=>ipcRenderer.invoke('source:remove',{sourceId}),removeImportGroup:(importGroupId:string)=>ipcRenderer.invoke('source:removeImportGroup',{importGroupId}),checkImportGroup:(importGroupId:string)=>ipcRenderer.invoke('source:checkImportGroup',{importGroupId}),home:(sourceId:string,force=false)=>ipcRenderer.invoke('source:home',{sourceId,force}),category:(sourceId:string,categoryId:string,page=1,filters:Record<string,string>={},force=false)=>ipcRenderer.invoke('source:category',{sourceId,categoryId,page,filters,force}),search:(sourceId:string,keyword:string,page=1,force=false)=>ipcRenderer.invoke('source:search',{sourceId,keyword,page,force}),detail:(sourceId:string,ids:string[],force=false)=>ipcRenderer.invoke('source:detail',{sourceId,ids,force}),aggregateSearch:(keyword:string)=>ipcRenderer.invoke('source:aggregateSearch',keyword),cancelAggregateSearch:()=>ipcRenderer.invoke('source:cancelAggregateSearch'),audit:(sourceId:string)=>ipcRenderer.invoke('source:audit',{sourceId}),exportAudit:(sourceId:string)=>ipcRenderer.invoke('source:exportAudit',{sourceId}),health:()=>ipcRenderer.invoke('source:health'),onHealthChanged:(listener:(value:{ok:boolean;checkedAt:string})=>void)=>{const handler=(_event:Electron.IpcRendererEvent,value:{ok:boolean;checkedAt:string})=>listener(value);ipcRenderer.on('source:healthChanged',handler);return()=>ipcRenderer.removeListener('source:healthChanged',handler);}},
  config:{importText:(text:string)=>ipcRenderer.invoke('config:importText',text),importFile:()=>ipcRenderer.invoke('config:importFile')},
  live:{listSources:()=>ipcRenderer.invoke('live:listSources'),importFile:()=>ipcRenderer.invoke('live:importFile'),importUrl:(value:unknown)=>ipcRenderer.invoke('live:importUrl',value),saveSource:(source:unknown)=>ipcRenderer.invoke('live:saveSource',source),removeSource:(sourceId:string)=>ipcRenderer.invoke('live:removeSource',{sourceId}),channels:(sourceId:string,force=false)=>ipcRenderer.invoke('live:channels',{sourceId,force}),play:(request:unknown)=>ipcRenderer.invoke('live:play',request),speedTest:(sourceId:string,channelId:string)=>ipcRenderer.invoke('live:speedTest',{sourceId,channelId}),favorites:()=>ipcRenderer.invoke('live:favorites'),toggleFavorite:(liveSourceId:string,channelId:string)=>ipcRenderer.invoke('live:toggleFavorite',{liveSourceId,channelId}),saveFavorite:(value:unknown)=>ipcRenderer.invoke('live:saveFavorite',value),removeFavorite:(liveSourceId:string,channelId:string)=>ipcRenderer.invoke('live:removeFavorite',{liveSourceId,channelId})},
  epg:{refresh:(liveSourceId:string)=>ipcRenderer.invoke('epg:refresh',{sourceId:liveSourceId}),list:(liveSourceId:string,channelId?:string)=>ipcRenderer.invoke('epg:list',{liveSourceId,channelId})},
  playback:{play:(request:unknown)=>ipcRenderer.invoke('playback:play',request),control:(command:unknown)=>ipcRenderer.invoke('playback:control',command),query:(query:'stats'|'tracks'|'load-status')=>ipcRenderer.invoke('playback:query',query),screenshot:()=>ipcRenderer.invoke('playback:screenshot'),smokeLoad:()=>ipcRenderer.invoke('playback:smokeLoad'),onStageChanged:(listener:(value:{stage:string;message:string;error?:string;at:number})=>void)=>{const handler=(_event:Electron.IpcRendererEvent,value:{stage:string;message:string;error?:string;at:number})=>listener(value);ipcRenderer.on('playback:stageChanged',handler);return()=>ipcRenderer.removeListener('playback:stageChanged',handler);}},
  history:{list:(limit=20)=>ipcRenderer.invoke('history:list',limit),updateProgress:(id:string,position:number,duration:number)=>ipcRenderer.invoke('history:updateProgress',{id,position,duration}),remove:(id:string)=>ipcRenderer.invoke('history:remove',id),clear:()=>ipcRenderer.invoke('history:clear')},
  reservation:{list:()=>ipcRenderer.invoke('reservation:list'),save:(value:unknown)=>ipcRenderer.invoke('reservation:save',value),remove:(id:string)=>ipcRenderer.invoke('reservation:remove',id)},
  settings:{list:()=>ipcRenderer.invoke('settings:list'),set:(key:string,value:string)=>ipcRenderer.invoke('settings:set',{key,value})},
  cache:{stats:()=>ipcRenderer.invoke('cache:stats'),clear:(namespace?:string)=>ipcRenderer.invoke('cache:clear',namespace)},
  diagnostics:{get:()=>ipcRenderer.invoke('diagnostics:get'),events:(limit=20)=>ipcRenderer.invoke('diagnostics:events',limit),selfTestItem:(index:number)=>ipcRenderer.invoke('diagnostics:selfTestItem',index),export:()=>ipcRenderer.invoke('diagnostics:export'),recordPerformance:(metric:string,value:number)=>ipcRenderer.invoke('diagnostics:recordPerformance',{metric,value})},
  maintenance:{openPath:(kind:'logs'|'temp'|`cache:${string}`)=>ipcRenderer.invoke('maintenance:openPath',kind)},
  update:{check:(channel:'stable'|'daily'='stable')=>ipcRenderer.invoke('update:check',channel),openReleases:()=>ipcRenderer.invoke('update:openReleases')}
});
