import type { CategoryResult,DetailResult,HomeResult,PlayResult,SearchResult,SourceAdapter,SourceContext } from '@free-new-desk/contracts';
import { RequestBroker } from '@free-new-desk/source-sdk';

const directProtocol=/^(?:rtmp|rtsp|udp):/i;
const httpProtocol=/^https?:/i;
const mediaUrl=/\.(?:m3u8|mp4|m4v|flv|mpd|ts|mkv|webm|aac|m4a)(?:[?#]|$)/i;
function canonicalHeaderName(value:string):string{const lower=value.trim().toLowerCase().replace(/_/g,'-');if(lower==='user-agent'||lower==='useragent'||lower==='ua')return'User-Agent';if(lower==='referer'||lower==='referrer')return'Referer';if(lower==='origin')return'Origin';if(lower==='cookie')return'Cookie';return value.trim();}
function splitPlay(value:string):{url:string;headers?:Record<string,string>}{const pipe=value.indexOf('|');if(pipe<0)return{url:value};const url=value.slice(0,pipe).trim();const headers:Record<string,string>={};for(const pair of value.slice(pipe+1).split('&')){const split=pair.indexOf('=');if(split<=0)continue;const key=pair.slice(0,split).trim(),raw=pair.slice(split+1).trim();try{headers[canonicalHeaderName(decodeURIComponent(key))]=decodeURIComponent(raw.replace(/\+/g,'%20'));}catch{headers[canonicalHeaderName(key)]=raw;}}return{url,...(Object.keys(headers).length?{headers}:{})};}

export abstract class BaseAdapter implements SourceAdapter{protected readonly broker:RequestBroker;protected context:SourceContext|undefined;constructor(protected readonly endpoint:string,broker?:RequestBroker){this.broker=broker??new RequestBroker();}async init(ctx:SourceContext):Promise<void>{this.context=ctx;this.broker.setDefaultHeaders(ctx.sourceId,ctx.requestHeaders);}protected sourceId():string{if(!this.context)throw new Error('Source adapter is not initialized');return this.context.sourceId;}abstract getHome():Promise<HomeResult>;abstract getCategory(categoryId:string,page:number,filters?:Record<string,string>):Promise<CategoryResult>;abstract getDetail(ids:string[]):Promise<DetailResult>;abstract search(keyword:string,page?:number):Promise<SearchResult>;async getPlay(_flag:string,id:string):Promise<PlayResult>{const value=id.trim();const parsed=splitPlay(value);const direct=directProtocol.test(parsed.url)||(httpProtocol.test(parsed.url)&&mediaUrl.test(parsed.url));return{url:parsed.url,parse:!direct,...(parsed.headers?{headers:parsed.headers}:{})};}async destroy():Promise<void>{if(this.context){this.broker.clearCookies(this.context.sourceId);this.broker.clearDefaultHeaders(this.context.sourceId);}this.context=undefined;}}
