import type { CategoryResult,DetailResult,HomeResult,PlayResult,SearchResult,VideoCard } from '@free-new-desk/contracts';
import { BaseAdapter } from './base.js';
import { jsonDetail,jsonList,parseCmsJson,pathValue,stringValue,type CmsJsonPayload,type JsonRecord } from './common.js';

interface RuleSpec{home?:string;category?:string;search?:string;detail?:string;play?:string;itemRegex?:string;idRegex?:string;nameRegex?:string;picRegex?:string;remarkRegex?:string;listPath?:string;idPath?:string;namePath?:string;picPath?:string;remarkPath?:string;}
function ruleSpec(raw:string|undefined):RuleSpec{if(!raw)return{};try{const value=JSON.parse(raw) as JsonRecord;return{home:stringValue(value.home??value.homeUrl??value['首页推荐链接']),category:stringValue(value.category??value.categoryUrl??value['分类链接']),search:stringValue(value.search??value.searchUrl??value['搜索链接']??value['搜索url']),detail:stringValue(value.detail??value.detailUrl??value['详情链接']),play:stringValue(value.play??value.playUrl??value['播放链接']),itemRegex:stringValue(value.itemRegex??value['列表数组']),idRegex:stringValue(value.idRegex??value['链接']),nameRegex:stringValue(value.nameRegex??value['标题']),picRegex:stringValue(value.picRegex??value['图片']),remarkRegex:stringValue(value.remarkRegex??value['副标题']),listPath:stringValue(value.listPath??value['数组路径']),idPath:stringValue(value.idPath??value['链接字段']),namePath:stringValue(value.namePath??value['标题字段']),picPath:stringValue(value.picPath??value['图片字段']),remarkPath:stringValue(value.remarkPath??value['副标题字段'])};}catch{return{};}}
function applyTemplate(base:string,template:string,values:Record<string,string|number>):string{const replaced=template.replace(/\{(\w+)\}|\[(\w+)\]/g,(_all,a:string,b:string)=>encodeURIComponent(String(values[a||b]??'')));return new URL(replaced||base,base).toString();}
function capture(value:string,pattern?:string):string{if(!pattern)return'';try{return value.match(new RegExp(pattern,'is'))?.[1]?.trim()??'';}catch{return'';}}
function regexCards(html:string,spec:RuleSpec):VideoCard[]{if(!spec.itemRegex)return[];let regex:RegExp;try{regex=new RegExp(spec.itemRegex,'gis');}catch{return[];}const cards:VideoCard[]=[];for(const match of html.matchAll(regex)){const block=match[1]??match[0],id=capture(block,spec.idRegex),name=capture(block,spec.nameRegex);if(!id||!name)continue;const poster=capture(block,spec.picRegex),remark=capture(block,spec.remarkRegex);cards.push({id,name,...(poster?{poster}:{}),...(remark?{remark}:{})});}return cards;}
function jsonCards(value:unknown,spec:RuleSpec):VideoCard[]{const list=spec.listPath?pathValue(value,spec.listPath):Array.isArray(value)?value:undefined;if(!Array.isArray(list))return[];return list.map(row=>{const item=row as JsonRecord;const id=stringValue(spec.idPath?pathValue(item,spec.idPath):item.id??item.vod_id),name=stringValue(spec.namePath?pathValue(item,spec.namePath):item.name??item.vod_name),poster=stringValue(spec.picPath?pathValue(item,spec.picPath):item.pic??item.vod_pic),remark=stringValue(spec.remarkPath?pathValue(item,spec.remarkPath):item.remark??item.vod_remarks);return{id,name,...(poster?{poster}:{}),...(remark?{remark}:{})};}).filter(item=>item.id&&item.name);}

export class DeclarativeRuleAdapter extends BaseAdapter{
  readonly #spec:RuleSpec;
  constructor(endpoint:string,ext?:string){super(endpoint);this.#spec=ruleSpec(ext);}
  async #cards(url:string):Promise<VideoCard[]>{const text=await this.broker.text({sourceId:this.sourceId(),url,retries:1});try{const parsed=JSON.parse(text) as unknown;const custom=jsonCards(parsed,this.#spec);return custom.length?custom:parseCmsJson(parsed as CmsJsonPayload);}catch{return regexCards(text,this.#spec);}}
  async getHome():Promise<HomeResult>{return{items:await this.#cards(applyTemplate(this.endpoint,this.#spec.home??this.endpoint,{}))};}
  async getCategory(categoryId:string,page:number,filters:Record<string,string>={}):Promise<CategoryResult>{const template=this.#spec.category??this.#spec.home??this.endpoint;return{page,hasMore:false,items:await this.#cards(applyTemplate(this.endpoint,template,{categoryId,tid:categoryId,page,...filters}))};}
  async search(keyword:string,page=1):Promise<SearchResult>{if(!this.#spec.search)return{page,items:[]};return{page,items:await this.#cards(applyTemplate(this.endpoint,this.#spec.search,{keyword,wd:keyword,page}))};}
  async getDetail(ids:string[]):Promise<DetailResult>{const id=ids[0]??'';if(!this.#spec.detail)return{id,name:id,episodes:[{flag:'直连',id,name:'播放'}]};const text=await this.broker.text({sourceId:this.sourceId(),url:applyTemplate(this.endpoint,this.#spec.detail,{id}),retries:1});try{const payload=JSON.parse(text) as CmsJsonPayload;const item=jsonList(payload)[0];if(item)return jsonDetail(item);}catch{/* html fallback */}return{id,name:id,description:text.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,1200),episodes:[{flag:'规则',id:this.#spec.play?applyTemplate(this.endpoint,this.#spec.play,{id}):id,name:'播放'}]};}
  override async getPlay(_flag:string,id:string):Promise<PlayResult>{const url=this.#spec.play?applyTemplate(this.endpoint,this.#spec.play,{id}):id;return{url,parse:!/^https?:\/\//i.test(url)};}
}
