import { createDecipheriv,createHash } from 'node:crypto';
import type { LiveSourceConfig,SourceConfig,SourceKind,TVBoxImportResult } from '@free-new-desk/contracts';
type UnknownRecord=Record<string,unknown>;
export interface TVBoxParseOptions{baseUrl?:string;configKey?:string;}
const MAX_CONFIG_BYTES=8*1024*1024;
const text=(value:unknown)=>typeof value==='string'||typeof value==='number'?String(value).trim():'';
const bool=(value:unknown,fallback=true)=>typeof value==='boolean'?value:typeof value==='number'?value!==0:typeof value==='string'&&/^(?:0|1)$/.test(value)?value==='1':fallback;
export type ConfigShell='plain'|'base64-star-v1'|'hex-wrapper-v1'|'hex-dollar-cbc-v1'|'pk-aes-ecb-v1'|'dollar-unknown';
export interface UnshellResult{text:string;shell:ConfigShell;decoded:boolean;}
function assertConfigSize(value:string):void{if(Buffer.byteLength(value,'utf8')>MAX_CONFIG_BYTES)throw new Error('[SRC_CONFIG_FORMAT_INVALID] TVBox 配置超过 8 MB 安全限制');}
function looksLikeTvBox(value:string):boolean{const candidate=value.trim();return(candidate.startsWith('{')||candidate.startsWith('['))&&/(?:\"sites\"|\"lives\"|\"spider\")/.test(candidate);}
function padded16(value:string):Buffer{const normalized=value.trim().slice(0,16).padEnd(16,'0');return Buffer.from(normalized,'utf8');}
function decryptHexAes(dataHex:string,key:string,mode:'cbc'|'ecb',iv?:string):string|null{if(!/^[0-9a-f]+$/i.test(dataHex)||dataHex.length%2!==0)return null;try{const decipher=createDecipheriv(mode==='cbc'?'aes-128-cbc':'aes-128-ecb',padded16(key),mode==='cbc'?padded16(iv??''):null);decipher.setAutoPadding(true);return Buffer.concat([decipher.update(Buffer.from(dataHex,'hex')),decipher.final()]).toString('utf8').replace(/^\uFEFF/,'');}catch{return null;}}
function decodeHexDollarCbc(value:string):string|null{const hex=value.trim().toLowerCase();if(!hex.startsWith('2423')||!/^[0-9a-f]+$/.test(hex)||hex.length%2!==0)return null;const delimiter=hex.indexOf('2324');if(delimiter<4||hex.length<=delimiter+4+26)return null;try{const prefix=Buffer.from(hex.slice(0,delimiter+4),'hex').toString('utf8').toLowerCase();const keyMatch=/\$#([^#$]{1,64})#\$/.exec(prefix);if(!keyMatch?.[1])return null;const ivTail=Buffer.from(hex.slice(-26),'hex').toString('utf8').toLowerCase();if(ivTail.length!==13)return null;const plain=decryptHexAes(hex.slice(delimiter+4,-26),keyMatch[1],'cbc',ivTail);return plain&&looksLikeTvBox(plain)?plain:null;}catch{return null;}}
function decodePkEcb(value:string,configKey:string):string|null{const plain=decryptHexAes(value.trim(),configKey,'ecb');return plain&&looksLikeTvBox(plain)?plain:null;}
export function unshell(raw:string,depth=0,options:{configKey?:string}={}):UnshellResult{assertConfigSize(raw);if(depth>3)return{text:raw,shell:'dollar-unknown',decoded:false};const t=raw.replace(/^\uFEFF/,'').trim();if(!t)return{text:raw,shell:'plain',decoded:false};if(t.startsWith('{')||t.startsWith('[')||t.startsWith('//')||t.startsWith('/*'))return{text:raw,shell:'plain',decoded:false};const star=t.match(/^([A-Za-z0-9]{6,32})\*\*([A-Za-z0-9+/=_-]{16,})$/s);if(star)try{const decoded=Buffer.from(star[2]!.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8');if(looksLikeTvBox(decoded)||decoded.trimStart().startsWith('//'))return{text:decoded,shell:'base64-star-v1',decoded:true};}catch{/* fall through */}if(/^2423/i.test(t)){const decoded=decodeHexDollarCbc(t);if(decoded)return{text:decoded,shell:'hex-dollar-cbc-v1',decoded:true};return{text:raw,shell:'dollar-unknown',decoded:false};}if(options.configKey&&/^[0-9a-f]+$/i.test(t)&&t.length%2===0){const decoded=decodePkEcb(t,options.configKey);if(decoded)return{text:decoded,shell:'pk-aes-ecb-v1',decoded:true};return{text:raw,shell:'dollar-unknown',decoded:false};}if(/^[0-9a-f]+$/i.test(t)&&t.length%2===0){try{const decoded=Buffer.from(t,'hex').toString('utf8');if(/[\x09\x0a\x0d\x20-\x7e\u0080-\uffff]/.test(decoded)){const inner=unshell(decoded,depth+1,options);return{text:inner.text,shell:'hex-wrapper-v1',decoded:true};}}catch{/* fall through */}}if(/^\$#[^#$]{1,64}#\$/.test(t))return{text:raw,shell:'dollar-unknown',decoded:false};return{text:raw,shell:'plain',decoded:false};}
function stableId(prefix:string,value:string):string{return `${prefix}-${createHash('sha1').update(value).digest('hex').slice(0,16)}`;}
function withoutComments(input:string):string{let output='',quote='',escaped=false;for(let index=0;index<input.length;index+=1){const ch=input[index]??'',next=input[index+1]??'';if(quote){output+=ch;if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote='';continue;}if(ch==='"'||ch==="'"){quote=ch;output+=ch;continue;}if(ch==='/'&&next==='/'){while(index<input.length&&input[index]!=='\n')index+=1;output+='\n';continue;}if(ch==='/'&&next==='*'){index+=2;while(index<input.length-1&&!(input[index]==='*'&&input[index+1]==='/'))index+=1;index+=1;output+=' ';continue;}output+=ch;}return output;}
function withoutTrailingCommas(input:string):string{let output='',quote='',escaped=false;for(let index=0;index<input.length;index+=1){const ch=input[index]??'';if(quote){output+=ch;if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch===quote)quote='';continue;}if(ch==='"'||ch==="'"){quote=ch;output+=ch;continue;}if(ch===','){let cursor=index+1;while(cursor<input.length&&/\s/.test(input[cursor]??''))cursor+=1;if(input[cursor]===']'||input[cursor]==='}')continue;}output+=ch;}return output;}
function parseConfigObject(input:string):UnknownRecord{const normalized=input.replace(/^\uFEFF/,'').trim();try{return JSON.parse(normalized) as UnknownRecord;}catch(first){const relaxed=withoutTrailingCommas(withoutComments(normalized));try{return JSON.parse(relaxed) as UnknownRecord;}catch{throw first;}}}
function resource(value:string,baseUrl?:string):string{if(!value||!baseUrl||/^[a-z][a-z0-9+.-]*:/i.test(value)||/^csp_/i.test(value)||/^[A-Za-z]:[\\/]/.test(value))return value;if(!/^(?:\.\.?\/|\/)/.test(value))return value;try{return new URL(value,baseUrl).toString();}catch{return value;}}
function resourceSpec(value:string,baseUrl?:string):string{const parts=value.split(';');const location=resource((parts.shift()??'').trim(),baseUrl);return[location,...parts].join(';');}
function parserResource(value:string,baseUrl?:string):string{if(!value)return'';if(/^json:/i.test(value))return'json:'+resource(value.slice(5),baseUrl);return resource(value,baseUrl);}
function sourceKind(site:UnknownRecord):SourceKind{const type=Number(site.type??1);const api=text(site.api).toLowerCase();const ext=text(site.ext).toLowerCase();const probe=`${api} ${ext}`;if(type===0)return'T0_XML';if(type===1)return'T1_JSON';if(type===4)return'T4_EXT';if(/\.jar(?:\?|$)|^csp_/i.test(api)||text(site.jar))return'T3_JAR';if(/xyq|香雅情/.test(probe))return'T3_XYQ';if(/xbpq/.test(probe))return'T3_XBPQ';if(/alist|网盘/.test(probe))return'DRIVE_ALIST';if(/\.js(?:\?|$)|drpy|js/.test(probe))return'T3_JS';return'T4_CATVOD';}
function executable(kind:SourceKind):boolean{return kind==='T3_JS'||kind==='T3_JAR'||kind==='T4_CATVOD';}
function normalizeExt(value:unknown,baseUrl?:string):string|undefined{if(value===undefined||value===null||value==='')return undefined;if(typeof value!=='string')return JSON.stringify(value);return resource(value.trim(),baseUrl);}
function stringRecord(value:unknown):Record<string,string>|undefined{if(!value||typeof value!=='object'||Array.isArray(value))return undefined;const entries=Object.entries(value as UnknownRecord).filter(([,item])=>typeof item==='string'||typeof item==='number').map(([key,item])=>[key,String(item)] as[string,string]);return entries.length?Object.fromEntries(entries):undefined;}
function stringArray(value:unknown):string[]|undefined{if(!Array.isArray(value))return undefined;const items=value.map(text).filter(Boolean);return items.length?items:undefined;}
function normalizeSite(value:unknown,index:number,globalSpider:string,baseUrl?:string):SourceConfig|null{if(!value||typeof value!=='object')return null;const site=value as UnknownRecord;const name=text(site.name)||text(site.key)||`来源 ${index+1}`;const api=resource(text(site.api),baseUrl);const ext=normalizeExt(site.ext,baseUrl);const endpoint=api||ext||'';if(!endpoint)return null;const kind=sourceKind(site);const isExecutable=executable(kind);const id=text(site.key)||stableId('site',`${name}|${endpoint}|${index}`);const headers=stringRecord(site.header),categories=stringArray(site.categories);const playUrl=parserResource(text(site.playUrl),baseUrl);const playerTypeRaw=Number(site.playerType);const playerType=Number.isInteger(playerTypeRaw)?playerTypeRaw:undefined;const ownJar=text(site.jar);const jar=kind==='T3_JAR'?resourceSpec(ownJar||globalSpider,baseUrl):ownJar?resourceSpec(ownJar,baseUrl):'';return{id,name,kind,endpoint,enabled:!isExecutable,trust:isExecutable?'B':'A',searchable:bool(site.searchable,true),...(ext?{ext}:{}),...(jar?{jar}:{}),...(headers?{headers}:{}),...(categories?{categories}:{}),...(playUrl?{playUrl}:{}),...(playerType!==undefined?{playerType}:{})};}
function normalizeLive(value:unknown,index:number,baseUrl?:string):LiveSourceConfig|null{
  if(typeof value==='string'){const endpoint=resource(value.trim(),baseUrl);return endpoint?{id:stableId('live',endpoint),name:`直播 ${index+1}`,endpoint,enabled:true}:null;}
  if(!value||typeof value!=='object')return null;
  const live=value as UnknownRecord;
  const endpoint=resource(text(live.url)||text(live.api),baseUrl);
  if(!endpoint)return null;
  const name=text(live.name)||`直播 ${index+1}`;
  const epg=resource(text(live.epg),baseUrl),logo=resource(text(live.logo),baseUrl);
  const headers={...(stringRecord(live.header)??{}),...(stringRecord(live.headers)??{})};
  const ua=text(live.ua)||text(live.userAgent),referer=text(live.referer)||text(live.referrer);
  if(ua)headers['User-Agent']=ua;
  if(referer)headers.Referer=referer;
  return{id:stableId('live',`${name}|${endpoint}`),name,endpoint,enabled:true,...(epg?{epg}:{}),...(logo?{logo}:{}),...(Object.keys(headers).length?{headers}:{})};
}
function uniqueSources(input:SourceConfig[]):{sources:SourceConfig[];duplicates:number}{const seen=new Map<string,number>();let duplicates=0;const sources=input.map(source=>{const count=(seen.get(source.id)??0)+1;seen.set(source.id,count);if(count===1)return source;duplicates+=1;return{...source,id:`${source.id}~${count}`};});return{sources,duplicates};}
export function parseTVBoxConfig(input:string,options:TVBoxParseOptions={}):TVBoxImportResult{assertConfigSize(input);const shell=unshell(input,0,options.configKey?{configKey:options.configKey}:{});let parsed:UnknownRecord;try{parsed=parseConfigObject(shell.text);}catch(error){if(shell.shell==='dollar-unknown')throw new Error('[SRC_CONFIG_DECRYPT_FAIL] 检测到影视仓加密配置，但当前已知 codec 无法解密');throw error;}const sites=Array.isArray(parsed.sites)?parsed.sites:[];const lives=Array.isArray(parsed.lives)?parsed.lives:[];const spider=resourceSpec(text(parsed.spider),options.baseUrl);const normalized=sites.map((site,index)=>normalizeSite(site,index,spider,options.baseUrl)).filter((item):item is SourceConfig=>item!==null).map(source=>({...source,configShell:shell.shell}));const{sources,duplicates}=uniqueSources(normalized);const liveSources=lives.map((live,index)=>normalizeLive(live,index,options.baseUrl)).filter((item):item is LiveSourceConfig=>item!==null);const warnings:string[]=[];if(shell.shell!=='plain')warnings.push(`配置已解壳：${shell.shell}`);if(sources.length===0)warnings.push('配置中未发现可导入的点播来源');if(liveSources.length===0&&lives.length>0)warnings.push('直播条目存在但没有可识别 URL');const executableCount=sources.filter(source=>source.trust==='B').length;if(executableCount>0)warnings.push(`${executableCount} 个可执行来源已按 Level B 导入并保持停用，请确认信任后手动启用`);const missingJar=sources.filter(source=>source.kind==='T3_JAR'&&!source.jar).length;if(missingJar>0)warnings.push(`${missingJar} 个 Java Spider 来源未提供顶层 spider 或独立 jar`);if(duplicates>0)warnings.push(`${duplicates} 个重复来源 key 已自动保留并添加序号后缀`);return{sources,liveSources,warnings};}
