import type { CategoryResult,DetailResult,HomeResult,PlayResult,SearchResult,SourceAdapter,SourceAuditResult,SourceConfig,SourceContext,SourceSummary } from '@free-new-desk/contracts';
import { AlistAdapter,CmsJsonAdapter,CmsXmlAdapter,DeclarativeRuleAdapter,Type4Adapter } from '@free-new-desk/source-adapters';
import { JavaSpiderAdapter } from './java-spider-adapter.js';
import { PluginAdapter } from './plugin-adapter.js';
import { SpiderAdapter } from './spider-adapter.js';
import { DoubanAdapter } from './douban-adapter.js';
interface LoadedSource{config:SourceConfig;adapter:SourceAdapter;lastUsed:number;executable:boolean;degraded:boolean;}
const MAX_EXECUTABLE=4,IDLE_MS=120_000;
function executable(config:SourceConfig):boolean{return config.kind==='T3_JS'||config.kind==='T3_JAR'||config.kind==='PLUGIN'||config.kind==='T4_CATVOD';}
function isDoubanSource(config:SourceConfig):boolean{return /豆瓣|douban/i.test(`${config.id} ${config.name}`);}
export class SourceEngine{
  readonly #configs=new Map<string,SourceConfig>();readonly #loaded=new Map<string,LoadedSource>();readonly #failures=new Map<string,string>();readonly #notices=new Map<string,string>();readonly #auditPending=new Map<string,Promise<SourceAuditResult>>();#proxyBaseUrl='';#proxyToken='';
  configureRuntime(config:{proxyBaseUrl?:string;proxyToken?:string}):void{this.#proxyBaseUrl=config.proxyBaseUrl??'';this.#proxyToken=config.proxyToken??'';}
  async replaceSources(sources:SourceConfig[]):Promise<void>{for(const loaded of this.#loaded.values())await loaded.adapter.destroy();this.#configs.clear();this.#loaded.clear();this.#failures.clear();this.#notices.clear();for(const config of sources)if(config.enabled)this.#configs.set(config.id,config);}
  #createAdapter(config:SourceConfig):SourceAdapter|undefined{switch(config.kind){case'T1_JSON':return new CmsJsonAdapter(config.endpoint);case'T0_XML':return new CmsXmlAdapter(config.endpoint);case'T4_EXT':return new Type4Adapter(config.endpoint,config.ext);case'T3_XYQ':case'T3_XBPQ':return new DeclarativeRuleAdapter(config.endpoint,config.ext);case'DRIVE_ALIST':return new AlistAdapter(config.endpoint);case'T3_JS':return new SpiderAdapter(config);case'T3_JAR':return new JavaSpiderAdapter(config);case'PLUGIN':return new PluginAdapter(config);case'T4_CATVOD':return/\.js(?:\?|$)/i.test(config.ext??config.endpoint)?new SpiderAdapter(config):new Type4Adapter(config.endpoint,config.ext);default:return undefined;}}
  async #getAdapter(sourceId:string):Promise<SourceAdapter>{await this.pruneIdle();const existing=this.#loaded.get(sourceId);if(existing){existing.lastUsed=Date.now();return existing.adapter;}const config=this.#configs.get(sourceId);if(!config)throw new Error(this.#failures.get(sourceId)??'Source is disabled or missing');const isExecutable=executable(config);if(isExecutable){const active=[...this.#loaded.values()].filter(item=>item.executable).sort((a,b)=>a.lastUsed-b.lastUsed);while(active.length>=MAX_EXECUTABLE){const victim=active.shift();if(!victim)break;await victim.adapter.destroy();this.#loaded.delete(victim.config.id);}}const adapter=this.#createAdapter(config);if(!adapter)throw new Error(`Unsupported source kind: ${config.kind}`);const context:SourceContext={sourceId:config.id,...(this.#proxyBaseUrl?{proxyBaseUrl:this.#proxyBaseUrl}:{}),...(this.#proxyToken?{proxyToken:this.#proxyToken}:{}),...(config.headers?{requestHeaders:config.headers}:{})};try{await adapter.init(context);this.#loaded.set(config.id,{config,adapter,lastUsed:Date.now(),executable:isExecutable,degraded:false});this.#failures.delete(config.id);this.#notices.delete(config.id);return adapter;}catch(error){const message=error instanceof Error?error.message:String(error);if(config.kind==='T3_JAR'&&/ClassNotFoundException/i.test(message)&&isDoubanSource(config)){const fallback=new DoubanAdapter(config);await fallback.init(context);this.#loaded.set(config.id,{config,adapter:fallback,lastUsed:Date.now(),executable:isExecutable,degraded:true});this.#failures.delete(config.id);this.#notices.set(config.id,`配置引用的 Spider 类不在 JAR 中，已自动回退到内置豆瓣源（浏览/搜索/详情/官方预告片播放）。原始错误：${message}`);return fallback;}this.#failures.set(config.id,message);throw error;}}
  listSources():SourceSummary[]{return[...this.#configs.values()].map(config=>({id:config.id,name:config.name,kind:config.kind,enabled:config.enabled,trust:config.trust,...(config.searchable!==undefined?{searchable:config.searchable}:{})})).sort((a,b)=>a.name.localeCompare(b.name));}
  getFailure(sourceId:string):string|undefined{return this.#failures.get(sourceId);}
  getNotice(sourceId:string):string|undefined{return this.#notices.get(sourceId);}
  async getHome(sourceId:string):Promise<HomeResult>{const result=await(await this.#getAdapter(sourceId)).getHome();const allow=this.#configs.get(sourceId)?.categories;if(!allow?.length||!result.categories?.length)return result;const names=new Set(allow);const categories=result.categories.filter(item=>names.has(item.name));const ids=new Set(categories.map(item=>item.id));const filters=result.filters?Object.fromEntries(Object.entries(result.filters).filter(([id])=>ids.has(id))):undefined;return{...result,categories,...(filters&&Object.keys(filters).length?{filters}:result.filters?{filters:{}}:{})};}
  async getCategory(sourceId:string,categoryId:string,page=1,filters:Record<string,string>={}):Promise<CategoryResult>{return(await this.#getAdapter(sourceId)).getCategory(categoryId,page,filters);}
  async search(sourceId:string,keyword:string,page=1):Promise<SearchResult>{return(await this.#getAdapter(sourceId)).search(keyword,page);}
  async getDetail(sourceId:string,ids:string[]):Promise<DetailResult>{return(await this.#getAdapter(sourceId)).getDetail(ids);}
  async getPlay(sourceId:string,flag:string,episodeId:string):Promise<PlayResult>{return(await this.#getAdapter(sourceId)).getPlay(flag,episodeId);}
  async audit(sourceId:string):Promise<SourceAuditResult>{const existing=this.#auditPending.get(sourceId);if(existing)return existing;const work=this.#runAudit(sourceId).finally(()=>{if(this.#auditPending.get(sourceId)===work)this.#auditPending.delete(sourceId);});this.#auditPending.set(sourceId,work);return work;}
  async #runAudit(sourceId:string):Promise<SourceAuditResult>{const stages:SourceAuditResult['stages']=[];const run=async(stage:string,action:()=>Promise<unknown>)=>{const started=performance.now();try{const result=await action();stages.push({stage,ok:true,durationMs:Math.round(performance.now()-started)});return result;}catch(error){stages.push({stage,ok:false,durationMs:Math.round(performance.now()-started),message:error instanceof Error?error.message:String(error)});return undefined;}};const missing=(stage:string,message:string)=>stages.push({stage,ok:false,durationMs:0,message});const home=await run('home',()=>this.getHome(sourceId)) as HomeResult|undefined;const category=home?.categories?.[0];if(category)await run('category',()=>this.getCategory(sourceId,category.id,1));else missing('category','来源未返回可审计分类');const first=home?.items[0];await run('search',()=>this.search(sourceId,first?.name??'test',1));let detail:DetailResult|undefined;if(first)detail=await run('detail',()=>this.getDetail(sourceId,[first.id])) as DetailResult|undefined;else missing('detail','来源未返回可审计条目');const episode=detail?.episodes[0];if(episode)await run('play',()=>this.getPlay(sourceId,episode.flag,episode.id));else missing('play','详情未返回可审计播放线路');const result:SourceAuditResult={sourceId,ok:stages.length===5&&stages.every(stage=>stage.ok),stages,checkedAt:new Date().toISOString()};const notice=this.#notices.get(sourceId);if(notice)result.notice=notice;return result;}
  async pruneIdle():Promise<void>{const cutoff=Date.now()-IDLE_MS;for(const[id,loaded]of[...this.#loaded])if(loaded.executable&&loaded.lastUsed<cutoff){await loaded.adapter.destroy();this.#loaded.delete(id);}}
  async destroy():Promise<void>{for(const loaded of this.#loaded.values())await loaded.adapter.destroy();this.#configs.clear();this.#loaded.clear();this.#failures.clear();this.#notices.clear();this.#auditPending.clear();}
}
