import { inflateRawSync } from 'node:zlib';
export type JarCompatKind='JVM'|'DEX'|'HYBRID'|'NATIVE'|'ANDROID_REQUIRED'|'INVALID';
export interface JarInspection{kind:JarCompatKind;classEntries:number;dexEntries:number;abis:string[];androidRefs:string[];catvodRefs:string[];highRisk:string[];hasManifest:boolean;magic:string;declaredClassFound:boolean;entries:number;}
interface ZipEntry{name:string;method:number;compressedSize:number;size:number;localOffset:number;}
const MAX_ZIP_ENTRIES=20_000,MAX_ENTRY_BYTES=32*1024*1024,MAX_SCAN_BYTES=64*1024*1024;
function zipEntries(bytes:Buffer):ZipEntry[]{const entries:ZipEntry[]=[];for(let i=0;i+46<=bytes.length;i++){if(bytes.readUInt32LE(i)!==0x02014b50)continue;const method=bytes.readUInt16LE(i+10),compressedSize=bytes.readUInt32LE(i+20),size=bytes.readUInt32LE(i+24),nameLength=bytes.readUInt16LE(i+28),extraLength=bytes.readUInt16LE(i+30),commentLength=bytes.readUInt16LE(i+32),localOffset=bytes.readUInt32LE(i+42);const name=bytes.subarray(i+46,i+46+nameLength).toString('utf8');entries.push({name,method,compressedSize,size,localOffset});if(entries.length>=MAX_ZIP_ENTRIES)break;i+=45+nameLength+extraLength+commentLength;}return entries;}
function entryBytes(bytes:Buffer,entry:ZipEntry):Buffer{if(entry.size>MAX_ENTRY_BYTES||entry.compressedSize>MAX_ENTRY_BYTES)return Buffer.alloc(0);const i=entry.localOffset;if(i+30>bytes.length||bytes.readUInt32LE(i)!==0x04034b50)return Buffer.alloc(0);const nameLength=bytes.readUInt16LE(i+26),extraLength=bytes.readUInt16LE(i+28),start=i+30+nameLength+extraLength,end=start+entry.compressedSize;if(start<0||end>bytes.length)return Buffer.alloc(0);const raw=bytes.subarray(start,end);if(entry.method===0)return raw;if(entry.method===8)try{return inflateRawSync(raw,{maxOutputLength:MAX_ENTRY_BYTES});}catch{return Buffer.alloc(0);}return Buffer.alloc(0);}
function uniqueMatches(text:string,patterns:RegExp[]):string[]{const values=new Set<string>();for(const pattern of patterns){pattern.lastIndex=0;for(const match of text.matchAll(pattern))if(match[0])values.add(match[0].replaceAll('/','.'));}return[...values].sort();}
function elfAbi(value:Buffer):string{if(value.length<20||value[0]!==0x7f||value[1]!==0x45||value[2]!==0x4c||value[3]!==0x46)return'unknown';const machine=value.readUInt16LE(18);return({3:'x86',40:'arm',62:'x86_64',183:'arm64'} as Record<number,string>)[machine]??`machine-${machine}`;}
const riskRules:ReadonlyArray<readonly[string,RegExp]>=[['WebView',/android[\/.]webkit[\/.]WebView/],['DexClassLoader',/dalvik[\/.]system[\/.](?:DexClassLoader|PathClassLoader)/],['System.loadLibrary',/(?:loadLibrary|System[\/.]loadLibrary)/],['Runtime.exec',/(?:Runtime[\/.]exec|ProcessBuilder)/]];
export function inspectJar(input:Uint8Array,expectClass?:string):JarInspection{const bytes=Buffer.from(input);const magic=bytes.subarray(0,8).toString('hex');if(bytes.length<4||bytes.readUInt32LE(0)!==0x04034b50)return{kind:'INVALID',classEntries:0,dexEntries:0,abis:[],androidRefs:[],catvodRefs:[],highRisk:[],hasManifest:false,magic,declaredClassFound:false,entries:0};const entries=zipEntries(bytes);const classEntries=entries.filter(item=>/\.class$/i.test(item.name)).length,dex=entries.filter(item=>/(?:^|\/)classes\d*\.dex$/i.test(item.name)),native=entries.filter(item=>/^lib\/.+\.so$/i.test(item.name));const inspectable=entries.filter(item=>/\.(?:class|dex)$/i.test(item.name));let scan='',scanBytes=0,scanComplete=true;for(const entry of inspectable){if(scanBytes>=MAX_SCAN_BYTES){scanComplete=false;break;}const body=entryBytes(bytes,entry);if(entry.size>0&&body.length===0){scanComplete=false;break;}if(body.length){const remaining=Math.max(0,MAX_SCAN_BYTES-scanBytes);if(body.length>remaining){scanComplete=false;break;}scan+='\n'+body.toString('latin1');scanBytes+=body.length;}}const androidRefs=uniqueMatches(scan,[/android[\/.][A-Za-z0-9_$/.-]+/g,/dalvik[\/.]system[\/.][A-Za-z0-9_$/.-]+/g]);const catvodRefs=uniqueMatches(scan,[/com[\/.]github[\/.]catvod[\/.][A-Za-z0-9_$/.-]+/g]);const highRisk:string[]=[];for(const [name,pattern] of riskRules)if(pattern.test(scan))highRisk.push(name);const abis=[...new Set(native.map(item=>elfAbi(entryBytes(bytes,item))))];const expected=(expectClass??'').replaceAll('.','/');const declaredClassFound=scanComplete&&(!expected||entries.some(item=>item.name===expected+'.class')||scan.includes('L'+expected+';')||scan.includes(expected));const hasManifest=entries.some(item=>/(?:^|\/)AndroidManifest\.xml$/i.test(item.name));let kind:JarCompatKind;if(!scanComplete)kind='INVALID';else if(native.length||highRisk.includes('System.loadLibrary'))kind='NATIVE';else if(highRisk.includes('WebView')||highRisk.includes('DexClassLoader'))kind='ANDROID_REQUIRED';else if(classEntries&&dex.length)kind='HYBRID';else if(dex.length)kind='DEX';else if(classEntries)kind='JVM';else kind='INVALID';return{kind,classEntries,dexEntries:dex.length,abis,androidRefs,catvodRefs,highRisk,hasManifest,magic,declaredClassFound,entries:entries.length};}
