import { spawn,type ChildProcessWithoutNullStreams } from 'node:child_process';
import { createHash,randomUUID } from 'node:crypto';
import { mkdir,readFile,stat,writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { CategoryResult,DetailResult,HomeResult,PlayResult,SearchResult,SourceAdapter,SourceConfig,SourceContext } from '@free-new-desk/contracts';
import { RequestBroker } from '@free-new-desk/source-sdk';
import { normalizeSpiderCategory,normalizeSpiderDetail,normalizeSpiderHome,normalizeSpiderPlay,normalizeSpiderSearch } from './result-normalizer.js';
import { inspectJar } from './jar-inspector.js';
import { probeJavaRuntime } from './java-runtime.js';

type Pending={resolve:(value:string)=>void;reject:(error:Error)=>void;timer:NodeJS.Timeout};
export interface JarSpec{location:string;md5?:string;}
const enc=(value:string)=>Buffer.from(value,'utf8').toString('base64url');
const dec=(value:string)=>Buffer.from(value,'base64url').toString('utf8');
const MAX_JAR_BYTES=64*1024*1024;
function assertJarSize(size:number):void{if(!Number.isFinite(size)||size<1||size>MAX_JAR_BYTES)throw new Error('[SRC_JAR_INVALID] Spider JAR size is outside the 1 B–64 MB safety limit');}
async function readResponseWithLimit(response:Response):Promise<Buffer>{const declared=Number(response.headers.get('content-length'));if(Number.isFinite(declared)&&declared>0)assertJarSize(declared);if(!response.body){const bytes=Buffer.from(await response.arrayBuffer());assertJarSize(bytes.length);return bytes;}const reader=response.body.getReader(),chunks:Buffer[]=[];let total=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value?.byteLength)continue;total+=value.byteLength;if(total>MAX_JAR_BYTES){void reader.cancel('Spider JAR exceeds 64 MB safety limit').catch(()=>{});throw new Error('[SRC_JAR_INVALID] Spider JAR download exceeded the 64 MB safety limit');}chunks.push(Buffer.from(value));}}finally{reader.releaseLock();}assertJarSize(total);return Buffer.concat(chunks,total);}
function javaEnv():NodeJS.ProcessEnv{const output:NodeJS.ProcessEnv={};for(const key of ['PATH','Path','SystemRoot','WINDIR','TEMP','TMP','JAVA_HOME','JRE_HOME','HOME','USERPROFILE','LOCALAPPDATA']){const value=process.env[key];if(value)output[key]=value;}return output;}
function sourceWorkDir(sourceId:string):string{const label=(sourceId.replace(/[^a-z0-9_.-]/gi,'_').replace(/^_+|_+$/g,'').slice(0,48)||'source');const digest=createHash('sha256').update(sourceId).digest('hex').slice(0,12);return path.join(os.tmpdir(),'free-new-desk','spider-data',`${label}-${digest}`);}
export function parseJarSpec(value:string):JarSpec{const parts=value.split(';').map(item=>item.trim());const location=parts[0]??'';if(!location)throw new Error('Java Spider source is missing jar');let md5:string|undefined;for(let index=1;index<parts.length-1;index+=1)if(parts[index]?.toLowerCase()==='md5'&&/^[a-f0-9]{32}$/i.test(parts[index+1]??'')){md5=(parts[index+1]??'').toLowerCase();break;}return{location,...(md5?{md5}:{})};}
function verifyMd5(bytes:Buffer,expected:string|undefined):void{if(!expected)return;const actual=createHash('md5').update(bytes).digest('hex');if(actual.toLowerCase()!==expected.toLowerCase())throw new Error(`Spider JAR MD5 mismatch: expected ${expected}, got ${actual}`);}
export function resolveCspClassName(api:string):string{const value=api.trim().replace(/^csp_/i,'');if(!value)throw new Error('Java Spider class name is empty');return value.includes('.')?value:`com.github.catvod.spider.${value}`;}
export class JavaSpiderAdapter implements SourceAdapter {
  readonly #broker=new RequestBroker();readonly #pending=new Map<string,Pending>();readonly #config:SourceConfig;#child:ChildProcessWithoutNullStreams|undefined;#buffer='';#context:SourceContext|undefined;#jarPath='';
  constructor(config:SourceConfig){this.#config=config;}
  async init(ctx:SourceContext):Promise<void>{this.#context=ctx;this.#broker.setDefaultHeaders(ctx.sourceId,ctx.requestHeaders);this.#jarPath=await this.#materializeJar();const inspection=inspectJar(await readFile(this.#jarPath),this.#className());if(!inspection.declaredClassFound)throw new Error('[SRC_JAR_CLASS_MISSING] 配置引用的 Spider 类不在包中');if(inspection.kind==='NATIVE'||inspection.kind==='ANDROID_REQUIRED')throw new Error(`[SRC_JAR_NEEDS_ANDROID] 该 Spider 需要 Android 原生/WebView/动态 DEX 能力：${inspection.highRisk.join(', ')||inspection.abis.join(', ')}`);if(inspection.kind==='DEX')throw new Error('[SRC_JAR_DEX_UNSUPPORTED] 已识别 classes.dex；真实 Census 未达到 S2 立项门槛，当前保持受限');if(inspection.kind==='INVALID')throw new Error('[SRC_JAR_INVALID] 文件不是可执行 JVM/DEX Spider 包');const host=this.#hostJar();const runtime=await probeJavaRuntime();const workDir=sourceWorkDir(this.#config.id);await mkdir(workDir,{recursive:true});const child=spawn(runtime.command,['-Xms16m','-Xmx128m','-Djava.awt.headless=true','-jar',host],{windowsHide:true,stdio:['pipe','pipe','pipe'],cwd:workDir,env:javaEnv()});child.stdout.setEncoding('utf8');child.stdout.on('data',chunk=>this.#consume(chunk));child.stderr.setEncoding('utf8');child.stderr.on('data',()=>{/* intentionally not forwarded with source URLs */});child.once('exit',()=>{for(const pending of this.#pending.values()){clearTimeout(pending.timer);pending.reject(new Error('JVM SpiderHost exited'));}this.#pending.clear();this.#child=undefined;});this.#child=child;await this.#request('PING',[]);const className=this.#className();await this.#request('INIT',[ctx.sourceId,this.#jarPath,className,this.#config.ext??'']);}
  #className():string{const api=this.#config.endpoint.trim();if(/^csp_/i.test(api))return resolveCspClassName(api);const ext=this.#config.ext??'';try{const parsed=JSON.parse(ext) as{class?:unknown};if(typeof parsed.class==='string'&&parsed.class.trim())return resolveCspClassName(parsed.class.trim());}catch{/* ext may be a plain string */}if(ext.startsWith('class:'))return resolveCspClassName(ext.slice(6).trim());throw new Error('Java Spider requires endpoint csp_ClassName or ext {"class":"..."}');}
  #hostJar():string{const resources=(process as typeof process&{resourcesPath?:string}).resourcesPath;if(resources)return path.join(resources,'jvm','jvm-spider-host.jar');return fileURLToPath(new URL('../../jvm-spider-host/dist/jvm-spider-host.jar',import.meta.url));}
  async #materializeJar():Promise<string>{const spec=parseJarSpec((this.#config.jar??'').trim());if(!/^https?:\/\//i.test(spec.location)){const target=path.resolve(spec.location);assertJarSize((await stat(target)).size);if(spec.md5)verifyMd5(await readFile(target),spec.md5);return target;}const response=await this.#broker.request({sourceId:this.#config.id,url:spec.location,timeoutMs:20_000});if(!response.ok)throw new Error(`Spider JAR HTTP ${response.status}`);const bytes=await readResponseWithLimit(response);verifyMd5(bytes,spec.md5);const hash=createHash('sha256').update(bytes).digest('hex');const dir=path.join(os.tmpdir(),'free-new-desk','jars');await mkdir(dir,{recursive:true});const target=path.join(dir,`${hash}.jar`);await writeFile(target,bytes);return target;}
  #consume(chunk:string):void{this.#buffer+=chunk;for(;;){const newline=this.#buffer.indexOf('\n');if(newline<0)break;const line=this.#buffer.slice(0,newline).replace(/\r$/,'');this.#buffer=this.#buffer.slice(newline+1);const parts=line.split('\t');if(parts.length<3)continue;const[status,id,payload]=parts;const pending=this.#pending.get(id??'');if(!pending)continue;clearTimeout(pending.timer);this.#pending.delete(id??'');if(status==='OK')pending.resolve(dec(payload??''));else pending.reject(new Error(dec(payload??'')));}}
  #request(command:string,args:string[]):Promise<string>{if(!this.#child)throw new Error('JVM SpiderHost is not running');const id=randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.#pending.delete(id);reject(new Error(`JVM SpiderHost timeout: ${command}`));this.#child?.kill();},15_000);this.#pending.set(id,{resolve,reject,timer});this.#child?.stdin.write([command,id,...args.map(enc)].join('\t')+'\n');});}
  async #callRaw(method:string,args:string[]):Promise<string>{return this.#request('CALL',[this.#config.id,method,String(args.length),...args]);}
  async #callFallback<T>(attempts:Array<[string,string[]]>,transform:(value:string)=>T):Promise<T>{let last:unknown;for(const[method,args]of attempts){try{return transform(await this.#callRaw(method,args));}catch(error){last=error;}}throw last instanceof Error?last:new Error('Java Spider method failed');}
  async getHome():Promise<HomeResult>{let home=await this.#callFallback<HomeResult>([['homeContent',['true']],['home',[]]],normalizeSpiderHome);if(home.items.length===0){try{const video=await this.#callFallback<HomeResult>([['homeVideoContent',[]]],normalizeSpiderHome);home={...home,items:video.items};}catch{/* recommendations are optional */}}return home;}
  getCategory(categoryId:string,page:number,filters:Record<string,string>={}):Promise<CategoryResult>{return this.#callFallback<CategoryResult>([['categoryContent',[categoryId,String(page),'true',JSON.stringify(filters)]],['category',[categoryId,String(page),JSON.stringify(filters)]]],value=>normalizeSpiderCategory(value,page));}
  getDetail(ids:string[]):Promise<DetailResult>{return this.#callFallback<DetailResult>([['detailContent',[ids.join('\u001f')]],['detail',[JSON.stringify(ids)]]],normalizeSpiderDetail);}
  search(keyword:string,page=1):Promise<SearchResult>{return this.#callFallback<SearchResult>([['searchContent',[keyword,'false',String(page)]],['searchContent',[keyword,'false']],['search',[keyword,String(page)]]],value=>normalizeSpiderSearch(value,page));}
  getPlay(flag:string,id:string):Promise<PlayResult>{return this.#callFallback<PlayResult>([['playerContent',[flag,id,'']],['play',[flag,id]]],normalizeSpiderPlay);}
  async destroy():Promise<void>{if(this.#child){try{await this.#request('DESTROY',[this.#config.id]);}catch{/* host may already be gone */}this.#child.kill();}this.#child=undefined;if(this.#context){this.#broker.clearCookies(this.#context.sourceId);this.#broker.clearDefaultHeaders(this.#context.sourceId);}this.#context=undefined;}
}
