import { app,BrowserWindow,ipcMain,screen,type IpcMainInvokeEvent } from 'electron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getCurrentPlayerClient,getPlayerRuntimeSession } from './player-client.js';

type OverlayAction='exit'|'pause-toggle'|'seek'|'volume'|'next'|'live-prev'|'live-next';
type OverlayState={requestId:string;domain:'vod'|'live'|null;paused:boolean;position:number;duration:number;volume:number;channelId?:string;routeIndex?:number;routeCount?:number};
const __dirname=path.dirname(fileURLToPath(import.meta.url));
let overlay:BrowserWindow|undefined;let pollTimer:NodeJS.Timeout|undefined;let registered=false;let lastVisible=false;let lastState='';
function requireLocalSender(event:IpcMainInvokeEvent):void{const sender=event.senderFrame?.url??'';if(sender.startsWith('file://')||sender.startsWith('data:text/html'))return;throw new Error('Untrusted overlay IPC sender');}
function appWindows():BrowserWindow[]{return BrowserWindow.getAllWindows().filter(window=>!window.isDestroyed()&&window!==overlay);}
function activeAppWindow():BrowserWindow|undefined{return appWindows().find(window=>window.isFocused())??appWindows().find(window=>window.isVisible())??appWindows()[0];}
function html():string{return`<!doctype html><html><head><meta charset="utf-8"><style>
:root{color-scheme:dark;font-family:"Segoe UI Variable Text","Segoe UI",sans-serif}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;background:transparent;overflow:hidden}.root{position:absolute;inset:0;display:flex;align-items:flex-end;justify-content:center;padding:0 3vw 4vh;pointer-events:none}.controls{pointer-events:auto;width:min(980px,92vw);padding:14px 18px 16px;border:1px solid rgba(255,255,255,.18);border-radius:14px;background:rgba(15,18,24,.82);backdrop-filter:blur(24px);box-shadow:0 12px 42px rgba(0,0,0,.38);transition:opacity .18s,transform .18s}.controls.hidden{opacity:0;transform:translateY(18px);pointer-events:none}.row{display:flex;align-items:center;gap:12px}.title{font-size:13px;font-weight:600;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.meta{font-size:11px;color:#c3c9d4}.time{font-variant-numeric:tabular-nums;font-size:11px;color:#d9dee8;min-width:110px;text-align:center}button{height:36px;min-width:42px;border:1px solid rgba(255,255,255,.15);border-radius:9px;background:rgba(255,255,255,.09);color:white;padding:0 12px;font:inherit}button:hover{background:rgba(255,255,255,.16)}input[type=range]{accent-color:#4f8cff}.progress{width:100%;margin:10px 0}.volume{width:120px}.live-only,.vod-only{display:none}.is-live .live-only,.is-vod .vod-only{display:inline-flex}
</style></head><body><div class="root"><div id="controls" class="controls"><div class="row"><strong id="title" class="title">Free New Desk</strong><span id="meta" class="meta"></span><span id="time" class="time">00:00 / 00:00</span></div><input id="progress" class="progress" type="range" min="0" max="1" step="0.1"><div class="row"><button id="pause">Ⅱ</button><button id="prev" class="live-only">上一台</button><button id="nextLive" class="live-only">下一台</button><button id="nextVod" class="vod-only">下一集</button><span style="flex:1"></span><span class="meta">音量</span><input id="volume" class="volume" type="range" min="0" max="100"><button id="exit">退出全屏</button></div></div></div></body></html>`;}
function createOverlay():BrowserWindow{const window=new BrowserWindow({show:false,frame:false,transparent:true,backgroundColor:'#00000000',resizable:false,movable:false,minimizable:false,maximizable:false,closable:false,focusable:true,skipTaskbar:true,alwaysOnTop:true,hasShadow:false,webPreferences:{preload:path.join(__dirname,'..','preload','fullscreen-overlay.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}});window.setAlwaysOnTop(true,'screen-saver',1);window.setVisibleOnAllWorkspaces(true,{visibleOnFullScreen:true});window.webContents.setWindowOpenHandler(()=>({action:'deny'}));void window.loadURL('data:text/html;charset=utf-8,'+encodeURIComponent(html()));window.on('closed',()=>{if(overlay===window)overlay=undefined;});return window;}
function sendState(state:OverlayState):void{if(!overlay||overlay.isDestroyed())return;const serialized=JSON.stringify(state);if(serialized===lastState)return;lastState=serialized;overlay.webContents.send('fullscreen-overlay:state',state);}
function fitOverlay(target:BrowserWindow):void{if(!overlay||overlay.isDestroyed())return;const bounds=target.getBounds(),display=screen.getDisplayMatching(bounds);const next=display.bounds,current=overlay.getBounds();if(current.x!==next.x||current.y!==next.y||current.width!==next.width||current.height!==next.height)overlay.setBounds(next,false);}
async function poll():Promise<void>{const player=getCurrentPlayerClient();if(!player)return;try{const stats=await player.query('stats'),session=getPlayerRuntimeSession();const visible=Boolean(stats.fullscreen&&session.domain&&session.domain!=='music'&&session.requestId);if(!visible){if(lastVisible&&overlay&&!overlay.isDestroyed())overlay.hide();lastVisible=false;lastState='';return;}const target=activeAppWindow();if(!target)return;overlay??=createOverlay();fitOverlay(target);if(!lastVisible){overlay.showInactive();lastVisible=true;}sendState({requestId:session.requestId,domain:session.domain==='vod'||session.domain==='live'?session.domain:null,paused:stats.paused,position:Math.max(0,stats.position),duration:Math.max(0,stats.duration),volume:Math.max(0,Math.min(100,stats.volume)),...(session.channelId?{channelId:session.channelId}:{}),...(session.routeIndex!==undefined?{routeIndex:session.routeIndex}:{}),...(session.routeCount!==undefined?{routeCount:session.routeCount}:{})});}catch{/* PlayerHost may be warming */}}
function dispatchRendererAction(action:'next'|'live-prev'|'live-next',requestId:string):void{const target=activeAppWindow();if(target&&!target.isDestroyed())target.webContents.send('fullscreen-overlay:renderer-action',{action,requestId});}
export function registerFullscreenOverlayIpc():void{if(registered)return;registered=true;ipcMain.handle('fullscreen-overlay:action',async(event,input)=>{requireLocalSender(event);const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>,action=String(value.action??'') as OverlayAction,requestId=String(value.requestId??''),session=getPlayerRuntimeSession();if(!requestId||session.requestId!==requestId||!session.domain)return false;const player=getCurrentPlayerClient();if(!player)return false;if(action==='exit'){const result=await player.command({command:'fullscreen',value:false});if(result.ok)overlay?.hide();return result.ok;}if(action==='pause-toggle'){const stats=await player.query('stats');return(await player.command({command:'pause',value:!stats.paused})).ok;}if(action==='seek'){const next=Number(value.value);if(!Number.isFinite(next))return false;return(await player.command({command:'seek',value:next,absolute:true})).ok;}if(action==='volume'){const next=Number(value.value);if(!Number.isFinite(next))return false;return(await player.command({command:'volume',value:Math.max(0,Math.min(100,next))})).ok;}if(action==='next'&&session.domain!=='vod')return false;if((action==='live-prev'||action==='live-next')&&session.domain!=='live')return false;if(action==='next'||action==='live-prev'||action==='live-next'){dispatchRendererAction(action,requestId);return true;}return false;});}
registerFullscreenOverlayIpc();
app.whenReady().then(()=>{overlay??=createOverlay();pollTimer=setInterval(()=>{void poll();},300);pollTimer.unref();void poll();});
app.once('before-quit',()=>{if(pollTimer)clearInterval(pollTimer);pollTimer=undefined;overlay?.destroy();overlay=undefined;});
