import { app,BrowserWindow,clipboard,dialog,ipcMain,Menu,nativeImage,nativeTheme,Notification,powerMonitor,protocol,screen,shell,Tray,type IpcMainInvokeEvent } from 'electron';
import { mkdirSync } from 'node:fs';
import { mkdir,readFile,rm,writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath,pathToFileURL } from 'node:url';
import { LiveSourceConfigSchema,PlaybackEpisodeRequestSchema,PlayerCommandSchema,SourceCategoryRequestSchema,SourceConfigSchema,SourceDetailRequestSchema,SourceIdRequestSchema,SourceSearchRequestSchema } from '@free-new-desk/contracts';
import type { CategoryResult,CompatibilityStage,DetailResult,HomeResult,ImportGroupRemovalResult,LiveChannel,LiveFavorite,LiveGroup,LiveRouteSpeed,LiveSourceConfig,PlayResult,PlayerQuery,ProgramReservation,SearchResult,SourceCompatibilityResult,SourceConfig,SourceHealth,TVBoxImportResult,VideoCard } from '@free-new-desk/contracts';
import { DataService } from '@free-new-desk/data-service';
import { parseTVBoxConfig } from '@free-new-desk/tvbox-config';
import { parseLivePlaylist } from '@free-new-desk/live-parser';
import { resolveEpgTemplate } from '@free-new-desk/epg-parser';
import { ProxyService } from '@free-new-desk/proxy-service';
import { RequestBroker,redactSecrets } from '@free-new-desk/source-sdk';
import { SourceEngineClient } from './source-engine-client.js';
import { PlayerClient } from './player-client.js';
import { JsonLogger } from './logger.js';
import { SniffingService } from './sniffing-service.js';
import { PlaybackResolver,shouldRetryPlayerFailure,type PlaybackResolution } from './playback-resolver.js';
import { collectJarRuntimeDiagnostic,probeJavaDiagnostic } from './runtime-diagnostics.js';
import { EpgWorkerClient } from './epg-worker-client.js';
import { DiskCache } from './cache-service.js';
import { ImageService } from './image-service.js';
import { safeManagedPlaylistPath,safeCacheNamespacePath } from './path-safety.js';

protocol.registerSchemesAsPrivileged([{scheme:'fnd-image',privileges:{standard:true,secure:true,corsEnabled:false,supportFetchAPI:false}}]);
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const sourceEngine=new SourceEngineClient();
const player=new PlayerClient();
const proxy=new ProxyService();
const sniffing=new SniffingService();
const broker=new RequestBroker();
const playbackResolver=new PlaybackResolver(broker,sniffing);
const epgWorker=new EpgWorkerClient();
const browserUserAgent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36';
let data:DataService|undefined;
let logger:JsonLogger|undefined;
let cache:DiskCache|undefined;
let images:ImageService|undefined;
let aggregateController:AbortController|undefined;
let epgRefreshTimer:NodeJS.Timeout|undefined;
let updateCheckTimer:NodeJS.Timeout|undefined;
let sourceHealthTimer:NodeJS.Timeout|undefined;
let reservationTimer:NodeJS.Timeout|undefined;
let mainWindow:BrowserWindow|undefined;
let tray:Tray|undefined;
let lastPlaybackDiagnostic:Record<string,unknown>|undefined;
let lastPerformanceDiagnostic:Record<string,unknown>|undefined;
const performanceSamples=new Map<string,number[]>();
const performanceMetricNames=new Set(['navigationMs','playbackNavigationMs','surfaceHideMs','surfaceSyncMs','firstFrameMs','bufferingDurationMs','bufferingCount','playerLoadAcceptedMs']);
function recordPerformanceMetric(metric:string,value:number):void{if(!performanceMetricNames.has(metric)||!Number.isFinite(value)||value<0||value>120_000)return;const items=performanceSamples.get(metric)??[];items.push(Math.round(value*10)/10);if(items.length>200)items.splice(0,items.length-200);performanceSamples.set(metric,items);}
function p95(values:number[]):number{if(!values.length)return 0;const ordered=[...values].sort((a,b)=>a-b);return ordered[Math.min(ordered.length-1,Math.max(0,Math.ceil(ordered.length*.95)-1))]??0;}
function performanceSummary():Record<string,{count:number;latest:number;p95:number}>{const out:Record<string,{count:number;latest:number;p95:number}>={};for(const[metric,values]of performanceSamples)out[metric]={count:values.length,latest:values.at(-1)??0,p95:p95(values)};return out;}
function broadcastPlaybackStage(stage:string,message:string,error?:string):void{mainWindow?.webContents.send('playback:stageChanged',{stage,message,...(error?{error}:{}),at:Date.now()});}
async function measureFirstFrame(started:number):Promise<void>{for(let attempt=0;attempt<20;attempt++){await new Promise(resolve=>setTimeout(resolve,100));try{const stats=await player.query('stats');if((stats.width??0)>0&&(stats.height??0)>0){recordPerformanceMetric('firstFrameMs',performance.now()-started);return;}}catch{return;}}}
const playbackResolutionCache=new Map<string,{resolved:PlayResult;resolution:PlaybackResolution;expiresAt:number}>();
const liveRouteCache=new Map<string,{routeIndex:number;expiresAt:number}>();
const PLAYBACK_RESOLUTION_TTL_MS=2*60*1000;
const LIVE_ROUTE_TTL_MS=30*60*1000;
function playbackCacheKey(sourceId:string,flag:string,episodeId:string):string{return sourceId+'\u0000'+flag+'\u0000'+episodeId;}
function liveRouteKey(sourceId:string,channelId:string):string{return sourceId+'\u0000'+channelId;}
function prunePlaybackCaches():void{const now=Date.now();for(const[key,item]of playbackResolutionCache)if(item.expiresAt<=now)playbackResolutionCache.delete(key);for(const[key,item]of liveRouteCache)if(item.expiresAt<=now)liveRouteCache.delete(key);}
function rememberPlaybackResolution(key:string,resolved:PlayResult,resolution:PlaybackResolution):void{if(playbackResolutionCache.size>=256){const oldest=playbackResolutionCache.keys().next().value as string|undefined;if(oldest)playbackResolutionCache.delete(oldest);}playbackResolutionCache.set(key,{resolved,resolution,expiresAt:Date.now()+PLAYBACK_RESOLUTION_TTL_MS});}
function rememberLiveRoute(key:string,routeIndex:number):void{if(liveRouteCache.size>=512){const oldest=liveRouteCache.keys().next().value as string|undefined;if(oldest)liveRouteCache.delete(oldest);}liveRouteCache.set(key,{routeIndex,expiresAt:Date.now()+LIVE_ROUTE_TTL_MS});}
function clearLiveRouteCache(sourceId:string):void{const prefix=sourceId+'\u0000';for(const key of liveRouteCache.keys())if(key.startsWith(prefix))liveRouteCache.delete(key);}
let quitting=false;
const liveGroupsCache=new Map<string,LiveGroup[]>();

function requireLocalSender(event:IpcMainInvokeEvent):void{const sender=event.senderFrame?.url??'';if(!sender.startsWith('file://'))throw new Error('Untrusted IPC sender');}
async function createUiSmokeMedia():Promise<string>{const sampleRate=8000,seconds=3,samples=sampleRate*seconds,dataSize=samples*2,buffer=Buffer.alloc(44+dataSize);buffer.write('RIFF',0,'ascii');buffer.writeUInt32LE(36+dataSize,4);buffer.write('WAVE',8,'ascii');buffer.write('fmt ',12,'ascii');buffer.writeUInt32LE(16,16);buffer.writeUInt16LE(1,20);buffer.writeUInt16LE(1,22);buffer.writeUInt32LE(sampleRate,24);buffer.writeUInt32LE(sampleRate*2,28);buffer.writeUInt16LE(2,32);buffer.writeUInt16LE(16,34);buffer.write('data',36,'ascii');buffer.writeUInt32LE(dataSize,40);const file=path.join(app.getPath('temp'),'free-new-desk-ui-smoke.wav');await writeFile(file,buffer);return pathToFileURL(file).href;}
function allowedExternal(value:string):boolean{try{const url=new URL(value);return url.protocol==='https:'&&url.hostname==='github.com'&&url.pathname.startsWith('/cwe88108/free-new-desk-public');}catch{return false;}}
function restoreWindowBounds(store:DataService|undefined):{width:number;height:number} | {width:number;height:number;x:number;y:number}{const fallback={width:1440,height:900};if(!store)return fallback;try{const parsed=JSON.parse(store.getSetting('window.bounds')??'') as {x?:unknown;y?:unknown;width?:unknown;height?:unknown};const width=Number(parsed.width),height=Number(parsed.height);if(!Number.isFinite(width)||!Number.isFinite(height))return fallback;const size={width:Math.max(1280,Math.min(width,3840)),height:Math.max(720,Math.min(height,2160))};const x=Number(parsed.x),y=Number(parsed.y);if(!Number.isFinite(x)||!Number.isFinite(y))return size;const display=screen.getDisplayMatching({x:Math.round(x),y:Math.round(y),width:size.width,height:size.height});const area=display.workArea;if(x<area.x-8||y<area.y-8||x+size.width>area.x+area.width+8||y+size.height>area.y+area.height+8)return size;return{...size,x:Math.round(x),y:Math.round(y)};}catch{return fallback;}}
function persistMainWindowBounds():void{if(!data||!mainWindow||mainWindow.isDestroyed())return;try{const bounds=mainWindow.getNormalBounds();data.setSetting('window.bounds',JSON.stringify({...bounds,maximized:mainWindow.isMaximized()}));}catch{/* bounds persistence is best effort */}}
function createWindow():BrowserWindow{const bounds=restoreWindowBounds(data);const window=new BrowserWindow({...bounds,minWidth:1280,minHeight:720,show:false,title:'Free New Desk',backgroundColor:'#00000000',backgroundMaterial:process.platform==='win32'?'mica':'none',titleBarStyle:'hidden',titleBarOverlay:process.platform==='win32'?{color:'#00000000',symbolColor:nativeTheme.shouldUseDarkColors?'#ffffff':'#111111',height:48}:false,roundedCorners:true,webPreferences:{preload:path.join(__dirname,'..','preload','index.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}});window.webContents.setWindowOpenHandler(({url})=>{if(allowedExternal(url))void shell.openExternal(url);return{action:'deny'};});window.webContents.on('will-navigate',(event,url)=>{if(url!==window.webContents.getURL())event.preventDefault();});window.webContents.on('will-attach-webview',event=>event.preventDefault());window.webContents.on('render-process-gone',(_event,details)=>logger?.fatal('crash','renderer process gone',{reason:details.reason,exitCode:details.exitCode}));window.webContents.session.setPermissionRequestHandler((_wc,_permission,callback)=>callback(false));void window.loadFile(path.join(__dirname,'..','renderer','index.html'));window.once('ready-to-show',()=>window.show());window.on('close',event=>{persistMainWindowBounds();if(!quitting&&tray){event.preventDefault();window.hide();}});window.on('closed',()=>{if(mainWindow===window)mainWindow=undefined;});mainWindow=window;return window;}

async function syncSources():Promise<void>{playbackResolutionCache.clear();if(data)await sourceEngine.replaceAll(data.listSources());}
function imageUrl(value:string|undefined,sourceId:string):string|undefined{return value&&images?images.url(value,sourceId):value;}
function wrapCard(sourceId:string,item:VideoCard):VideoCard{return{...item,...(item.poster?{poster:imageUrl(item.poster,sourceId)}:{})};}
function wrapHome(sourceId:string,result:HomeResult):HomeResult{return{...result,items:result.items.map(item=>wrapCard(sourceId,item))};}
function wrapCategory(sourceId:string,result:CategoryResult):CategoryResult{return{...result,items:result.items.map(item=>wrapCard(sourceId,item))};}
function wrapSearch(sourceId:string,result:SearchResult):SearchResult{return{...result,items:result.items.map(item=>wrapCard(sourceId,item))};}
function wrapDetail(sourceId:string,result:DetailResult):DetailResult{return{...result,...(result.poster?{poster:imageUrl(result.poster,sourceId)}:{})};}
async function cachedJson<T>(namespace:string,key:string,force:boolean,ttlMs:number,load:()=>Promise<T>):Promise<T>{if(cache&&!force){const saved=await cache.get(namespace,key);if(saved)try{return JSON.parse(saved.data.toString('utf8')) as T;}catch{/* malformed cache is replaced below */}}const value=await load();if(cache)await cache.put(namespace,key,Buffer.from(JSON.stringify(value)),'application/json',ttlMs);return value;}
function filterCacheKey(filters:Record<string,string>):string{return JSON.stringify(Object.entries(filters).sort(([a],[b])=>a.localeCompare(b)));}

function networkTimeoutMs(store:DataService,fallbackMs:number):number{const raw=Number(store.getSetting('network.timeoutSeconds'));if(!Number.isFinite(raw)||raw<3||raw>120)return fallbackMs;return Math.round(raw*1000);}
async function fetchText(store:DataService,sourceId:string,url:string,headers?:Record<string,string>,signal?:AbortSignal):Promise<string>{if(!/^https?:\/\//i.test(url))throw new Error('Only HTTP(S) resources are supported');return broker.text({sourceId,url,...(headers?{headers}:{}),timeoutMs:networkTimeoutMs(store,15_000),retries:2,...(signal?{signal}:{})});}
interface ImportContext{importGroupId:string;sourceLabel:string;importedAt:string;}
async function importConfigInput(store:DataService,input:string,context:ImportContext):Promise<TVBoxImportResult>{
  const value=input.trim();if(!value)throw new Error('Configuration text or URL is empty');
  let configText=value,baseUrl:string|undefined,configKey:string|undefined;
  if(/^https?:\/\//i.test(value)){
    const pkIndex=value.indexOf(';pk;');const requestUrl=pkIndex>0?value.slice(0,pkIndex):value;
    if(pkIndex>0){configKey=value.slice(pkIndex+4).trim();if(!configKey)throw new Error('[SRC_CONFIG_DECRYPT_FAIL] ;pk; 配置缺少解密 key');}
    const response=await broker.request({sourceId:'config-import',url:requestUrl,headers:{'User-Agent':browserUserAgent,Accept:'application/json,text/plain,*/*'},timeoutMs:networkTimeoutMs(store,20_000),retries:2});
    if(!response.ok)throw new Error(`配置地址返回 HTTP ${response.status}`);configText=await response.text();baseUrl=response.url||requestUrl;
  }
  const parsed=parseTVBoxConfig(configText,{...(baseUrl?{baseUrl}:{}),...(configKey?{configKey}:{})});
  const sources=parsed.sources.map(source=>({...source,importGroupId:context.importGroupId,sourceLabel:context.sourceLabel,importedAt:context.importedAt}));
  const liveSources=parsed.liveSources.map(live=>({...live,origin:'tvbox' as const,importGroupId:context.importGroupId,sourceLabel:context.sourceLabel,importedAt:context.importedAt}));
  for(const source of sources)store.saveSource(source);for(const live of liveSources){store.saveLiveSource(live);clearLiveRouteCache(live.id);}await syncSources();const compatibility=await checkImportCompatibility(store,sources,liveSources);return{...parsed,sources,liveSources,importGroupId:context.importGroupId,sourceLabel:context.sourceLabel,importedAt:context.importedAt,compatibility};
}
function managedPlaylistPath(sourceId:string):string{return safeManagedPlaylistPath(path.join(app.getPath('userData'),'playlists'),sourceId);}
async function readLiveSourceText(store:DataService,source:LiveSourceConfig,force=false):Promise<string>{
  if(source.endpoint.startsWith('fnd-local://'))return readFile(managedPlaylistPath(source.id),'utf8');
  if(cache&&!force){const saved=await cache.get('live-playlists',source.id);if(saved)return saved.data.toString('utf8');}
  const text=await fetchText(store,'live:'+source.id,source.endpoint,source.headers);if(cache)await cache.put('live-playlists',source.id,Buffer.from(text),'text/plain',12*60*60*1000);return text;
}
async function loadLiveGroups(store:DataService,sourceId:string,force=false):Promise<LiveGroup[]>{
  if(!force){const cached=liveGroupsCache.get(sourceId);if(cached)return cached;}
  const source=store.listLiveSources().find(item=>item.id===sourceId);if(!source)throw new Error('Live source not found');
  const groups:LiveGroup[]=parseLivePlaylist(await readLiveSourceText(store,source,force)).map(group=>({...group,channels:group.channels.map(channel=>{const {logo,...channelWithoutLogo}=channel;const headers={...(source.headers??{}),...(channel.headers??{})};const resolvedLogo=logo?imageUrl(logo,'live:'+sourceId):undefined;return{...channelWithoutLogo,...(Object.keys(headers).length?{headers}:{}),...(resolvedLogo?{logo:resolvedLogo}:{})};})}));
  liveGroupsCache.set(sourceId,groups);return groups;
}
function compatibilityStage(message:string,auditStage?:string):CompatibilityStage{if(/classnotfound|missing|not found|unsupported|未提供|未授权|停用/i.test(message))return /classnotfound|jar|module|manifest/i.test(message)?'load':'preflight';if(/timeout|timed out|http|network|fetch|连接|响应|403|404|5\d\d/i.test(message))return'network';if(/parse|format|json|xml|normalize|格式|解析|未返回/i.test(message))return'normalize';if(auditStage==='home')return'init';return'invoke';}
function compatibilityRetryable(stage:CompatibilityStage,message:string):boolean{return stage==='network'||/timeout|403|429|5\d\d|停用|未授权|配置|jar|header|user-agent|referer/i.test(message);}
function persistCompatibility(store:DataService,result:SourceCompatibilityResult):void{const previous=store.listSourceHealth().find(item=>item.sourceId===result.sourceId);const successCount=(previous?.successCount??0)+(result.compatible?1:0);const failureCount=(previous?.failureCount??0)+(result.compatible?0:1);const successRate=successCount/Math.max(1,successCount+failureCount);store.saveSourceHealth({sourceId:result.sourceId,ok:result.compatible,latencyMs:result.durationMs,checkedAt:result.checkedAt,score:result.compatible?Math.max(10,Math.min(100,Math.round((100-result.durationMs/100)*(0.5+successRate/2)))):Math.round(successRate*20),successCount,failureCount,successRate,compatibilityStage:result.stage,retryable:result.retryable,...(result.compatible?{lastSuccess:result.checkedAt,message:'兼容'}:{lastFailure:result.checkedAt,failureReason:result.reason??'兼容性检查失败',message:result.reason??'兼容性检查失败'})});}
async function checkPointCompatibility(store:DataService,source:SourceConfig):Promise<SourceCompatibilityResult>{const started=performance.now(),checkedAt=new Date().toISOString();if(!source.enabled){const reason=source.trust==='B'?'可执行来源尚未授权启用，无法执行运行时兼容性检查。确认信任并启用后可重试。':'来源当前已停用，启用后可重试兼容性检查。';const result:SourceCompatibilityResult={sourceId:source.id,sourceName:source.name,sourceType:'vod',compatible:false,stage:'preflight',retryable:true,checkedAt,durationMs:0,reason};persistCompatibility(store,result);return result;}try{const audit=await sourceEngine.audit(source.id);const durationMs=audit.stages.reduce((sum,stage)=>sum+stage.durationMs,0);const failed=audit.stages.find(stage=>!stage.ok);const reason=failed?.message??(audit.ok?'':'来源没有完成五阶段调用链');const stage=audit.ok?'normalize':compatibilityStage(reason,failed?.stage);const result:SourceCompatibilityResult={sourceId:source.id,sourceName:source.name,sourceType:'vod',compatible:audit.ok,stage,retryable:audit.ok?false:compatibilityRetryable(stage,reason),checkedAt:audit.checkedAt,durationMs,...(reason?{reason}:{} )};persistCompatibility(store,result);return result;}catch(error){const reason=sourceCompatibilityError(error),stage=compatibilityStage(reason);const result:SourceCompatibilityResult={sourceId:source.id,sourceName:source.name,sourceType:'vod',compatible:false,stage,retryable:compatibilityRetryable(stage,reason),checkedAt,durationMs:Math.round(performance.now()-started),reason};persistCompatibility(store,result);return result;}}
async function checkLiveCompatibility(store:DataService,source:LiveSourceConfig):Promise<SourceCompatibilityResult>{const started=performance.now(),checkedAt=new Date().toISOString();try{const groups=await loadLiveGroups(store,source.id,true);const channelCount=groups.reduce((sum,group)=>sum+group.channels.length,0);if(channelCount===0)throw new Error('播放列表未返回可识别频道');const result:SourceCompatibilityResult={sourceId:source.id,sourceName:source.name,sourceType:'live',compatible:true,stage:'normalize',retryable:false,checkedAt,durationMs:Math.round(performance.now()-started),reason:`已识别 ${channelCount} 个直播频道`};persistCompatibility(store,result);return result;}catch(error){const reason=error instanceof Error?error.message:String(error),stage=compatibilityStage(reason);const result:SourceCompatibilityResult={sourceId:source.id,sourceName:source.name,sourceType:'live',compatible:false,stage,retryable:compatibilityRetryable(stage,reason),checkedAt,durationMs:Math.round(performance.now()-started),reason};persistCompatibility(store,result);return result;}}
async function checkImportCompatibility(store:DataService,sources:SourceConfig[],liveSources:LiveSourceConfig[]):Promise<SourceCompatibilityResult[]>{const tasks=[...sources.map(source=>()=>checkPointCompatibility(store,source)),...liveSources.map(source=>()=>checkLiveCompatibility(store,source))];const output=new Array<SourceCompatibilityResult>(tasks.length);let cursor=0;const worker=async()=>{while(cursor<tasks.length){const index=cursor++,task=tasks[index];if(task)output[index]=await task();}};await Promise.all(Array.from({length:Math.min(4,Math.max(1,tasks.length))},worker));mainWindow?.webContents.send('source:healthChanged',{ok:output.every(item=>item.compatible),checkedAt:new Date().toISOString()});return output.filter(Boolean);}
async function resolveLiveChannel(store:DataService,sourceId:string,channelId:string):Promise<LiveChannel>{const groups=await loadLiveGroups(store,sourceId);const channel=groups.flatMap(group=>group.channels).find(item=>item.id===channelId);if(!channel)throw new Error('Live channel no longer exists in this playlist');return channel;}
async function loadEpg(store:DataService,liveSourceId:string,force=false):Promise<number>{if(!cache)throw new Error('Cache is not initialized');const source=store.listLiveSources().find(item=>item.id===liveSourceId);if(!source?.epg)return 0;const url=resolveEpgTemplate(source.epg,new Date());const key=`${liveSourceId}|${url}`;let bytes:Buffer;const cached=!force?await cache.get('epg',key):undefined;if(cached)bytes=cached.data;else{const response=await broker.request({sourceId:`epg:${liveSourceId}`,url,...(source.headers?{headers:source.headers}:{}),timeoutMs:networkTimeoutMs(store,20_000),retries:2});if(!response.ok)throw new Error(`EPG HTTP ${response.status}`);bytes=Buffer.from(await response.arrayBuffer());await cache.put('epg',key,bytes,response.headers.get('content-type')??'application/xml',6*60*60*1000);}const programs=await epgWorker.parse(bytes);store.replaceEpg(liveSourceId,programs);store.setSetting('epg.lastRefresh.'+liveSourceId,new Date().toISOString());return programs.length;}
async function refreshConfiguredEpg(store:DataService,log:JsonLogger):Promise<void>{for(const source of store.listLiveSources().filter(item=>item.enabled&&item.epg)){try{const count=await loadEpg(store,source.id,false);log.info('epg','background refresh completed',{liveSourceId:source.id,count});}catch(error){log.warn('epg','background refresh failed',{liveSourceId:source.id,detail:error instanceof Error?error.message:String(error)});}}}

async function playResolved(store:DataService,request:{sourceId:string;videoId:string;videoName:string;flag:string;episodeId:string;episodeName:string;poster?:string|undefined;episodeListJson?:string|undefined}){
  const source=store.listSources().find(item=>item.id===request.sourceId);if(!source)throw new Error('[P1000] 来源不存在或已被删除，请从点播页重新选择。');broadcastPlaybackStage('source-resolving','正在获取点播线路…');
  const totalStarted=performance.now(),cacheKey=playbackCacheKey(source.id,request.flag,request.episodeId);prunePlaybackCaches();let cacheHit=false,sourceResolveMs=0,resolverMs=0,playerLoadMs=0;
  try{
    let resolved:PlayResult;let resolution:PlaybackResolution;const cached=playbackResolutionCache.get(cacheKey);
    if(cached&&cached.expiresAt>Date.now()){cacheHit=true;resolved=cached.resolved;resolution={...cached.resolution,fallbackAttempted:false};}
    else{playbackResolutionCache.delete(cacheKey);const sourceStarted=performance.now();try{resolved=await sourceEngine.play(request.sourceId,request.flag,request.episodeId);}catch(error){throw new Error(`[P1001] 来源解析播放地址失败：${error instanceof Error?error.message:String(error)}`);}sourceResolveMs=Math.round(performance.now()-sourceStarted);broadcastPlaybackStage('probing','正在解析媒体地址…');const resolverStarted=performance.now();resolution=await playbackResolver.resolve({sourceId:source.id,sourceKind:source.kind,flag:request.flag,resolved,sourceHeaders:source.headers,playUrl:source.playUrl,playerType:source.playerType});resolverMs=Math.round(performance.now()-resolverStarted);if(!resolved.drm)rememberPlaybackResolution(cacheKey,resolved,resolution);}
    const resolveFresh=async()=>{const sourceStarted=performance.now();resolved=await sourceEngine.play(request.sourceId,request.flag,request.episodeId);sourceResolveMs+=Math.round(performance.now()-sourceStarted);const resolverStarted=performance.now();resolution=await playbackResolver.resolve({sourceId:source.id,sourceKind:source.kind,flag:request.flag,resolved,sourceHeaders:source.headers,playUrl:source.playUrl,playerType:source.playerType});resolverMs+=Math.round(performance.now()-resolverStarted);if(!resolved.drm)rememberPlaybackResolution(cacheKey,resolved,resolution);};
    const loadMedia=async(current:PlaybackResolution)=>{const started=performance.now();broadcastPlaybackStage('connecting','正在连接媒体服务器…');const result=await player.load({url:current.url,...(Object.keys(current.headers).length?{headers:current.headers}:{}),profile:'vod'},()=>{recordPerformanceMetric('playerLoadAcceptedMs',performance.now()-started);broadcastPlaybackStage('buffering','正在缓冲媒体…');});const elapsed=Math.round(performance.now()-started);playerLoadMs+=elapsed;recordPerformanceMetric('bufferingDurationMs',elapsed);recordPerformanceMetric('bufferingCount',1);return result;};
    const forceFallback=async()=>{const resolverStarted=performance.now();const fallback=await playbackResolver.resolve({sourceId:source.id,sourceKind:source.kind,flag:request.flag,resolved:{...resolved,url:resolution.url,headers:resolution.headers,parse:true},sourceHeaders:source.headers,playUrl:source.playUrl,playerType:source.playerType,forceSniff:true});resolverMs+=Math.round(performance.now()-resolverStarted);resolution=fallback;if(!resolved.drm)rememberPlaybackResolution(cacheKey,resolved,resolution);lastPlaybackDiagnostic={checkedAt:new Date().toISOString(),sourceId:source.id,flag:request.flag,resolverDecision:fallback.mode,inputUrlHost:fallback.inputHost,finalUrlHost:fallback.finalHost,fallbackAttempted:true,cacheHit:false,status:'fallback'};return loadMedia(fallback);};
    lastPlaybackDiagnostic={checkedAt:new Date().toISOString(),sourceId:source.id,flag:request.flag,resolverDecision:resolution.mode,inputUrlHost:resolution.inputHost,finalUrlHost:resolution.finalHost,contentType:resolution.contentType,httpStatus:resolution.httpStatus,fallbackAttempted:false,cacheHit,status:'resolved'};logger?.info('player','playback resolved',{sourceId:source.id,videoId:request.videoId,episodeName:request.episodeName,flag:request.flag,resolverDecision:resolution.mode,cacheHit});
    let result:{ok:boolean;detail?:string};
    try{result=await loadMedia(resolution);}catch(first){let detail=first instanceof Error?first.message:String(first);if(cacheHit){playbackResolutionCache.delete(cacheKey);cacheHit=false;await resolveFresh();try{result=await loadMedia(resolution);}catch(second){detail=second instanceof Error?second.message:String(second);if(shouldRetryPlayerFailure(detail)&&/^https?:\/\//i.test(resolution.url)&&resolution.mode==='direct')result=await forceFallback();else throw second;}}else if(shouldRetryPlayerFailure(detail)&&/^https?:\/\//i.test(resolution.url)&&resolution.mode==='direct')result=await forceFallback();else throw first;}
    if(!result.ok&&shouldRetryPlayerFailure(result.detail)&&/^https?:\/\//i.test(resolution.url)&&resolution.mode==='direct'){playbackResolutionCache.delete(cacheKey);result=await forceFallback();}
    if(!result.ok)throw new Error(`[PLAY_MEDIA_OPEN_FAILED] PlayerHost 加载媒体失败：${result.detail??'未知原因'}`);
    for(const subtitle of resolved.subtitles??[]){try{await player.command({command:'subtitle-add',value:subtitle.url});}catch{/* optional subtitle failure */}}
    let historyEpisodes:Array<{flag:string;id:string;name:string}>|undefined;if(request.episodeListJson)try{const parsed=JSON.parse(request.episodeListJson) as unknown;if(Array.isArray(parsed))historyEpisodes=parsed.filter((item):item is {flag:string;id:string;name:string}=>Boolean(item&&typeof item==='object'&&typeof(item as {flag?:unknown}).flag==='string'&&typeof(item as {id?:unknown}).id==='string'&&typeof(item as {name?:unknown}).name==='string')).slice(0,500);}catch{/* optional snapshot */}
    store.addHistory({id:randomUUID(),sourceId:source.id,sourceName:source.name,videoId:request.videoId,videoName:request.videoName,episodeName:request.episodeName,url:resolution.url,playedAt:new Date().toISOString(),flag:request.flag,episodeId:request.episodeId,...(request.poster?{poster:request.poster}:{}),...(historyEpisodes?.length?{episodes:historyEpisodes}:{})});
    const totalMs=Math.round(performance.now()-totalStarted);lastPerformanceDiagnostic={checkedAt:new Date().toISOString(),kind:'vod',sourceId:source.id,sourceResolveMs,resolverMs,playerLoadMs,totalMs,cacheHit,status:'opened'};lastPlaybackDiagnostic={...(lastPlaybackDiagnostic??{}),checkedAt:new Date().toISOString(),sourceId:source.id,resolverDecision:resolution.mode,finalUrlHost:resolution.finalHost,cacheHit,status:'opened'};logger?.info('player','media opened',{sourceId:source.id,videoId:request.videoId,episodeName:request.episodeName,resolverDecision:resolution.mode,cacheHit,totalMs});broadcastPlaybackStage('playing','媒体已打开');void measureFirstFrame(totalStarted);return result;
  }catch(error){playbackResolutionCache.delete(cacheKey);const detail=error instanceof Error?error.message:String(error);lastPerformanceDiagnostic={checkedAt:new Date().toISOString(),kind:'vod',sourceId:source.id,sourceResolveMs,resolverMs,playerLoadMs,totalMs:Math.round(performance.now()-totalStarted),cacheHit,status:'failed'};lastPlaybackDiagnostic={...(lastPlaybackDiagnostic??{}),checkedAt:new Date().toISOString(),sourceId:source.id,status:'failed',errorCode:/^\[([A-Z0-9_]+)\]/.exec(detail)?.[1]??'P1099'};logger?.error('player','media open failed',{sourceId:source.id,videoId:request.videoId,episodeName:request.episodeName,detail});broadcastPlaybackStage('failed','播放失败',detail);throw error;}
}

function liveUrls(channel:LiveChannel):string[]{return[...new Set([channel.url,...(channel.urls??[])].map(url=>url.trim()).filter(Boolean))];}
async function probeLiveRoute(index:number,url:string,headers?:Record<string,string>):Promise<LiveRouteSpeed>{if(!/^https?:\/\//i.test(url))return{index,ok:true,latencyMs:0,bytes:0,kbps:0,message:'协议不支持预检'};const metric=await broker.measure({sourceId:'live-speed',url,headers:{...(headers??{}),Range:'bytes=0-65535'},timeoutMs:6_000,retries:0});return{index,ok:metric.ok,latencyMs:metric.latencyMs,bytes:metric.bytes,kbps:Math.round(metric.bytes*8/Math.max(metric.latencyMs,1)),...(!metric.ok?{message:metric.status?`HTTP ${metric.status}`:'连接失败'}:{})};}
async function speedLive(channel:LiveChannel):Promise<LiveRouteSpeed[]>{return Promise.all(liveUrls(channel).map((url,index)=>probeLiveRoute(index,url,channel.headers)));}
function orderedRouteIndexes(speeds:LiveRouteSpeed[]):number[]{const rank=(item:LiveRouteSpeed)=>!item.ok?2:item.message==='协议不支持预检'?1:0;return[...speeds].sort((a,b)=>rank(a)-rank(b)||(a.latencyMs||Number.MAX_SAFE_INTEGER)-(b.latencyMs||Number.MAX_SAFE_INTEGER)||a.index-b.index).map(item=>item.index);}
async function playLive(channel:LiveChannel,log:JsonLogger,sourceId:string,preferredRouteIndex?:number,allowFallback=true):Promise<{ok:boolean;detail?:string;routeIndex:number;routeCount:number;attempts:Array<{index:number;ok:boolean;detail?:string}>}>{
  const urls=liveUrls(channel);if(urls.length===0)throw new Error('Invalid live URL');prunePlaybackCaches();const key=liveRouteKey(sourceId,channel.id),remembered=liveRouteCache.get(key);let order:number[];
  if(Number.isInteger(preferredRouteIndex)&&preferredRouteIndex!==undefined&&preferredRouteIndex>=0&&preferredRouteIndex<urls.length)order=[preferredRouteIndex,...(allowFallback?urls.map((_,index)=>index).filter(index=>index!==preferredRouteIndex):[])];
  else if(remembered&&remembered.expiresAt>Date.now()&&remembered.routeIndex<urls.length)order=[remembered.routeIndex,...(allowFallback?urls.map((_,index)=>index).filter(index=>index!==remembered.routeIndex):[])];
  else order=urls.map((_,index)=>index);
  let last='没有可播放线路';const attempts:Array<{index:number;ok:boolean;detail?:string}>=[],started=performance.now();log.info('live','live playback requested',{sourceId,channelId:channel.id,channelName:channel.name,routeCount:urls.length,routeOrder:order,allowFallback,lastKnownGood:Boolean(remembered)});broadcastPlaybackStage('connecting',`正在连接直播频道「${channel.name}」…`);
  for(const index of order){const url=urls[index];if(!url)continue;const routeStarted=performance.now();try{const result=await player.load({url,...(channel.headers?{headers:channel.headers}:{}),profile:'live'},()=>{recordPerformanceMetric('playerLoadAcceptedMs',performance.now()-routeStarted);broadcastPlaybackStage('buffering',`直播线路 ${index+1} 正在缓冲…`);});if(result.ok){rememberLiveRoute(key,index);const totalMs=Math.round(performance.now()-started);lastPerformanceDiagnostic={checkedAt:new Date().toISOString(),kind:'live',sourceId,channelId:channel.id,routeIndex:index,routeLoadMs:Math.round(performance.now()-routeStarted),totalMs,lastKnownGood:Boolean(remembered),status:'opened'};log.info('live','live route opened',{sourceId,channelId:channel.id,routeIndex:index,routeCount:urls.length,totalMs});recordPerformanceMetric('bufferingDurationMs',Math.round(performance.now()-routeStarted));recordPerformanceMetric('bufferingCount',1);broadcastPlaybackStage('playing',`直播频道「${channel.name}」已连接`);attempts.push({index,ok:true});return{...result,routeIndex:index,routeCount:urls.length,attempts};}last=result.detail??'PlayerHost rejected route';}catch(error){last=error instanceof Error?error.message:String(error);}attempts.push({index,ok:false,detail:last});if(remembered?.routeIndex===index)liveRouteCache.delete(key);log.warn('live','live route failed',{sourceId,channelId:channel.id,routeIndex:index,detail:last});if(!allowFallback)break;}
  const totalMs=Math.round(performance.now()-started);lastPerformanceDiagnostic={checkedAt:new Date().toISOString(),kind:'live',sourceId,channelId:channel.id,totalMs,status:'failed'};log.error('live','all live routes failed',{sourceId,channelId:channel.id,routeCount:urls.length,detail:last});broadcastPlaybackStage('failed','直播播放失败',last);throw new Error(`所有直播线路均不可用：${last}`);
}

async function aggregateSearch(keyword:string){aggregateController?.abort(new DOMException('Superseded','AbortError'));const controller=new AbortController();aggregateController=controller;const sources=(data?.listSources()??[]).filter(source=>source.enabled&&source.searchable!==false);const output=new Array<{sourceId:string;sourceName:string;items:VideoCard[];error:string|null}>(sources.length);let cursor=0;const run=async()=>{while(cursor<sources.length&&!controller.signal.aborted){const index=cursor++;const source=sources[index];if(!source)continue;const perSource=new AbortController();const timer=setTimeout(()=>perSource.abort(new DOMException('Source search timeout','TimeoutError')),30_000);const abort=()=>perSource.abort(controller.signal.reason);controller.signal.addEventListener('abort',abort,{once:true});try{const result=await sourceEngine.search(source.id,keyword,1,perSource.signal);output[index]={sourceId:source.id,sourceName:source.name,items:result.items.map(item=>wrapCard(source.id,item)),error:null};}catch(error){output[index]={sourceId:source.id,sourceName:source.name,items:[],error:controller.signal.aborted?'已取消':error instanceof Error?error.message:String(error)};}finally{clearTimeout(timer);controller.signal.removeEventListener('abort',abort);}}};await Promise.all(Array.from({length:Math.min(4,Math.max(1,sources.length))},run));if(aggregateController===controller)aggregateController=undefined;return output.filter(Boolean);}

async function collectDiagnostics(store:DataService){const gpu=await app.getGPUInfo('basic').catch(()=>({}));const sourceInfo=await sourceEngine.info().catch(()=>({ok:false}));const playerStats=await player.query('stats').catch(()=>undefined);const cacheStats=cache?await cache.stats():{bytes:0,files:0,maxBytes:0};const javaRuntime=await probeJavaDiagnostic();const jarRuntime=collectJarRuntimeDiagnostic(store.listSources(),store.listSourceHealth(),javaRuntime);const sourceFile=app.isPackaged?path.join(process.resourcesPath,'native','player-host','SOURCE.txt'):path.join(app.getAppPath(),'third_party','mpv','win-x64','SOURCE.txt');const libmpv=(await readFile(sourceFile,'utf8').catch(()=>'' )).split(/\r?\n/).slice(0,6).join('; ');const cpu=os.cpus();return{appVersion:app.getVersion(),electron:process.versions.electron??'',chromium:process.versions.chrome??'',node:process.versions.node,windowsBuild:os.release(),architecture:process.arch,cpu:cpu[0]?.model??'unknown',cpuCores:cpu.length,memoryGB:Number((os.totalmem()/1024/1024/1024).toFixed(1)),gpu:JSON.stringify((gpu as{gpuDevice?:unknown}).gpuDevice??[]),libmpv,hardwareDecode:playerStats?.hwdec??'not-active',databaseVersion:store.getDatabaseVersion(),sourceEngineVersion:sourceInfo.version??'unknown',javaAvailable:javaRuntime.available,javaCommand:javaRuntime.command,javaVersion:javaRuntime.version,javaMajor:javaRuntime.major,jvmSpiderHostVersion:'1.2.0',pluginSdkVersion:'1.3.0',playbackResolverVersion:'2.0',lastResolverDecision:String(lastPlaybackDiagnostic?.resolverDecision??'not-used'),lastResolverFallback:Boolean(lastPlaybackDiagnostic?.fallbackAttempted),jarRuntimePolicy:jarRuntime.policy,jarSourceCount:jarRuntime.sources.length,jarRestrictedCount:jarRuntime.sources.filter(item=>item.state!=='jvm-ready'&&item.state!=='unknown').length,lastPerformanceKind:String(lastPerformanceDiagnostic?.kind??'not-used'),lastPerformanceTotalMs:Number(lastPerformanceDiagnostic?.totalMs??0),playbackResolutionCacheEntries:playbackResolutionCache.size,liveRouteCacheEntries:liveRouteCache.size,performanceP95:JSON.stringify(performanceSummary()),sourceCount:store.listSources().length,liveSourceCount:store.listLiveSources().length,cacheBytes:cacheStats.bytes,cacheFiles:cacheStats.files,cacheMaxBytes:cacheStats.maxBytes};}
async function exportDiagnostics(store:DataService,log:JsonLogger):Promise<{path?:string;canceled:boolean}>{const chosen=await dialog.showSaveDialog({title:'导出诊断包',defaultPath:`Free-New-Desk-Diagnostics-${new Date().toISOString().slice(0,10)}.zip`,filters:[{name:'ZIP',extensions:['zip']}]});if(chosen.canceled||!chosen.filePath)return{canceled:true};const dir=path.join(app.getPath('temp'),`free-new-desk-diag-${randomUUID()}`);await mkdir(dir,{recursive:true});try{await writeFile(path.join(dir,'diagnostics.json'),JSON.stringify(await collectDiagnostics(store),null,2),'utf8');await writeFile(path.join(dir,'playback-runtime.json'),JSON.stringify({resolverVersion:'2.0',last:lastPlaybackDiagnostic??null},null,2),'utf8');await writeFile(path.join(dir,'performance-runtime.json'),JSON.stringify({last:lastPerformanceDiagnostic??null,uiMetrics:performanceSummary(),playbackResolutionCacheEntries:playbackResolutionCache.size,liveRouteCacheEntries:liveRouteCache.size},null,2),'utf8');const javaRuntime=await probeJavaDiagnostic();await writeFile(path.join(dir,'jar-runtime.json'),JSON.stringify(collectJarRuntimeDiagnostic(store.listSources(),store.listSourceHealth(),javaRuntime),null,2),'utf8');await writeFile(path.join(dir,'source-health.json'),JSON.stringify(store.listSourceHealth(),null,2),'utf8');await writeFile(path.join(dir,'sources.json'),JSON.stringify(store.listSources().map(({id,name,kind,enabled,trust})=>({id,name,kind,enabled,trust})),null,2),'utf8');const liveSources=store.listLiveSources().map(source=>{let endpoint=source.endpoint;try{const parsed=new URL(endpoint);parsed.search='';parsed.hash='';endpoint=parsed.toString();}catch{endpoint='<non-http>';}return{id:source.id,name:source.name,enabled:source.enabled,endpoint,...(source.epg?{epg:source.epg}:{}),...(source.headers?{headers:redactSecrets(source.headers)}:{})};});await writeFile(path.join(dir,'live-sources.json'),JSON.stringify(liveSources,null,2),'utf8');await writeFile(path.join(dir,'player-runtime.json'),JSON.stringify(await player.query('stats').catch(error=>({error:error instanceof Error?error.message:String(error)})),null,2),'utf8');const logs=await readFile(log.filePath,'utf8').catch(()=>'' );await writeFile(path.join(dir,'app.log'),logs.split(/\r?\n/).slice(-5000).join('\n'),'utf8');if(process.platform!=='win32')throw new Error('Diagnostics ZIP export is currently supported on Windows');await new Promise<void>((resolve,reject)=>{const child=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',"Compress-Archive -Path (Join-Path $env:FND_DIAG_SRC '*') -DestinationPath $env:FND_DIAG_ZIP -Force"],{windowsHide:true,env:{...process.env,FND_DIAG_SRC:dir,FND_DIAG_ZIP:chosen.filePath as string}});child.once('error',reject);child.once('exit',code=>code===0?resolve():reject(new Error(`Compress-Archive failed with ${code}`)));});return{path:chosen.filePath,canceled:false};}finally{await rm(dir,{recursive:true,force:true});}}
function newer(latest:string,current:string):boolean{const parse=(value:string)=>value.replace(/^v/,'').split(/[.-]/).slice(0,3).map(part=>Number(part)||0);const a=parse(latest),b=parse(current);for(let i=0;i<3;i++){if((a[i]??0)!==(b[i]??0))return(a[i]??0)>(b[i]??0);}return false;}

const selfTestChecks:ReadonlyArray<{name:string;run:(store:DataService,log:JsonLogger)=>Promise<string>}>=[
  {name:'来源引擎',run:async()=>{const ok=await sourceEngine.ping();return ok?'Source Engine 运行中':(()=>{throw new Error('Source Engine ping 失败');})();}},
  {name:'本地数据库',run:async store=>{const version=store.getDatabaseVersion();return `Schema ${version} · ${store.listSources().length} 点播 / ${store.listLiveSources().length} 直播来源`;}},
  {name:'缓存目录',run:async()=>{if(!cache)throw new Error('缓存服务未初始化');await cache.put('selftest','probe',Buffer.from('ok'),'text/plain',60_000);const restored=await cache.get('selftest','probe');await cache.clear('selftest');if(!restored||restored.data.toString()!=='ok')throw new Error('缓存写入后无法读回');return '写入/读取/清理正常';}},
  {name:'日志目录',run:async(_store,log)=>{const lines=(await readFile(log.filePath,'utf8').catch(()=>'')).split(/\r?\n/).filter(Boolean).length;return `app.log 可访问 · ${lines} 条记录`;}},
  {name:'播放器内核',run:async()=>{try{const stats=await player.query('stats');return `PlayerHost 可达 · ${stats.paused?'空闲/已暂停':'播放中'}`;}catch(error){throw new Error(`PlayerHost 未连接：${error instanceof Error?error.message:String(error)}`);}}},
  {name:'网络栈',run:async store=>{const response=await broker.request({sourceId:'selftest-net',url:'https://api.github.com/zen',headers:{'User-Agent':browserUserAgent},timeoutMs:networkTimeoutMs(store,10_000),retries:0});if(!response.ok)throw new Error(`出站 HTTPS 请求失败（HTTP ${response.status}）`);return '出站 HTTPS 请求正常';}}
];
async function runSelfTestItem(store:DataService,log:JsonLogger,index:number):Promise<{name:string;ok:boolean;detail:string}>{
  const check=selfTestChecks[index];
  if(!check)throw new Error('Invalid self-test item');
  const started=Date.now();
  try{const detail=await check.run(store,log);const result={name:check.name,ok:true,detail:`${detail}（${Date.now()-started}ms）`};log.info('diagnostics','self test item passed',{name:check.name,detail});return result;}
  catch(error){const detail=error instanceof Error?error.message:String(error);const result={name:check.name,ok:false,detail:`${detail}（${Date.now()-started}ms）`};log.warn('diagnostics','self test item failed',{name:check.name,detail});return result;}
}

function showMainWindow():void{if(!mainWindow||mainWindow.isDestroyed())mainWindow=createWindow();if(mainWindow.isMinimized())mainWindow.restore();mainWindow.show();mainWindow.focus();}
function createTray():void{if(tray)return;const icon=nativeImage.createFromPath(app.getPath('exe'));tray=new Tray(icon.resize({width:16,height:16}));tray.setToolTip('Free New Desk');tray.setContextMenu(Menu.buildFromTemplate([{label:'显示主窗口',click:showMainWindow},{label:'检查更新',click:()=>{showMainWindow();mainWindow?.webContents.send('app:navigate','/settings?section=update');}},{type:'separator'},{label:'退出',click:()=>{quitting=true;app.quit();}}]));tray.on('double-click',showMainWindow);}
function installRuntimeGuards(store:DataService,log:JsonLogger):void{const previousClean=store.getSetting('lifecycle.cleanExit')!=='false';store.setSetting('lifecycle.cleanExit','false');if(!previousClean)log.warn('lifecycle','detected previous unclean shutdown',{recovery:'database and cache integrity checks completed during initialization'});process.on('uncaughtException',error=>log.fatal('crash','uncaught exception',{detail:error.stack??error.message}));process.on('unhandledRejection',reason=>log.error('crash','unhandled rejection',{detail:reason instanceof Error?reason.stack??reason.message:String(reason)}));powerMonitor.on('suspend',()=>{log.info('lifecycle','system suspend');void player.command({command:'pause',value:true}).catch(()=>undefined);});powerMonitor.on('resume',()=>{log.info('lifecycle','system resume');void sourceEngine.ping().then(ok=>log.info('source','source engine health after resume',{ok})).catch(error=>log.warn('source','source engine unavailable after resume',{detail:error instanceof Error?error.message:String(error)}));});powerMonitor.on('lock-screen',()=>{log.info('lifecycle','screen locked');void player.command({command:'pause',value:true}).catch(()=>undefined);});}
function scheduleSourceHealth(log:JsonLogger):void{sourceHealthTimer=setInterval(()=>{void sourceEngine.ping().then(ok=>{log.info('source','source engine heartbeat',{ok});mainWindow?.webContents.send('source:healthChanged',{ok,checkedAt:new Date().toISOString()});}).catch(error=>{log.warn('source','source engine heartbeat failed',{detail:error instanceof Error?error.message:String(error)});mainWindow?.webContents.send('source:healthChanged',{ok:false,checkedAt:new Date().toISOString()});});},30_000);sourceHealthTimer.unref();}
function scheduleReservationNotifications(store:DataService,log:JsonLogger):void{const check=()=>{const now=Date.now();for(const item of store.listReservations()){const starts=Date.parse(item.start);if(!Number.isFinite(starts)||starts<now||starts-now>120_000)continue;const key='reservation.notified.'+item.id;if(store.getSetting(key)==='true')continue;store.setSetting(key,'true');if(Notification.isSupported())new Notification({title:'节目即将开始',body:`${item.channelName} · ${item.programTitle}`}).show();log.info('reservation','upcoming program notification',{reservationId:item.id,start:item.start});}};check();reservationTimer=setInterval(check,30_000);reservationTimer.unref();}

function sourceCompatibilityError(error:unknown):string{const raw=error instanceof Error?error.message:String(error);const className=/ClassNotFoundException:\s*([A-Za-z0-9_.$]+)/i.exec(raw)?.[1];if(className)return `来源兼容性错误：配置引用的 Spider 类 ${className} 未包含在当前 JAR 中。请更换匹配的 Spider JAR、检查 ext/jar 配置，或停用该来源。`;return raw;}
async function guardedSourceCall<T>(sourceId:string,operation:string,log:JsonLogger,call:()=>Promise<T>):Promise<T>{try{return await call();}catch(error){const detail=sourceCompatibilityError(error);log.warn('source','source operation failed',{sourceId,operation,detail});throw new Error(detail);}}

interface RecentImportRecord{kind:string;name:string;importedAt:string;source?:string;count?:number;groupId?:string;}
type UpdateChannel='stable'|'daily';
interface RepoUpdateResult{current:string;latest:string;available:boolean;url:string;channel:UpdateChannel;checkedAt:string;publishedAt?:string;}
function recordImport(store:DataService,record:RecentImportRecord):void{let existing:RecentImportRecord[]=[];try{const parsed=JSON.parse(store.getSetting('imports.recent')??'[]') as unknown;if(Array.isArray(parsed))existing=parsed.filter((item):item is RecentImportRecord=>Boolean(item&&typeof item==='object'&&typeof(item as RecentImportRecord).name==='string'&&typeof(item as RecentImportRecord).importedAt==='string'));}catch{/* ignore malformed historic setting */}const records=[record,...existing.filter(item=>item.name!==record.name||item.importedAt!==record.importedAt)].slice(0,20);store.setSetting('imports.recent',JSON.stringify(records));}
async function recentDiagnosticEvents(log:JsonLogger,limit=20):Promise<Array<{time:string;level:string;category:string;message:string}>>{const safe=Math.min(Math.max(Math.trunc(limit),1),2000);const raw=await readFile(log.filePath,'utf8').catch(()=>'');const output:Array<{time:string;level:string;category:string;message:string}>=[];for(const line of raw.split(/\r?\n/).filter(Boolean).slice(-safe*3)){try{const value=JSON.parse(line) as Record<string,unknown>;if(typeof value.time==='string'&&typeof value.level==='string'&&typeof value.category==='string'&&typeof value.message==='string')output.push({time:value.time,level:value.level,category:value.category,message:value.message});}catch{/* ignore malformed lines */}}return output.slice(-safe).reverse();}
async function checkRepoUpdate(channel:UpdateChannel):Promise<RepoUpdateResult>{let release:{tag_name?:string;html_url?:string;draft?:boolean;published_at?:string}|undefined;if(channel==='stable')release=await broker.json<{tag_name?:string;html_url?:string;published_at?:string}>({sourceId:'update',url:'https://api.github.com/repos/cwe88108/free-new-desk-public/releases/latest',headers:{Accept:'application/vnd.github+json'},timeoutMs:10_000,retries:1});else{const releases=await broker.json<Array<{tag_name?:string;html_url?:string;draft?:boolean;published_at?:string}>>({sourceId:'update-daily',url:'https://api.github.com/repos/cwe88108/free-new-desk-public/releases?per_page=20',headers:{Accept:'application/vnd.github+json'},timeoutMs:10_000,retries:1});release=releases.find(item=>item.draft!==true);}const latest=release?.tag_name?.replace(/^v/,'')??app.getVersion();const releaseUrl=release?.html_url&&allowedExternal(release.html_url)?release.html_url:'https://github.com/cwe88108/free-new-desk-public/releases';return{current:app.getVersion(),latest,available:newer(latest,app.getVersion()),url:releaseUrl,channel,checkedAt:new Date().toISOString(),...(release?.published_at?{publishedAt:release.published_at}:{})};}
async function maybeAutoCheckUpdates(store:DataService,log:JsonLogger):Promise<void>{const schedule=store.getSetting('update.schedule')??(store.getSetting('update.autoCheck')==='false'?'off':'daily');if(schedule==='off')return;const interval=schedule==='weekly'?7*24*60*60*1000:24*60*60*1000;const last=Date.parse(store.getSetting('update.lastCheck')??'');if(Number.isFinite(last)&&Date.now()-last<interval)return;const channel:UpdateChannel=store.getSetting('update.channel')==='daily'?'daily':'stable';try{const result=await checkRepoUpdate(channel);store.setSetting('update.lastCheck',result.checkedAt);store.setSetting('update.lastResult',JSON.stringify(result));log.info('update','automatic update check completed',{channel,latest:result.latest,available:result.available});}catch(error){store.setSetting('update.lastCheck',new Date().toISOString());log.warn('update','automatic update check failed',{channel,detail:error instanceof Error?error.message:String(error)});}}

function registerIpc(store:DataService,log:JsonLogger):void{
  const trusted=<T>(handler:(input:unknown)=>Promise<T>|T)=>(event:IpcMainInvokeEvent,input:unknown)=>{requireLocalSender(event);return handler(input);};
  ipcMain.handle('app:getInfo',(event)=>{requireLocalSender(event);return{version:app.getVersion(),platform:process.platform,arch:process.arch,theme:nativeTheme.shouldUseDarkColors?'dark':'light',packaged:app.isPackaged};});
  ipcMain.handle('app:newWindow',(event,route:string)=>{requireLocalSender(event);if(typeof route!=='string'||!route.startsWith('/')||route.length>1024)throw new Error('Invalid app route');const child=createWindow();child.webContents.once('did-finish-load',()=>child.webContents.send('app:navigate',route));return true;});
  ipcMain.handle('app:action',trusted(input=>{if(typeof input==='object'&&input!==null&&'copy' in input){clipboard.writeText(String((input as {copy:unknown}).copy));return true;}if(input==='reload'){mainWindow?.webContents.reload();return true;}if(input==='devtools'){mainWindow?.webContents.toggleDevTools();return true;}if(input==='quit'){quitting=true;app.quit();return true;}throw new Error('Invalid application action');}));
  ipcMain.handle('source:ping',(event)=>{requireLocalSender(event);return sourceEngine.ping();});
  ipcMain.handle('source:list',(event)=>{requireLocalSender(event);return store.listSources();});
  ipcMain.handle('source:save',trusted(async input=>{const source=SourceConfigSchema.parse(input);store.saveSource(source);await cache?.clear('vod-data');await syncSources();log.info('source','source saved',{sourceId:source.id,kind:source.kind,enabled:source.enabled});return source;}));
  ipcMain.handle('source:setEnabledBulk',trusted(async input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const clean=(raw:unknown)=>Array.isArray(raw)?[...new Set(raw.filter((item):item is string=>typeof item==='string'&&item.length>0&&item.length<=512))].slice(0,10_000):[];const vodSourceIds=clean(value.vodSourceIds),liveSourceIds=clean(value.liveSourceIds),enabled=value.enabled===true;if(vodSourceIds.length+liveSourceIds.length===0)return{requested:0,changed:0,unchanged:0,failed:[]};const existingVod=new Set(store.listSources().map(item=>item.id)),existingLive=new Set(store.listLiveSources().map(item=>item.id));const failed=[...vodSourceIds.filter(id=>!existingVod.has(id)),...liveSourceIds.filter(id=>!existingLive.has(id))].map(sourceId=>({sourceId,reason:'来源不存在或已经删除'}));const validVod=vodSourceIds.filter(id=>existingVod.has(id)),validLive=liveSourceIds.filter(id=>existingLive.has(id));const result=store.setSourcesEnabledBulk(validVod,validLive,enabled);if(validVod.length){await cache?.clear('vod-data');await syncSources();}log.info('source','bulk source state changed',{enabled,requested:vodSourceIds.length+liveSourceIds.length,changed:result.changed,failed:failed.length});return{requested:vodSourceIds.length+liveSourceIds.length,changed:result.changed,unchanged:result.unchanged,failed};}));
  ipcMain.handle('source:remove',trusted(async input=>{const{sourceId}=SourceIdRequestSchema.parse(input);const removed=store.removeSource(sourceId);await cache?.clear('vod-data');await syncSources();return removed;}));
  ipcMain.handle('source:removeImportGroup',trusted(async input=>{const importGroupId=typeof input==='object'&&input!==null?String((input as {importGroupId?:unknown}).importGroupId??'').trim():'';if(!importGroupId)throw new Error('Invalid import group');const managed=store.listLiveSources().filter(source=>source.importGroupId===importGroupId&&source.endpoint.startsWith('fnd-local://'));const removed=store.removeImportGroup(importGroupId);let managedFiles=0;for(const source of managed){liveGroupsCache.delete(source.id);try{await rm(managedPlaylistPath(source.id),{force:true});managedFiles+=1;}catch(error){log.warn('source','managed playlist cleanup failed',{sourceId:source.id,detail:error instanceof Error?error.message:String(error)});}}for(const sourceId of removed.liveSourceIds){liveGroupsCache.delete(sourceId);clearLiveRouteCache(sourceId);}await Promise.all([cache?.clear('vod-data'),cache?.clear('live-playlists')]);try{const parsed=JSON.parse(store.getSetting('imports.recent')??'[]') as RecentImportRecord[];if(Array.isArray(parsed))store.setSetting('imports.recent',JSON.stringify(parsed.filter(item=>item.groupId!==importGroupId)));}catch{/* malformed historic import list */}await syncSources();const result:ImportGroupRemovalResult={importGroupId,pointSources:removed.pointSources,liveSources:removed.liveSources,history:removed.history,health:removed.health,liveFavorites:removed.liveFavorites,epgPrograms:removed.epgPrograms,reservations:removed.reservations,managedFiles};log.info('source','import group removed',{...result});return result;}));
  ipcMain.handle('source:checkImportGroup',trusted(async input=>{const importGroupId=typeof input==='object'&&input!==null?String((input as {importGroupId?:unknown}).importGroupId??'').trim():'';if(!importGroupId)throw new Error('Invalid import group');const sources=store.listSources().filter(source=>source.importGroupId===importGroupId),liveSources=store.listLiveSources().filter(source=>source.importGroupId===importGroupId);if(sources.length+liveSources.length===0)throw new Error('导入源不存在或已经删除');return checkImportCompatibility(store,sources,liveSources);}));
  ipcMain.handle('source:home',trusted(async input=>{const{sourceId}=SourceIdRequestSchema.parse(input);const force=Boolean(input&&typeof input==='object'&&(input as {force?:unknown}).force===true);return guardedSourceCall(sourceId,'home',log,async()=>wrapHome(sourceId,await cachedJson('vod-data',`home:${sourceId}`,force,6*60*60*1000,()=>sourceEngine.home(sourceId))));}));
  ipcMain.handle('source:category',trusted(async input=>{const request=SourceCategoryRequestSchema.parse(input),force=Boolean(input&&typeof input==='object'&&(input as {force?:unknown}).force===true),filters=request.filters??{},page=request.page??1;return guardedSourceCall(request.sourceId,'category',log,async()=>wrapCategory(request.sourceId,await cachedJson('vod-data',`category:${request.sourceId}:${request.categoryId}:${page}:${filterCacheKey(filters)}`,force,2*60*60*1000,()=>sourceEngine.category(request.sourceId,request.categoryId,page,filters))));}));
  ipcMain.handle('source:search',trusted(async input=>{const request=SourceSearchRequestSchema.parse(input),force=Boolean(input&&typeof input==='object'&&(input as {force?:unknown}).force===true),page=request.page??1;return guardedSourceCall(request.sourceId,'search',log,async()=>wrapSearch(request.sourceId,await cachedJson('vod-data',`search:${request.sourceId}:${request.keyword}:${page}`,force,30*60*1000,()=>sourceEngine.search(request.sourceId,request.keyword,page))));}));
  ipcMain.handle('source:detail',trusted(async input=>{const request=SourceDetailRequestSchema.parse(input),force=Boolean(input&&typeof input==='object'&&(input as {force?:unknown}).force===true);return guardedSourceCall(request.sourceId,'detail',log,async()=>wrapDetail(request.sourceId,await cachedJson('vod-data',`detail:${request.sourceId}:${request.ids.join('\u001f')}`,force,12*60*60*1000,()=>sourceEngine.detail(request.sourceId,request.ids))));}));
  ipcMain.handle('source:audit',trusted(async input=>{const{sourceId}=SourceIdRequestSchema.parse(input);const result=await sourceEngine.audit(sourceId);const latencyMs=result.stages.reduce((sum,stage)=>sum+stage.durationMs,0);const previous=store.listSourceHealth().find(item=>item.sourceId===sourceId);const successCount=(previous?.successCount??0)+(result.ok?1:0);const failureCount=(previous?.failureCount??0)+(result.ok?0:1);const successRate=successCount/Math.max(1,successCount+failureCount);const checkedAt=result.checkedAt;const failed=result.stages.find(stage=>!stage.ok),reason=failed?.message??'Audit failed',stage=result.ok?'normalize':compatibilityStage(reason,failed?.stage);const health:SourceHealth={sourceId,ok:result.ok,latencyMs,checkedAt,score:result.ok?Math.max(10,Math.min(100,Math.round((100-latencyMs/100)*(0.5+successRate/2)))):Math.round(successRate*20),successCount,failureCount,successRate,compatibilityStage:stage,retryable:result.ok?false:compatibilityRetryable(stage,reason),...(result.ok?{lastSuccess:checkedAt,message:'兼容'}:{lastFailure:checkedAt,failureReason:reason,message:reason})};store.saveSourceHealth(health);return result;}));
  ipcMain.handle('source:exportAudit',trusted(async input=>{const{sourceId}=SourceIdRequestSchema.parse(input);const source=store.listSources().find(item=>item.id===sourceId);if(!source)throw new Error('Source no longer exists');const result=await sourceEngine.audit(sourceId);const chosen=await dialog.showSaveDialog({title:'导出来源审计报告',defaultPath:`Free-New-Desk-Audit-${source.name.replace(/[^a-z0-9\u4e00-\u9fff_-]/gi,'_')}-${new Date().toISOString().slice(0,10)}.json`,filters:[{name:'JSON',extensions:['json']}]});if(chosen.canceled||!chosen.filePath)return{canceled:true};await writeFile(chosen.filePath,JSON.stringify({appVersion:app.getVersion(),exportedAt:new Date().toISOString(),source:{id:source.id,name:source.name,kind:source.kind,trust:source.trust},result},null,2),'utf8');return{canceled:false,path:chosen.filePath};}));
  ipcMain.handle('source:health',(event)=>{requireLocalSender(event);return store.listSourceHealth();});
  ipcMain.handle('source:aggregateSearch',trusted(async input=>{const keyword=typeof input==='string'?input.trim():'';if(!keyword)throw new Error('Search keyword is required');return aggregateSearch(keyword);}));
  ipcMain.handle('source:cancelAggregateSearch',(event)=>{requireLocalSender(event);aggregateController?.abort(new DOMException('Canceled','AbortError'));aggregateController=undefined;return true;});

  ipcMain.handle('config:importText',trusted(async input=>{if(typeof input!=='string')throw new Error('Configuration text or URL must be a string');const trimmed=input.trim(),isUrl=/^https?:\/\//i.test(trimmed);if(isUrl){const host=new URL(trimmed).hostname.toLowerCase();let allowed:string[]=[];try{const parsed=JSON.parse(store.getSetting('security.allowedConfigHosts')??'[]') as unknown;if(Array.isArray(parsed))allowed=parsed.filter((item):item is string=>typeof item==='string');}catch{/* malformed allowlist is treated as empty */}if(!allowed.includes(host)){const options={type:'warning' as const,buttons:['取消','信任并导入'],defaultId:0,cancelId:0,title:'确认远程配置来源',message:`配置将从 ${host} 下载`,detail:'远程配置可能引用脚本、JAR 或外部播放地址。仅导入你信任的域名。'};const confirmation=mainWindow?await dialog.showMessageBox(mainWindow,options):await dialog.showMessageBox(options);if(confirmation.response!==1)throw new Error('已取消未信任域名的远程配置导入');allowed.push(host);store.setSetting('security.allowedConfigHosts',JSON.stringify([...new Set(allowed)]));}}const importedAt=new Date().toISOString(),importGroupId=randomUUID(),sourceLabel=isUrl?new URL(trimmed).hostname:'TVBox / FongMi 配置';const result=await importConfigInput(store,input,{importGroupId,sourceLabel,importedAt});recordImport(store,{kind:isUrl?'网络配置':'粘贴配置',name:sourceLabel,importedAt,count:result.sources.length+result.liveSources.length,groupId:importGroupId,...(isUrl?{source:trimmed}:{})});return result;}));
  ipcMain.handle('config:importFile',async event=>{requireLocalSender(event);const chosen=await dialog.showOpenDialog({title:'导入本地 TVBox / FongMi 配置',properties:['openFile'],filters:[{name:'配置文件',extensions:['json','txt']},{name:'所有文件',extensions:['*']}]});if(chosen.canceled||!chosen.filePaths[0])return{canceled:true};const filePath=chosen.filePaths[0];const bytes=await readFile(filePath);if(bytes.byteLength>8*1024*1024)throw new Error('配置文件超过 8 MB 限制');const importedAt=new Date().toISOString(),importGroupId=randomUUID(),sourceLabel=path.basename(filePath);const result=await importConfigInput(store,bytes.toString('utf8').replace(/^\uFEFF/,''),{importGroupId,sourceLabel,importedAt});recordImport(store,{kind:'本地配置',name:sourceLabel,source:filePath,importedAt,count:result.sources.length+result.liveSources.length,groupId:importGroupId});return{canceled:false,result,filePath};});
  ipcMain.handle('live:listSources',(event)=>{requireLocalSender(event);return store.listLiveSources().map(source=>({...source,...(source.logo?{logo:imageUrl(source.logo,'live:'+source.id)}:{})}));});
  ipcMain.handle('live:importFile',async event=>{requireLocalSender(event);const chosen=await dialog.showOpenDialog({title:'导入直播播放列表',properties:['openFile'],filters:[{name:'IPTV 播放列表',extensions:['m3u','m3u8','txt','json']},{name:'所有文件',extensions:['*']}]});if(chosen.canceled||!chosen.filePaths[0])return{canceled:true};const filePath=chosen.filePaths[0];const bytes=await readFile(filePath);if(bytes.byteLength>32*1024*1024)throw new Error('直播播放列表超过 32 MB 限制');const text=bytes.toString('utf8').replace(/^\uFEFF/,'');const groups=parseLivePlaylist(text);const channelCount=groups.reduce((sum,group)=>sum+group.channels.length,0);if(channelCount===0)throw new Error('文件中没有识别到 M3U/TXT/JSON 直播频道');const id=randomUUID(),importedAt=new Date().toISOString(),importGroupId=randomUUID();await mkdir(path.dirname(managedPlaylistPath(id)),{recursive:true});await writeFile(managedPlaylistPath(id),text,'utf8');const source:LiveSourceConfig={id,name:path.basename(filePath),endpoint:'fnd-local://'+id,enabled:true,origin:'local-file',sourceLabel:filePath,importedAt,importGroupId};store.saveLiveSource(source);liveGroupsCache.set(id,groups);const compatibility=[await checkLiveCompatibility(store,source)];log.info('live','local playlist imported',{sourceId:id,name:source.name,channelCount});recordImport(store,{kind:'本地直播',name:source.name,source:filePath,importedAt,count:channelCount,groupId:importGroupId});return{canceled:false,source,channelCount,compatibility};});
  ipcMain.handle('live:importUrl',trusted(async input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const url=String(value.url??'').trim();if(!/^https?:\/\//i.test(url))throw new Error('请输入有效的 HTTP(S) M3U/TXT/JSON 地址');const name=String(value.name??'').trim()||new URL(url).hostname;const epg=String(value.epg??'').trim();const userAgent=String(value.userAgent??'').trim();const headers=userAgent?{'User-Agent':userAgent}:undefined;const text=await fetchText(store,'live-import',url,headers);const groups=parseLivePlaylist(text);const channelCount=groups.reduce((sum,group)=>sum+group.channels.length,0);if(channelCount===0)throw new Error('网络地址没有返回可识别的直播频道');const id=randomUUID(),importedAt=new Date().toISOString(),importGroupId=randomUUID();const source:LiveSourceConfig={id,name,endpoint:url,enabled:true,origin:'remote-playlist',sourceLabel:url,importedAt,importGroupId,...(epg?{epg}:{}),...(headers?{headers}:{})};store.saveLiveSource(source);liveGroupsCache.set(id,groups);await cache?.put('live-playlists',id,Buffer.from(text),'text/plain',12*60*60*1000);const compatibility=[await checkLiveCompatibility(store,source)];log.info('live','remote playlist imported',{sourceId:id,name,channelCount});recordImport(store,{kind:'网络直播',name:source.name,source:url,importedAt,count:channelCount,groupId:importGroupId});return{source,channelCount,compatibility};}));
  ipcMain.handle('live:saveSource',trusted(async input=>{const source=LiveSourceConfigSchema.parse(input),previous=store.listLiveSources().find(item=>item.id===source.id);store.saveLiveSource({...source,...(source.logo&&images?{logo:images.original(source.logo)}:{})});if(!previous||previous.endpoint!==source.endpoint||JSON.stringify(previous.headers??{})!==JSON.stringify(source.headers??{})){liveGroupsCache.delete(source.id);clearLiveRouteCache(source.id);await cache?.clear('live-playlists');}return source;}));
  ipcMain.handle('live:removeSource',trusted(async input=>{const{sourceId}=SourceIdRequestSchema.parse(input);const source=store.listLiveSources().find(item=>item.id===sourceId);const removed=store.removeLiveSource(sourceId);liveGroupsCache.delete(sourceId);clearLiveRouteCache(sourceId);await cache?.clear('live-playlists');if(source?.endpoint.startsWith('fnd-local://'))await rm(managedPlaylistPath(sourceId),{force:true});return removed;}));
  ipcMain.handle('live:channels',trusted(async input=>{const{sourceId}=SourceIdRequestSchema.parse(input);const force=Boolean(input&&typeof input==='object'&&(input as {force?:unknown}).force===true);return loadLiveGroups(store,sourceId,force);}));
  ipcMain.handle('live:speedTest',trusted(async input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const sourceId=String(value.sourceId??''),channelId=String(value.channelId??'');if(!sourceId||!channelId)throw new Error('Invalid live channel request');return speedLive(await resolveLiveChannel(store,sourceId,channelId));}));
  ipcMain.handle('live:play',trusted(async input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const sourceId=String(value.sourceId??''),channelId=String(value.channelId??'');if(!sourceId||!channelId)throw new Error('Invalid live channel request');const routeIndex=typeof value.routeIndex==='number'&&Number.isInteger(value.routeIndex)?value.routeIndex:undefined;const allowFallback=value.allowFallback!==false;return playLive(await resolveLiveChannel(store,sourceId,channelId),log,sourceId,routeIndex,allowFallback);}));
  ipcMain.handle('live:favorites',(event)=>{requireLocalSender(event);return store.listLiveFavorites().map(item=>({...item,...(item.logo?{logo:imageUrl(item.logo,'live:'+item.liveSourceId)}:{})}));});
  ipcMain.handle('live:saveFavorite',(event,value:LiveFavorite)=>{requireLocalSender(event);if(!data)throw new Error('Data service unavailable');if(!value||typeof value.liveSourceId!=='string'||typeof value.channelId!=='string')throw new Error('Invalid live favorite');data.saveLiveFavorite({...value,urls:Array.isArray(value.urls)?value.urls.slice(0,16):[],createdAt:value.createdAt||new Date().toISOString()});return true;});
  ipcMain.handle('live:removeFavorite',(event,value:{liveSourceId:string;channelId:string})=>{requireLocalSender(event);if(!data)throw new Error('Data service unavailable');return data.removeLiveFavorite(value.liveSourceId,value.channelId);});
  ipcMain.handle('live:toggleFavorite',trusted(async input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const liveSourceId=String(value.liveSourceId??''),channelId=String(value.channelId??'');if(!liveSourceId||!channelId)throw new Error('Invalid favorite request');const channel=await resolveLiveChannel(store,liveSourceId,channelId);const existing=store.listLiveFavorites().some(item=>item.liveSourceId===liveSourceId&&item.channelId===channel.id);if(existing){store.removeLiveFavorite(liveSourceId,channel.id);return{favorite:false};}const favorite:LiveFavorite={liveSourceId,channelId:channel.id,channelName:channel.name,group:channel.group,url:channel.url,urls:liveUrls(channel),createdAt:new Date().toISOString(),...(channel.logo?{logo:images?.original(channel.logo)??channel.logo}:{}),...(channel.tvgId?{tvgId:channel.tvgId}:{})};store.saveLiveFavorite(favorite);return{favorite:true};}));


  ipcMain.handle('epg:refresh',trusted(async input=>{const{sourceId}=SourceIdRequestSchema.parse(input);return{count:await loadEpg(store,sourceId,true)};}));
  ipcMain.handle('epg:list',trusted(async input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const liveSourceId=String(value.liveSourceId??'');if(!liveSourceId)throw new Error('liveSourceId is required');let programs=store.listEpg(liveSourceId,typeof value.channelId==='string'?value.channelId:undefined);if(programs.length===0){await loadEpg(store,liveSourceId,false);programs=store.listEpg(liveSourceId,typeof value.channelId==='string'?value.channelId:undefined);}return programs;}));

  ipcMain.handle('playback:play',trusted(async input=>playResolved(store,PlaybackEpisodeRequestSchema.parse(input))));
  ipcMain.handle('playback:control',trusted(async input=>{const command=PlayerCommandSchema.parse(input);if(command.command==='screenshot')throw new Error('Use playback.screenshot so the application selects a safe path');return player.command(command);}));
  ipcMain.handle('playback:query',trusted(input=>{if(input!=='stats'&&input!=='tracks'&&input!=='load-status')throw new Error('Invalid player query');return player.query(input as PlayerQuery);}));
  ipcMain.handle('playback:smokeLoad',async event=>{requireLocalSender(event);if(process.env.FND_UI_SMOKE!=='1')throw new Error('UI smoke media load is disabled');const url=await createUiSmokeMedia();const started=performance.now();let acceptedMs=0;const result=await player.load({url,profile:'vod'},()=>{acceptedMs=performance.now()-started;});if(!result.ok)throw new Error(result.detail??'UI smoke media failed');const totalMs=performance.now()-started;recordPerformanceMetric('playerLoadAcceptedMs',acceptedMs);return{ok:true,acceptedMs,totalMs};});
  ipcMain.handle('playback:screenshot',async event=>{requireLocalSender(event);const dir=path.join(app.getPath('pictures'),'Free New Desk');await mkdir(dir,{recursive:true});const file=path.join(dir,`Screenshot-${new Date().toISOString().replace(/[:.]/g,'-')}.png`);await player.command({command:'screenshot',value:file});return{path:file};});

  ipcMain.handle('history:list',trusted(input=>store.listHistory(typeof input==='number'?input:20)));
  ipcMain.handle('history:updateProgress',trusted(input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const id=String(value.id??'');const position=Number(value.position??0),duration=Number(value.duration??0);if(!id||id.length>128||!Number.isFinite(position)||!Number.isFinite(duration))throw new Error('Invalid history progress');return store.updateHistoryProgress(id,position,duration);}));
  ipcMain.handle('history:remove',trusted(input=>{const id=String(input??'');if(!id||id.length>128)throw new Error('Invalid history id');return store.removeHistory(id);}));
  ipcMain.handle('history:clear',event=>{requireLocalSender(event);return store.clearHistory();});
  ipcMain.handle('reservation:list',(event)=>{requireLocalSender(event);return store.listReservations();});
  ipcMain.handle('reservation:save',trusted(input=>{if(!input||typeof input!=='object')throw new Error('Invalid reservation');const row=input as Partial<ProgramReservation>;const value:ProgramReservation={id:typeof row.id==='string'&&row.id?row.id:randomUUID(),liveSourceId:String(row.liveSourceId??''),channelId:String(row.channelId??''),channelName:String(row.channelName??''),programTitle:String(row.programTitle??''),start:String(row.start??''),createdAt:typeof row.createdAt==='string'&&row.createdAt?row.createdAt:new Date().toISOString()};if(!value.liveSourceId||!value.channelId||!value.programTitle||!value.start)throw new Error('Reservation fields are incomplete');const startMs=Date.parse(value.start);if(!Number.isFinite(startMs))throw new Error('Reservation start time is invalid');const conflict=store.listReservations().find(item=>item.id!==value.id&&Math.abs(Date.parse(item.start)-startMs)<30*60*1000);if(conflict)throw new Error(`预约时间冲突：${conflict.channelName} · ${conflict.programTitle}`);store.saveReservation(value);return value;}));
  ipcMain.handle('reservation:remove',trusted(input=>store.removeReservation(String(input??''))));

  ipcMain.handle('settings:list',(event)=>{requireLocalSender(event);return store.listSettings();});
  ipcMain.handle('settings:set',trusted(input=>{if(!input||typeof input!=='object')throw new Error('Invalid setting');const{key,value}=input as Record<string,unknown>;if(typeof key!=='string'||typeof value!=='string')throw new Error('Setting must be string');store.setSetting(key,value);if(key==='theme'&&(value==='system'||value==='light'||value==='dark'))nativeTheme.themeSource=value;if(key==='cache.maxBytes'&&cache)cache.setMaxBytes(Number(value));return true;}));
  ipcMain.handle('cache:stats',async event=>{requireLocalSender(event);return cache?.stats()??{bytes:0,files:0,maxBytes:0,namespaces:[]};});
  ipcMain.handle('cache:clear',trusted(async input=>{const namespace=typeof input==='string'&&input.trim()?input.trim():undefined;if(namespace&&!/^[a-z0-9_-]{1,64}$/i.test(namespace))throw new Error('Invalid cache namespace');await cache?.clear(namespace);return true;}));

  ipcMain.handle('diagnostics:get',async event=>{requireLocalSender(event);return collectDiagnostics(store);});
  ipcMain.handle('diagnostics:recordPerformance',trusted(input=>{const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>;const metric=typeof value.metric==='string'?value.metric:'';const duration=Number(value.value);recordPerformanceMetric(metric,duration);return true;}));
  ipcMain.handle('diagnostics:events',trusted(input=>recentDiagnosticEvents(log,typeof input==='number'?input:20)));
  ipcMain.handle('diagnostics:selfTestItem',trusted(input=>runSelfTestItem(store,log,typeof input==='number'?Math.trunc(input):-1)));
  ipcMain.handle('diagnostics:export',async event=>{requireLocalSender(event);return exportDiagnostics(store,log);});
  ipcMain.handle('maintenance:openPath',trusted(async input=>{if(typeof input!=='string'||(input!=='logs'&&input!=='temp'&&!/^cache:[a-z0-9_-]{1,64}$/i.test(input)))throw new Error('Invalid maintenance path');const target=input==='logs'?path.join(app.getPath('userData'),'logs'):input==='temp'?app.getPath('temp'):safeCacheNamespacePath(path.join(app.getPath('userData'),'cache'),input.slice(6));if(input!=='temp')await mkdir(target,{recursive:true});const error=await shell.openPath(target);return{path:target,...(error?{error}:{})};}));
  ipcMain.handle('update:check',trusted(async input=>{const channel:UpdateChannel=input==='daily'?'daily':'stable';const result=await checkRepoUpdate(channel);store.setSetting('update.channel',channel);store.setSetting('update.lastCheck',result.checkedAt);store.setSetting('update.lastResult',JSON.stringify(result));return result;}));
  ipcMain.handle('update:openReleases',(event)=>{requireLocalSender(event);void shell.openExternal('https://github.com/cwe88108/free-new-desk-public/releases');return true;});
}

const hasInstanceLock=app.requestSingleInstanceLock();
if(!hasInstanceLock){app.quit();}else{
app.on('second-instance',showMainWindow);
app.whenReady().then(async()=>{
  const userData=app.getPath('userData');const dataDir=path.join(userData,'data');mkdirSync(dataDir,{recursive:true});
  data=new DataService(path.join(dataDir,'app.db'));logger=new JsonLogger(path.join(userData,'logs'));installRuntimeGuards(data,logger);cache=new DiskCache(path.join(userData,'cache'),Number(data.getSetting('cache.maxBytes')??1024*1024*1024));await cache.init();images=new ImageService(cache,broker);
  protocol.handle('fnd-image',request=>images?.handle(request.url)??new Response('Image service unavailable',{status:503}));
  const proxyDescriptor=data.getSetting('network.proxyMode')==='direct'?undefined:await proxy.start();sourceEngine.start();await sourceEngine.configure(proxyDescriptor?{proxyBaseUrl:proxyDescriptor.baseUrl,proxyToken:proxyDescriptor.token}:{});await syncSources();registerIpc(data,logger);
  const savedTheme=data.getSetting('theme');if(savedTheme==='system'||savedTheme==='light'||savedTheme==='dark')nativeTheme.themeSource=savedTheme;
  const epgStore=data,epgLog=logger;void refreshConfiguredEpg(epgStore,epgLog);epgRefreshTimer=setInterval(()=>{void refreshConfiguredEpg(epgStore,epgLog);},6*60*60*1000);epgRefreshTimer.unref();void maybeAutoCheckUpdates(data,logger);updateCheckTimer=setInterval(()=>{if(data&&logger)void maybeAutoCheckUpdates(data,logger);},60*60*1000);updateCheckTimer.unref();
  logger.info('app','application ready',{version:app.getVersion(),arch:process.arch});createTray();createWindow();void player.query('stats').catch(()=>undefined);scheduleSourceHealth(logger);scheduleReservationNotifications(data,logger);app.on('activate',showMainWindow);
}).catch(error=>{logger?.fatal('app','startup failed',{detail:error instanceof Error?error.message:String(error)});quitting=true;app.quit();});
app.on('window-all-closed',()=>{if(process.platform==='darwin')return;});
app.on('before-quit',()=>{quitting=true;persistMainWindowBounds();data?.setSetting('lifecycle.cleanExit','true');aggregateController?.abort();if(epgRefreshTimer)clearInterval(epgRefreshTimer);if(updateCheckTimer)clearInterval(updateCheckTimer);if(sourceHealthTimer)clearInterval(sourceHealthTimer);if(reservationTimer)clearInterval(reservationTimer);tray?.destroy();tray=undefined;sourceEngine.stop();epgWorker.stop();player.stop();void proxy.stop();data?.close();});
}
