import { readMusicTags,type MusicTags } from './music-tags.js';
import { app,dialog,ipcMain,nativeImage,safeStorage,type IpcMainInvokeEvent } from 'electron';
import { createHash,randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { readFile,readdir,realpath,stat } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import type { MusicSource,MusicTrack } from '@free-new-desk/contracts';
import { MusicNetworkSourceRequestSchema,MusicPlayRequestSchema } from '@free-new-desk/contracts';
import { DataService } from '@free-new-desk/data-service';
import { parseCueSheet } from './music-cue.js';
import { localArtworkCandidates } from './music-artwork.js';
import { disconnectSmbConnections,ensureSmbConnection,musicRequestHeaders,scanWebDav,type MusicCredentials } from './music-network.js';
import { findOnlineArtwork,findOnlineLyrics } from './music-online.js';
import { getCurrentPlayerClient,getPlayerRuntimeSession } from './player-client.js';

const audioExtensions=new Set(['.mp3','.ape','.flac','.wav','.m4a','.alac','.aac','.ogg','.opus','.aiff','.aif','.dsf','.dff','.tta','.tak']);
const MAX_TRACKS=50_000;
const MAX_DISCOVERED_FILES=100_000;
const MAX_CUE_BYTES=2*1024*1024;
const MAX_ARTWORK_BYTES=8*1024*1024;
const MAX_LYRICS_BYTES=512*1024;
const scanControllers=new Map<string,AbortController>();
const transientCredentials=new Map<string,MusicCredentials>();
let store:DataService|undefined;
let registered=false;

function db():DataService{if(store)return store;const directory=path.join(app.getPath('userData'),'data');mkdirSync(directory,{recursive:true});store=new DataService(path.join(directory,'app.db'));return store;}
function requireLocalSender(event:IpcMainInvokeEvent):void{const sender=event.senderFrame?.url??'';if(!sender.startsWith('file://'))throw new Error('Untrusted IPC sender');}
function stableTrackId(sourceId:string,relativePath:string):string{return createHash('sha256').update(`${sourceId}\0${relativePath.replaceAll('\\','/')}`).digest('hex').slice(0,32);}
function relativeKey(value:string):string{const normalized=value.replaceAll('\\','/');return process.platform==='win32'?normalized.toLocaleLowerCase('en-US'):normalized;}
function pathKey(value:string):string{const normalized=path.normalize(value);return process.platform==='win32'?normalized.toLocaleLowerCase('en-US'):normalized;}
async function canonicalRoot(value:string):Promise<string>{const resolved=path.resolve(value);try{return await realpath(resolved);}catch{return resolved;}}
function basicTagsFromRelative(relative:string):Pick<MusicTrack,'title'|'artist'|'album'>{const normalized=relative.replaceAll('\\','/'),parts=normalized.split('/').filter(Boolean),file=parts.at(-1)??relative,stem=file.slice(0,Math.max(0,file.length-path.extname(file).length)),match=/^(.+?)\s+-\s+(.+)$/.exec(stem),title=(match?.[2]??stem).trim(),artist=(match?.[1]??(parts.length>=3?parts.at(-3):'')??'').trim(),album=(parts.length>=2?parts.at(-2):'')?.trim()??'';return{title,artist,album};}
async function firstExisting(paths:string[]):Promise<string|undefined>{for(const candidate of paths)try{const info=await stat(candidate);if(info.isFile())return candidate;}catch{/* optional sidecar */}return undefined;}
function throwIfAborted(signal:AbortSignal):void{if(signal.aborted)throw signal.reason instanceof Error?signal.reason:new DOMException('音乐扫描已取消','AbortError');}
function credentialSettingKey(ref:string):string{return`music.credential.${ref}`;}
function encodeCredential(credentials:MusicCredentials):string{if(!safeStorage.isEncryptionAvailable())throw new Error('Windows 安全凭据加密当前不可用，无法持久保存音乐来源密码');return safeStorage.encryptString(JSON.stringify(credentials)).toString('base64');}
function decodeCredential(value:string):MusicCredentials|undefined{try{if(!safeStorage.isEncryptionAvailable())return;const parsed=JSON.parse(safeStorage.decryptString(Buffer.from(value,'base64'))) as Record<string,unknown>;return{...(typeof parsed.username==='string'?{username:parsed.username}:{}),...(typeof parsed.password==='string'?{password:parsed.password}:{})};}catch{return;}}
function credentialsFor(source:MusicSource):MusicCredentials|undefined{const transient=transientCredentials.get(source.id);if(transient)return transient;if(!source.credentialRef)return;const saved=db().getSetting(credentialSettingKey(source.credentialRef));return saved?decodeCredential(saved):undefined;}
function saveCredentials(sourceId:string,credentials:MusicCredentials,remember:boolean):string|undefined{if(!credentials.username&&!credentials.password)return;transientCredentials.set(sourceId,credentials);if(!remember)return;const ref=randomUUID();db().setSetting(credentialSettingKey(ref),encodeCredential(credentials));return ref;}
function clearCredentials(source:MusicSource):void{transientCredentials.delete(source.id);if(source.credentialRef)db().setSetting(credentialSettingKey(source.credentialRef),'');}
function musicCacheRoot():string{return path.join(app.getPath('userData'),'cache','music-online');}
function trackIdentity(track:MusicTrack):string{return`${track.id}\0${track.path}\0${track.modifiedAt??track.etag??''}\0${track.cueStart??''}\0${track.cueEnd??''}`;}
function currentIdentity(track:MusicTrack):boolean{const latest=db().getMusicTrack(track.id);return Boolean(latest&&trackIdentity(latest)===trackIdentity(track));}
function segmentUrl(url:string,track:MusicTrack):string{if(track.cueStart===undefined&&track.cueEnd===undefined)return url;const start=Math.max(0,track.cueStart??0),end=track.cueEnd!==undefined&&track.cueEnd>start?String(track.cueEnd):'';return`${url}#fnd-segment=${start},${end}`;}

async function discoverFilesystem(root:string,signal:AbortSignal):Promise<{audio:string[];cues:string[];truncated:boolean}>{const audio:string[]=[],cues:string[]=[],pending=[root];let discovered=0;while(pending.length&&audio.length<MAX_TRACKS&&discovered<MAX_DISCOVERED_FILES){throwIfAborted(signal);const directory=pending.pop();if(!directory)break;let entries;try{entries=await readdir(directory,{withFileTypes:true});}catch(error){throw error;}for(const entry of entries){throwIfAborted(signal);discovered+=1;if(discovered>=MAX_DISCOVERED_FILES)break;const full=path.join(directory,entry.name);if(entry.isSymbolicLink())continue;if(entry.isDirectory()){if(!entry.name.startsWith('.'))pending.push(full);continue;}if(!entry.isFile())continue;const ext=path.extname(entry.name).toLowerCase();if(audioExtensions.has(ext))audio.push(full);else if(ext==='.cue')cues.push(full);if(audio.length>=MAX_TRACKS)break;}}return{audio,cues,truncated:audio.length>=MAX_TRACKS||discovered>=MAX_DISCOVERED_FILES};}
async function buildFilesystemTrack(source:MusicSource,root:string,full:string,relativePath:string,existing:Map<string,MusicTrack>,overrides:Partial<MusicTrack>={}):Promise<MusicTrack|undefined>{
  let info;try{info=await stat(full);}catch{return;}if(!info.isFile())return;
  const ext=path.extname(full).toLowerCase();if(!audioExtensions.has(ext))return;
  const modifiedAt=info.mtime.toISOString(),previous=existing.get(relativeKey(relativePath)),unchanged=Boolean(previous&&previous.size===info.size&&previous.modifiedAt===modifiedAt),base=basicTagsFromRelative(relativePath);
  const supplied=overrides.title!==undefined||overrides.artist!==undefined||overrides.album!==undefined?{title:overrides.title??'',artist:overrides.artist??'',album:overrides.album??''}:unchanged&&previous?{title:previous.title,artist:previous.artist,album:previous.album}:base;
  const embedded:MusicTags=unchanged?{}:await readMusicTags(full),title=embedded.title||supplied.title||base.title,artist=embedded.artist||supplied.artist||base.artist,album=embedded.album||supplied.album||base.album;
  const stem=full.slice(0,-ext.length),directoryName=path.dirname(full),lyricsCandidates=overrides.title?[path.join(directoryName,`${overrides.title}.lrc`),`${stem}.lrc`,`${stem}.LRC`]:[`${stem}.lrc`,`${stem}.LRC`];
  const [lyricsPath,cover]=await Promise.all([firstExisting(lyricsCandidates),firstExisting(localArtworkCandidates(full,{album,title}))]);
  return{id:stableTrackId(source.id,relativePath),sourceId:source.id,path:full,relativePath,title,artist,album,...((embedded.duration??previous?.duration)!==undefined?{duration:embedded.duration??previous!.duration!}:{}),format:ext.slice(1).toUpperCase(),size:info.size,modifiedAt,favorite:previous?.favorite??false,available:true,...(cover?{cover}:{}),...(lyricsPath?{lyricsPath}:{}),...overrides};
}
async function scanFilesystemSource(source:MusicSource,signal:AbortSignal,existing:Map<string,MusicTrack>,options:{disconnectSmbConflicts?:boolean}={}):Promise<{tracks:MusicTrack[];truncated:boolean}>{if(source.kind==='smb')await ensureSmbConnection(source.root,credentialsFor(source),{disconnectConflicts:options.disconnectSmbConflicts===true});const root=source.kind==='local'?await canonicalRoot(source.root):path.resolve(source.root);throwIfAborted(signal);const rootInfo=await stat(root).catch(()=>undefined);if(!rootInfo?.isDirectory())throw new Error('音乐来源当前不可访问；已保留上次扫描结果，不会清空离线曲目');const discovered=await discoverFilesystem(root,signal),tracks:MusicTrack[]=[],referenced=new Set<string>();
  for(const cueFile of discovered.cues){throwIfAborted(signal);const cueInfo=await stat(cueFile).catch(()=>undefined);if(!cueInfo?.isFile()||cueInfo.size>MAX_CUE_BYTES)continue;let specs;try{specs=parseCueSheet((await readFile(cueFile)).toString('utf8'),cueFile,root);}catch{continue;}const cueRelative=path.relative(root,cueFile).replaceAll('\\','/');for(const spec of specs){throwIfAborted(signal);const audioKey=pathKey(spec.audioFile);referenced.add(audioKey);const relative=`${cueRelative}#${String(spec.trackNumber).padStart(2,'0')}`,track=await buildFilesystemTrack(source,root,spec.audioFile,relative,existing,{title:spec.title,artist:spec.performer,album:spec.album,cueFile:spec.cueFile,cueTrack:spec.trackNumber,cueStart:spec.start,...(spec.end!==undefined?{cueEnd:spec.end}:{})});if(track)tracks.push(track);if(tracks.length>=MAX_TRACKS)break;}if(tracks.length>=MAX_TRACKS)break;}
  if(tracks.length<MAX_TRACKS)for(const full of discovered.audio){throwIfAborted(signal);if(referenced.has(pathKey(full)))continue;const relative=path.relative(root,full).replaceAll('\\','/'),track=await buildFilesystemTrack(source,root,full,relative,existing);if(track)tracks.push(track);if(tracks.length>=MAX_TRACKS)break;}
  return{tracks,truncated:discovered.truncated||tracks.length>=MAX_TRACKS};}
async function scanWebDavSource(source:MusicSource,signal:AbortSignal,existing:Map<string,MusicTrack>):Promise<{tracks:MusicTrack[];truncated:boolean}>{const remote=await scanWebDav(source.root,credentialsFor(source),signal,MAX_TRACKS,relative=>audioExtensions.has(path.posix.extname(relative).toLowerCase())),tracks:MusicTrack[]=[];for(const file of remote){const relative=file.relativePath.replaceAll('\\','/'),previous=existing.get(relativeKey(relative)),tags=previous&&previous.size===file.size&&previous.modifiedAt===file.modifiedAt&&previous.etag===file.etag?{title:previous.title,artist:previous.artist,album:previous.album}:basicTagsFromRelative(relative),ext=path.posix.extname(relative).toLowerCase();tracks.push({id:stableTrackId(source.id,relative),sourceId:source.id,path:file.url,relativePath:relative,title:tags.title,artist:tags.artist,album:tags.album,format:ext.slice(1).toUpperCase(),favorite:previous?.favorite??false,available:true,...(file.size!==undefined?{size:file.size}:{}),...(file.modifiedAt?{modifiedAt:file.modifiedAt}:{}),...(file.etag?{etag:file.etag}:{})});}return{tracks,truncated:tracks.length>=MAX_TRACKS};}
async function scanSource(sourceId:string,options:{disconnectSmbConflicts?:boolean}={}):Promise<{count:number;truncated:boolean;canceled?:boolean}>{const database=db(),source=database.listMusicSources().find(item=>item.id===sourceId);if(!source)throw new Error('音乐来源不存在');scanControllers.get(sourceId)?.abort(new DOMException('扫描已被新的扫描请求替代','AbortError'));const controller=new AbortController();scanControllers.set(sourceId,controller);database.saveMusicSource({...source,scanState:'scanning',message:'',updatedAt:new Date().toISOString()});try{const existing=new Map(database.listMusicTracks(sourceId,undefined,MAX_TRACKS).map(track=>[relativeKey(track.relativePath),track])),scanned=source.kind==='webdav'?await scanWebDavSource(source,controller.signal,existing):await scanFilesystemSource(source,controller.signal,existing,options);throwIfAborted(controller.signal);database.replaceMusicTracks(sourceId,scanned.tracks,!scanned.truncated);const message=scanned.truncated?'已达到音乐库安全扫描上限':undefined,now=new Date().toISOString();database.saveMusicSource({...source,lastScannedAt:now,scanState:'ready',updatedAt:now,...(message?{message}:{})});return{count:scanned.tracks.length,truncated:scanned.truncated};}catch(error){if(controller.signal.aborted||(error instanceof DOMException&&error.name==='AbortError')){if(scanControllers.get(sourceId)===controller&&database.listMusicSources().some(item=>item.id===sourceId))database.saveMusicSource({...source,scanState:'idle',message:'扫描已取消；保留上次完整扫描结果',updatedAt:new Date().toISOString()});return{count:database.listMusicTracks(sourceId,undefined,MAX_TRACKS).length,truncated:false,canceled:true};}const message=error instanceof Error?error.message:String(error);database.saveMusicSource({...source,scanState:'error',message,updatedAt:new Date().toISOString()});throw error;}finally{if(scanControllers.get(sourceId)===controller)scanControllers.delete(sourceId);}}

function imageDataUrl(bytes:Buffer|Uint8Array):string|undefined{const image=nativeImage.createFromBuffer(Buffer.from(bytes));if(image.isEmpty())return;const size=image.getSize(),scale=Math.min(1,1024/Math.max(size.width,size.height,1)),normalized=scale<1?image.resize({width:Math.max(1,Math.round(size.width*scale)),height:Math.max(1,Math.round(size.height*scale))}):image;return normalized.toDataURL();}
async function readArtwork(track:MusicTrack,allowOnline=true):Promise<string|undefined>{if(!/^https?:/i.test(track.path)){const embedded=await readMusicTags(track.path,true);if(embedded.picture){const value=imageDataUrl(embedded.picture);if(value)return value;}}if(track.cover)try{const info=await stat(track.cover);if(info.isFile()&&info.size<=MAX_ARTWORK_BYTES){const value=imageDataUrl(await readFile(track.cover));if(value)return value;}}catch{/* fall through to online provider */}if(!allowOnline)return;const online=await findOnlineArtwork(track,musicCacheRoot()).catch(()=>undefined);if(!online||!currentIdentity(track))return;return imageDataUrl(online.bytes);}
async function readLyrics(track:MusicTrack):Promise<string>{const online=await findOnlineLyrics(track,musicCacheRoot()).catch(()=>undefined);if(online&&currentIdentity(track)&&online.text.trim())return online.text;if(track.lyricsPath)try{const info=await stat(track.lyricsPath);if(info.isFile()&&info.size<=MAX_LYRICS_BYTES)return(await readFile(track.lyricsPath)).toString('utf8').replace(/^\uFEFF/,'');}catch{/* online-first fallback exhausted */}return'';}
async function addNetworkSource(input:unknown):Promise<{source:MusicSource;count:number;truncated:boolean}>{const request=MusicNetworkSourceRequestSchema.parse(input),database=db(),now=new Date().toISOString(),id=randomUUID(),root=request.kind==='webdav'?(()=>{const url=new URL(request.root);if(url.protocol!=='http:'&&url.protocol!=='https:')throw new Error('WebDAV 地址必须使用 http:// 或 https://');if(!url.pathname.endsWith('/'))url.pathname+='/';return url.toString();})():request.root.replaceAll('/','\\'),credentials:MusicCredentials={...(request.username?{username:request.username}:{}),...(request.password?{password:request.password}:{})},credentialRef=saveCredentials(id,credentials,request.rememberCredential===true),source:MusicSource={id,name:request.name.trim(),kind:request.kind,root,enabled:true,createdAt:now,updatedAt:now,scanState:'idle',...(credentialRef?{credentialRef}:{})};database.saveMusicSource(source);try{const result=await scanSource(id,{disconnectSmbConflicts:request.disconnectConflicts===true});return{source:database.listMusicSources().find(item=>item.id===id)??source,count:result.count,truncated:result.truncated};}catch(error){database.removeMusicSource(id);clearCredentials(source);throw error;}}

export function registerMusicIpc():void{if(registered)return;registered=true;
  ipcMain.handle('music:listSources',event=>{requireLocalSender(event);return db().listMusicSources();});
  ipcMain.handle('music:addLocalSource',async event=>{requireLocalSender(event);const selected=await dialog.showOpenDialog({title:'添加本地音乐文件夹',properties:['openDirectory']});const selectedRoot=selected.filePaths[0];if(selected.canceled||!selectedRoot)return{canceled:true};const root=await canonicalRoot(selectedRoot),database=db(),duplicate=database.listMusicSources().find(item=>item.kind==='local'&&pathKey(item.root)===pathKey(root));if(duplicate){const scanned=await scanSource(duplicate.id);return{canceled:false,duplicate:true,source:database.listMusicSources().find(item=>item.id===duplicate.id)??duplicate,...scanned};}const now=new Date().toISOString(),source:MusicSource={id:randomUUID(),name:path.basename(root)||root,kind:'local',root,enabled:true,createdAt:now,updatedAt:now,scanState:'idle'};database.saveMusicSource(source);const scanned=await scanSource(source.id);return{canceled:false,source:database.listMusicSources().find(item=>item.id===source.id)??source,...scanned};});
  ipcMain.handle('music:addNetworkSource',async(event,input)=>{requireLocalSender(event);return addNetworkSource(input);});
  ipcMain.handle('music:scan',async(event,input)=>{requireLocalSender(event);const sourceId=String((input as{sourceId?:unknown}|undefined)?.sourceId??'');if(!sourceId)throw new Error('缺少音乐来源');return scanSource(sourceId);});
  ipcMain.handle('music:cancelScan',(event,input)=>{requireLocalSender(event);const sourceId=String((input as{sourceId?:unknown}|undefined)?.sourceId??'');if(!sourceId)throw new Error('缺少音乐来源');const controller=scanControllers.get(sourceId);if(!controller)return false;controller.abort(new DOMException('用户取消音乐扫描','AbortError'));return true;});
  ipcMain.handle('music:removeSource',(event,input)=>{requireLocalSender(event);const sourceId=String((input as{sourceId?:unknown}|undefined)?.sourceId??'');if(!sourceId)throw new Error('缺少音乐来源');const source=db().listMusicSources().find(item=>item.id===sourceId);scanControllers.get(sourceId)?.abort(new DOMException('音乐来源已删除','AbortError'));scanControllers.delete(sourceId);if(source)clearCredentials(source);return db().removeMusicSource(sourceId);});
  ipcMain.handle('music:listTracks',(event,input)=>{requireLocalSender(event);const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>,sourceId=typeof value.sourceId==='string'&&value.sourceId?value.sourceId:undefined,query=typeof value.query==='string'?value.query:undefined,limit=Number.isFinite(Number(value.limit))?Math.min(MAX_TRACKS,Math.max(1,Number(value.limit))):5000;return db().listMusicTracks(sourceId,query,limit);});
  ipcMain.handle('music:toggleFavorite',(event,input)=>{requireLocalSender(event);const trackId=String((input as{trackId?:unknown}|undefined)?.trackId??'');if(!trackId)throw new Error('缺少曲目');return db().toggleMusicFavorite(trackId);});
  ipcMain.handle('music:artwork',async(event,input)=>{requireLocalSender(event);const value=(input&&typeof input==='object'?input:{}) as Record<string,unknown>,track=db().getMusicTrack(String(value.trackId??'')),allowOnline=value.online!==false;return track?readArtwork(track,allowOnline):undefined;});
  ipcMain.handle('music:lyrics',async(event,input)=>{requireLocalSender(event);const track=db().getMusicTrack(String((input as{trackId?:unknown}|undefined)?.trackId??''));return track?readLyrics(track):'';});
  ipcMain.handle('music:capabilities',event=>{requireLocalSender(event);return{local:{scan:true,incrementalReuse:true,cancel:true,offlineRetention:true,pathDeduplication:true,lyrics:'sidecar-lrc+online',artwork:'embedded+folder+online'},webdav:{implemented:true,scan:'PROPFIND',playback:'native-http-range',credentials:'safeStorage'},smb:{implemented:true,scan:'UNC',playback:'UNC',credentials:'Windows-session+safeStorage'},onlineLyrics:{implemented:true,provider:'LRCLIB',scoredMatch:true,cache:true},onlineArtwork:{implemented:true,provider:'iTunes Search',scoredMatch:true,cache:true},cue:{implemented:true,singleFile:true,multiFile:true,boundedSegments:true},dsdNative:{implemented:false,pcmFallback:true,reason:'原生 DSD/DoP 必须由真实 DAC/驱动能力验证，源码不伪报'}};});
  ipcMain.handle('music:play',async(event,input)=>{requireLocalSender(event);const request=MusicPlayRequestSchema.parse(input),track=db().getMusicTrack(request.trackId);if(!track||!track.available)throw new Error('曲目不存在或当前不可用');const source=db().listMusicSources().find(item=>item.id===track.sourceId);if(!source)throw new Error('音乐来源不存在');let url:string,headers:Record<string,string>|undefined;if(source.kind==='webdav'){url=track.path;headers=musicRequestHeaders(credentialsFor(source));}else{if(source.kind==='smb')await ensureSmbConnection(source.root,credentialsFor(source));const exists=await stat(track.path).catch(()=>undefined);if(!exists?.isFile())throw new Error('音乐文件当前不可访问；来源可能离线，请重新扫描后重试');url=pathToFileURL(track.path).href;}const player=getCurrentPlayerClient();if(!player)throw new Error('PlayerHost 尚未初始化');await player.command({command:'window-sync',x:0,y:0,width:1,height:1,scale:1,visible:false}).catch(()=>undefined);const result=await player.load({url:segmentUrl(url,track),profile:'music',...(headers&&Object.keys(headers).length?{headers}:{})},undefined,{initiator:request.initiator??'user',sourceId:track.sourceId,trackId:track.id});return{...result,track,session:getPlayerRuntimeSession()};});
  app.once('before-quit',()=>{for(const controller of scanControllers.values())controller.abort(new DOMException('应用退出','AbortError'));scanControllers.clear();transientCredentials.clear();void disconnectSmbConnections();try{store?.close();}catch{/* main process owns shutdown ordering */}store=undefined;});
}

registerMusicIpc();
