import type { PlayResult,SourceKind } from '@free-new-desk/contracts';
import { mergeHeaders,RequestBroker } from '@free-new-desk/source-sdk';
import type { SniffingService } from './sniffing-service.js';
const MEDIA_URL=/\.(?:m3u8|mp4|m4v|flv|mpd|ts|mkv|webm|aac|m4a)(?:[?#]|$)/i;
const DIRECT_PROTOCOL=/^(?:rtmp|rtsp|udp):/i;
const PROVIDER_FLAG=/^(?:qq|qiyi|iqiyi|youku|mgtv|bilibili|pptv|sohu)$/i;
const MEDIA_TYPE=/^(?:video\/|audio\/|application\/(?:vnd\.apple\.mpegurl|x-mpegurl|dash\+xml))/i;
const NON_MEDIA_TYPE=/^(?:text\/html|application\/(?:json|problem\+json)|text\/(?:plain|json))/i;
export type PlaybackMode='direct'|'sniff'|'parser';
export interface PlaybackResolution{url:string;headers:Record<string,string>;mode:PlaybackMode;contentType?:string|undefined;httpStatus?:number|undefined;inputHost?:string|undefined;finalHost?:string|undefined;fallbackAttempted:boolean;}
export interface PlaybackResolveInput{sourceId:string;sourceKind:SourceKind;flag:string;resolved:PlayResult;sourceHeaders?:Record<string,string>|undefined;playUrl?:string|undefined;playerType?:number|undefined;forceSniff?:boolean|undefined;}
export function isLikelyMediaUrl(value:string):boolean{return MEDIA_URL.test(value);}
export function isMediaContentType(value:string):boolean{return MEDIA_TYPE.test(value.trim());}
export function isClearlyNonMediaContentType(value:string):boolean{return NON_MEDIA_TYPE.test(value.trim());}
export function shouldRetryPlayerFailure(detail:string|undefined):boolean{return /(?:unrecognized file format|mpv\s*-17|\(-17\))/i.test(detail??'');}
function host(value:string):string|undefined{try{return new URL(value).host;}catch{return undefined;}}
function parserTarget(playUrl:string,inputUrl:string):string{const raw=playUrl.trim();if(raw.includes('{url}'))return raw.replaceAll('{url}',encodeURIComponent(inputUrl));return raw+encodeURIComponent(inputUrl);}
export class PlaybackResolver{constructor(private readonly broker:RequestBroker,private readonly sniffing:SniffingService){}
  async #probe(sourceId:string,url:string,headers:Record<string,string>):Promise<{url:string;status:number;contentType:string}>{let response:Response|undefined;try{response=await this.broker.request({sourceId,url,method:'HEAD',headers,timeoutMs:6_000,retries:0});if(response.status===405||response.status===403){await response.body?.cancel();response=undefined;}}catch{/* range fallback */}if(!response)response=await this.broker.request({sourceId,url,headers:{...headers,Range:'bytes=0-65535'},timeoutMs:7_000,retries:0});const finalUrl=response.url||url,status=response.status,contentType=response.headers.get('content-type')??'';await response.body?.cancel();return{url:finalUrl,status,contentType};}
  async #sniff(input:PlaybackResolveInput,url:string,headers:Record<string,string>,mode:PlaybackMode):Promise<PlaybackResolution>{if(!/^https?:\/\//i.test(url))throw new Error('[PLAY_DIRECT_INVALID] 解析目标不是 HTTP(S) 地址');const found=await this.sniffing.resolve(input.sourceId,url,headers);return{url:found.url,headers:mergeHeaders(headers,found.headers),mode,inputHost:host(input.resolved.url),finalHost:host(found.url),fallbackAttempted:Boolean(input.forceSniff)};}
  async #playUrl(input:PlaybackResolveInput,headers:Record<string,string>):Promise<PlaybackResolution|null>{const playUrl=input.playUrl?.trim();if(!playUrl)return null;if(/^json:/i.test(playUrl)){const endpoint=parserTarget(playUrl.slice(5),input.resolved.url);const response=await this.broker.request({sourceId:input.sourceId,url:endpoint,headers,timeoutMs:10_000,retries:0});const contentType=response.headers.get('content-type')??'';const body=await response.text();if(!response.ok)throw new Error(`[PLAY_PARSER_FAILED] Parser HTTP ${response.status}`);try{const json=JSON.parse(body) as Record<string,unknown>;const url=typeof json.url==='string'?json.url:'';const extra=(json.header&&typeof json.header==='object'&&!Array.isArray(json.header)?json.header:json.headers&&typeof json.headers==='object'&&!Array.isArray(json.headers)?json.headers:{}) as Record<string,string>;if(url)return{url,headers:mergeHeaders(headers,extra),mode:'parser',contentType,httpStatus:response.status,inputHost:host(input.resolved.url),finalHost:host(url),fallbackAttempted:Boolean(input.forceSniff)};}catch{/* parser response may be a page */}throw new Error('[PLAY_PARSER_FAILED] JSON parser did not return a media URL');}if(/^https?:\/\//i.test(playUrl))return this.#sniff(input,parserTarget(playUrl,input.resolved.url),headers,'parser');return null;}
  async resolve(input:PlaybackResolveInput):Promise<PlaybackResolution>{const url=input.resolved.url.trim();if(!url)throw new Error('[PLAY_DIRECT_INVALID] 播放地址为空');const headers=mergeHeaders(input.sourceHeaders,input.resolved.headers,input.resolved.userAgent?{'User-Agent':input.resolved.userAgent}:undefined,input.resolved.referer?{Referer:input.resolved.referer}:undefined);if(DIRECT_PROTOCOL.test(url))return{url,headers,mode:'direct',inputHost:host(url),finalHost:host(url),fallbackAttempted:Boolean(input.forceSniff)};if(!/^https?:\/\//i.test(url))throw new Error('[PLAY_PARSER_FAILED] 来源返回了无法直接解析的非 HTTP 播放标识');if(!input.forceSniff&&isLikelyMediaUrl(url))return{url,headers,mode:'direct',inputHost:host(url),finalHost:host(url),fallbackAttempted:false};if(!input.forceSniff&&input.playUrl){const parsed=await this.#playUrl(input,headers);if(parsed)return parsed;}let probe:{url:string;status:number;contentType:string}|undefined;try{probe=await this.#probe(input.sourceId,url,headers);}catch{/* inaccessible probe still may work in browser sniff */}if(!input.forceSniff&&probe?.status&&probe.status>=200&&probe.status<400&&isMediaContentType(probe.contentType))return{url:probe.url,headers,mode:'direct',contentType:probe.contentType,httpStatus:probe.status,inputHost:host(url),finalHost:host(probe.url),fallbackAttempted:false};const shouldSniff=Boolean(input.forceSniff||input.resolved.parse||PROVIDER_FLAG.test(input.flag)||isClearlyNonMediaContentType(probe?.contentType??'')||!probe?.contentType||input.playerType!==undefined);if(shouldSniff)return this.#sniff(input,probe?.url??url,headers,input.playUrl?'parser':'sniff');return this.#sniff(input,probe?.url??url,headers,'sniff');}
}
