import { BrowserWindow } from 'electron';
import { createHash,randomUUID } from 'node:crypto';
const MEDIA=/\.(?:m3u8|mp4|m4v|flv|mpd|ts|mkv|webm|aac|m4a)(?:[?#]|$)/i;
const KEEP_HEADERS=new Set(['user-agent','referer','origin','cookie']);
export interface SniffedMedia{url:string;headers?:Record<string,string>;}
function selectHeaders(input:Record<string,string>):Record<string,string>{const output:Record<string,string>={};for(const[key,value]of Object.entries(input))if(KEEP_HEADERS.has(key.toLowerCase()))output[key]=value;return output;}
export class SniffingService {
  async resolve(sourceId:string,pageUrl:string,headers:Record<string,string>={},timeoutMs=12_000):Promise<SniffedMedia>{const sourceHash=createHash('sha256').update(sourceId).digest('hex').slice(0,12);const partition=`sniff_${sourceHash}_${randomUUID()}`;const window=new BrowserWindow({show:false,width:800,height:600,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true,partition}});return new Promise<SniffedMedia>((resolve,reject)=>{let settled=false;const finish=(error:Error|null,value?:SniffedMedia)=>{if(settled)return;settled=true;clearTimeout(timer);if(!window.isDestroyed())window.destroy();if(error)reject(error);else resolve(value as SniffedMedia);};const timer=setTimeout(()=>finish(new Error('[PLAY_SNIFF_TIMEOUT] Media sniffing timed out')),timeoutMs);window.webContents.session.webRequest.onBeforeSendHeaders({urls:['http://*/*','https://*/*']},(details,callback)=>{if(MEDIA.test(details.url)&&details.url!==pageUrl){const captured=selectHeaders(details.requestHeaders as Record<string,string>);finish(null,{url:details.url,...(Object.keys(captured).length?{headers:captured}:{})});}callback({requestHeaders:details.requestHeaders});});window.webContents.once('did-fail-load',(_event,code,description)=>{if(!settled&&code!==-3)finish(new Error(`[PLAY_PARSER_FAILED] Sniff page failed: ${description}`));});const extraHeaders=Object.entries(headers).map(([key,value])=>`${key}: ${value}`).join('\n');void window.loadURL(pageUrl,extraHeaders?{extraHeaders}:undefined).catch(error=>finish(error instanceof Error?error:new Error(String(error))));});}
}
