import vm from 'node:vm';
import { randomUUID } from 'node:crypto';
import type { PluginSourceModule } from '@free-new-desk/plugin-sdk';
type JsonRecord=Record<string,unknown>;interface Pending {resolve:(value:unknown)=>void;reject:(error:Error)=>void;timer:NodeJS.Timeout;}
let plugin:PluginSourceModule|undefined;let sourceId='';let pluginId='';let config:unknown;const storage=new Map<string,string>();const broker=new Map<string,Pending>();const send=(message:unknown)=>{if(process.send)process.send(message);};
function request(url:string,options:JsonRecord={}):Promise<unknown>{const id=randomUUID();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{broker.delete(id);reject(new Error('Plugin network request timeout'));},15_000);broker.set(id,{resolve,reject,timer});send({type:'broker.request',id,url,options});});}
function load(code:string):PluginSourceModule {const module={exports:{}} as {exports:PluginSourceModule};const safeConsole={log:(...args:unknown[])=>send({type:'log',level:'info',args:args.map(String).slice(0,8)}),warn:(...args:unknown[])=>send({type:'log',level:'warn',args:args.map(String).slice(0,8)}),error:(...args:unknown[])=>send({type:'log',level:'error',args:args.map(String).slice(0,8)})};const context=vm.createContext({module,exports:module.exports,console:safeConsole,URL,URLSearchParams,TextEncoder,TextDecoder,setTimeout,clearTimeout,host:Object.freeze({request,storage:Object.freeze({get:(key:string)=>storage.get(String(key))??'',set:(key:string,value:string)=>{storage.set(String(key),String(value));return true;},delete:(key:string)=>storage.delete(String(key))})})});new vm.Script(`"use strict";\n${code}\n;globalThis.__plugin=module.exports;`,{filename:`plugin-${pluginId||'unknown'}.js`}).runInContext(context,{timeout:2_000});const value=(context as unknown as {__plugin?:PluginSourceModule}).__plugin;if(!value||typeof value!=='object')throw new Error('Plugin entry must assign module.exports');return value;}
async function call(method:keyof PluginSourceModule,args:unknown[]):Promise<unknown>{if(!plugin)throw new Error('Plugin is not initialized');const fn=plugin[method];if(typeof fn!=='function')throw new Error(`Plugin method not implemented: ${String(method)}`);return Promise.race([Promise.resolve((fn as (...values:unknown[])=>unknown)(...args)),new Promise((_,reject)=>setTimeout(()=>reject(new Error(`Plugin method timeout: ${String(method)}`)),12_000))]);}
process.on('message',(message:unknown)=>{void (async()=>{if(!message||typeof message!=='object')return;const data=message as JsonRecord;if(data.type==='broker.response'){const id=String(data.id??'');const pending=broker.get(id);if(!pending)return;clearTimeout(pending.timer);broker.delete(id);if(data.error)pending.reject(new Error(String(data.error)));else pending.resolve(data.result);return;}const id=String(data.id??'');try{if(data.type==='init'){sourceId=String(data.sourceId??'');pluginId=String(data.pluginId??'');config=data.config;storage.clear();plugin=load(String(data.code??''));if(typeof plugin.init==='function')await call('init',[{sourceId,pluginId,config}]);send({type:'response',id,result:{ok:true}});return;}if(data.type==='call'){const method=String(data.method??'') as keyof PluginSourceModule;const result=await call(method,Array.isArray(data.args)?data.args:[]);send({type:'response',id,result});return;}if(data.type==='destroy'){if(plugin&&typeof plugin.destroy==='function')await call('destroy',[]);plugin=undefined;storage.clear();send({type:'response',id,result:{ok:true}});return;}throw new Error('Unsupported plugin-host message');}catch(error){send({type:'response',id,error:error instanceof Error?error.message:String(error)});}})();});process.on('disconnect',()=>process.exit(0));
