<script setup lang="ts">
import { computed,onMounted,ref } from 'vue';
import { useRouter } from 'vue-router';
import type { DetailResult,LiveFavorite,ProgramReservation } from '@free-new-desk/contracts';
import { listVodFavorites,removeVodFavorite,saveVodFavorites,type VodFavorite } from '../favorites';

const router=useRouter();
type Tab='all'|'vod'|'live'|'reservation';
const items=ref<VodFavorite[]>([]);const liveItems=ref<LiveFavorite[]>([]);const reservations=ref<ProgramReservation[]>([]);const availableSources=ref(new Set<string>());const sourceNames=ref(new Map<string,string>());const detail=ref<DetailResult|null>(null);const detailSource=ref('');const error=ref('');const tab=ref<Tab>('all');const query=ref('');const sourceFilter=ref('all');const sort=ref<'newest'|'name'>('newest');const viewMode=ref<'grid'|'list'>(localStorage.getItem('favorites.viewMode')==='list'?'list':'grid');const bulk=ref(false);const selected=ref(new Set<string>());
const visibleVod=computed(()=>items.value.filter(item=>(tab.value==='all'||tab.value==='vod')&&(item.label??item.name).toLowerCase().includes(query.value.trim().toLowerCase())&&(sourceFilter.value==='all'||item.sourceId===sourceFilter.value)).sort((a,b)=>sort.value==='name'?(a.label??a.name).localeCompare(b.label??b.name):b.createdAt.localeCompare(a.createdAt)));
const visibleLive=computed(()=>liveItems.value.filter(item=>(tab.value==='all'||tab.value==='live')&&item.channelName.toLowerCase().includes(query.value.trim().toLowerCase())&&(sourceFilter.value==='all'||item.liveSourceId===sourceFilter.value)).sort((a,b)=>sort.value==='name'?a.channelName.localeCompare(b.channelName):b.createdAt.localeCompare(a.createdAt)));
const visibleReservations=computed(()=>reservations.value.filter(item=>(tab.value==='all'||tab.value==='reservation')&&(item.programTitle+' '+item.channelName).toLowerCase().includes(query.value.trim().toLowerCase())));
const total=computed(()=>items.value.length+liveItems.value.length+reservations.value.length);
function setViewMode(mode:'grid'|'list'){viewMode.value=mode;localStorage.setItem('favorites.viewMode',mode);}
function checkSources(){const unhealthy=items.value.filter(item=>!availableSources.value.has(item.sourceId)).map(item=>item.sourceId);if(!unhealthy.length){error.value='所有收藏的来源当前都可用。';return;}error.value='';const params=new URLSearchParams([['filter','unhealthy'],['source',unhealthy[0]!]]);void router.push(`/sources?${params.toString()}`);}
function key(item:VodFavorite){return item.sourceId+'\u0000'+item.videoId;}
async function reload(){const [vod,live,reserved,sources]=await Promise.all([listVodFavorites(),window.desktop.live.favorites(),window.desktop.reservation.list(),window.desktop.source.list().catch(()=>[])]);items.value=vod;liveItems.value=live;reservations.value=reserved;availableSources.value=new Set(sources.map(item=>item.id));sourceNames.value=new Map(sources.map(item=>[item.id,item.name]));}
async function open(item:VodFavorite){error.value='';try{detailSource.value=item.sourceId;detail.value=await window.desktop.source.detail(item.sourceId,[item.videoId]);}catch(value){detail.value=null;error.value='来源不可用：'+(value instanceof Error?value.message:String(value));}}
async function remove(item:VodFavorite){await removeVodFavorite(item.sourceId,item.videoId);if(detailSource.value===item.sourceId&&detail.value?.id===item.videoId)detail.value=null;await reload();}
async function play(flag:string,id:string,name:string){if(!detail.value)return;try{await window.desktop.playback.play({sourceId:detailSource.value,videoId:detail.value.id,videoName:detail.value.name,flag,episodeId:id,episodeName:name});}catch(value){error.value=value instanceof Error?value.message:String(value);}}
async function playLive(item:LiveFavorite){try{await window.desktop.live.play({sourceId:item.liveSourceId,channelId:item.channelId,allowFallback:true});}catch(value){error.value=value instanceof Error?value.message:String(value);}}
async function removeLive(item:LiveFavorite){await window.desktop.live.toggleFavorite(item.liveSourceId,item.channelId);await reload();}
function toggleSelection(value:string){const next=new Set(selected.value);next.has(value)?next.delete(value):next.add(value);selected.value=next;}function toggleSelected(item:VodFavorite){toggleSelection('vod:'+key(item));}
async function removeSelected(){if(!selected.value.size||!window.confirm(`确认删除选中的 ${selected.value.size} 项？`))return;await saveVodFavorites(items.value.filter(item=>!selected.value.has('vod:'+key(item))));for(const item of liveItems.value)if(selected.value.has('live:'+item.liveSourceId+'\u0000'+item.channelId))await window.desktop.live.removeFavorite(item.liveSourceId,item.channelId);for(const item of reservations.value)if(selected.value.has('reservation:'+item.id))await window.desktop.reservation.remove(item.id);selected.value=new Set();await reload();}
async function rename(item:VodFavorite){const value=window.prompt('输入收藏显示名称',item.label??item.name)?.trim();if(!value)return;await saveVodFavorites(items.value.map(current=>key(current)===key(item)?{...current,label:value}:current));await reload();}
function exportFavorites(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),vod:items.value,live:liveItems.value},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='Free-New-Desk-Favorites.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importFavorites(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()) as {vod?:VodFavorite[];live?:LiveFavorite[]};if(!Array.isArray(parsed.vod)&&!Array.isArray(parsed.live))throw new Error('收藏文件缺少 vod/live 数组');if(Array.isArray(parsed.vod))await saveVodFavorites([...(parsed.vod??[]),...items.value]);if(Array.isArray(parsed.live))for(const favorite of parsed.live.slice(0,5000))await window.desktop.live.saveFavorite(favorite);await reload();error.value='';}catch(value){error.value='导入失败：'+(value instanceof Error?value.message:String(value));}}
onMounted(reload);
</script>

<template>
  <section class="page favorites-page">
    <div class="page-heading split"><div><h1>收藏</h1><p>点播、直播与节目预约统一管理，数据仅保存在本机。</p></div><span class="count-label">{{total}} 项</span></div>
    <div class="favorites-toolbar"><div class="segmented"><button v-for="value in (['all','vod','live','reservation'] as Tab[])" :key="value" :class="{active:tab===value}" @click="tab=value">{{({all:'全部',vod:'点播',live:'直播',reservation:'预约'} as Record<Tab,string>)[value]}}</button></div><input v-model="query" maxlength="100" placeholder="搜索收藏" aria-label="搜索收藏" data-search-input/><select v-model="sourceFilter" aria-label="按来源筛选收藏"><option value="all">全部来源</option><option v-for="[id,name] in sourceNames" :key="id" :value="id">{{name}}</option></select><select v-model="sort" aria-label="收藏排序"><option value="newest">按收藏时间</option><option value="name">按名称</option></select><span class="view-toggle"><button :class="{active:viewMode==='grid'}" title="网格" @click="setViewMode('grid')">▦</button><button :class="{active:viewMode==='list'}" title="列表" @click="setViewMode('list')">☷</button></span><button class="secondary-button" @click="bulk=!bulk">{{bulk?'完成':'批量管理'}}</button><button v-if="bulk" class="secondary-button" :disabled="!selected.size" @click="removeSelected">删除选中</button><button class="secondary-button" @click="checkSources">检查来源</button><button class="text-link" @click="exportFavorites">导出 JSON</button><label class="text-link import-label">导入 JSON<input type="file" accept=".json,application/json" @change="importFavorites"/></label></div>
    <p v-if="error" class="error-banner">{{error}}</p>
    <div v-if="!visibleVod.length&&!visibleLive.length&&!visibleReservations.length" class="empty-state"><div class="empty-icon">☆</div><h3>当前分类暂无收藏</h3><p>可在点播、搜索或直播页添加。</p></div>
    <div v-else class="favorites-workspace"><div>
      <div v-if="visibleVod.length" :class="viewMode==='grid'?'poster-grid cinematic':'favorites-list-view'"><article v-for="item in visibleVod" :key="key(item)" class="favorite-card"><label v-if="bulk" class="bulk-check"><input type="checkbox" :checked="selected.has('vod:'+key(item))" @change="toggleSelected(item)"/>选择</label><button class="poster-card" :class="{selected:detailSource===item.sourceId&&detail?.id===item.videoId,list:viewMode==='list'}" @dblclick="open(item)" @click="bulk?toggleSelected(item):open(item)"><div class="poster-art"><img v-if="item.poster" :src="item.poster" :alt="(item.label??item.name)+' 海报'" loading="lazy"/><div v-else class="poster-placeholder">▶</div><span class="poster-badge">{{item.sourceName}}</span></div><div class="poster-copy"><strong>{{item.label??item.name}}</strong><small>{{item.remark}}</small><small v-if="!availableSources.has(item.sourceId)" class="error-text">来源不可用（收藏已保留）</small></div></button><div class="row-actions"><button class="text-link" @click="rename(item)">重命名</button><button class="remove-favorite" @click="remove(item)">取消收藏</button></div></article></div>
      <div v-if="visibleLive.length" class="favorite-list"><article v-for="item in visibleLive" :key="item.liveSourceId+item.channelId"><label v-if="bulk"><input type="checkbox" :checked="selected.has('live:'+item.liveSourceId+'\u0000'+item.channelId)" @change="toggleSelection('live:'+item.liveSourceId+'\u0000'+item.channelId)"/>选择</label><div><strong>{{item.channelName}}</strong><small>{{item.group}} · 直播频道</small></div><button @click="playLive(item)">播放</button><button @click="removeLive(item)">取消收藏</button></article></div>
      <div v-if="visibleReservations.length" class="favorite-list"><article v-for="item in visibleReservations" :key="item.id"><label v-if="bulk"><input type="checkbox" :checked="selected.has('reservation:'+item.id)" @change="toggleSelection('reservation:'+item.id)"/>选择</label><div><strong>{{item.programTitle}}</strong><small>{{item.channelName}} · {{new Date(item.start).toLocaleString()}}</small></div><RouterLink to="/settings">管理预约</RouterLink></article></div>
    </div><aside class="detail-rail"><template v-if="detail"><img v-if="detail.poster" class="detail-poster" :src="detail.poster" :alt="detail.name+' 海报'"/><h2>{{detail.name}}</h2><p>{{detail.description||'该来源未提供简介。'}}</p><div class="episode-heading"><strong>剧集</strong><span>{{detail.episodes.length}}</span></div><div class="episode-grid"><button v-for="(episode,index) in detail.episodes" :key="episode.flag+episode.id" @click="play(episode.flag,episode.id,episode.name)">{{index+1}}</button></div></template><div v-else class="detail-empty"><span>☆</span><h3>选择一个点播收藏</h3><p>详情和剧集会显示在这里。</p></div></aside></div>
  </section>
</template>

<style scoped>
.favorites-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.favorites-toolbar>input{min-width:180px}.import-label{cursor:pointer}.import-label input{display:none}.bulk-check{display:flex;gap:5px;align-items:center}.favorite-list{display:grid;gap:8px;margin:0 0 14px}.favorite-list article{display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:10px}.favorite-list strong,.favorite-list small{display:block}.favorite-list small{color:var(--muted)}
.view-toggle{display:flex;gap:3px}.view-toggle button{min-width:32px;height:30px;border:1px solid var(--line);background:var(--surface);border-radius:6px}.view-toggle button.active{background:var(--accent-soft);color:var(--accent)}.favorites-list-view{display:flex;flex-direction:column;gap:7px}.favorite-card .poster-card.list{display:grid;grid-template-columns:70px 1fr;align-items:center;text-align:left;gap:12px;padding:7px;width:100%}.favorite-card .poster-copy{min-width:0}.favorite-card .poster-copy small{display:block;color:var(--muted);margin-top:4px}
</style>
