<script setup lang="ts">
import { computed,nextTick,onBeforeUnmount,onMounted,ref } from 'vue';
import { onBeforeRouteLeave,useRouter } from 'vue-router';
import type { EpgProgram,LiveChannel,LiveFavorite,LiveGroup,LiveRouteSpeed,LiveSourceConfig,PlayerTrack } from '@free-new-desk/contracts';
import { createNativeSurfaceLease,type NativeSurfaceLease } from '../native-surface';
import { emitPlaybackStage } from '../playback-events';
import { usePageStateStore } from '../stores/page-state';
const router=useRouter();const pageState=usePageStateStore();
const systemTimeZone=Intl.DateTimeFormat().resolvedOptions().timeZone||'系统时区';
const epgTimeZone=ref(localStorage.getItem('live.epgTimeZone')||'system');
const timeZoneOptions=[{value:'system',label:`系统时区`},{value:'UTC',label:'UTC'},{value:'Asia/Shanghai',label:'Asia/Shanghai'},{value:'Asia/Tokyo',label:'Asia/Tokyo'},{value:'Asia/Hong_Kong',label:'Asia/Hong_Kong'},{value:'America/New_York',label:'America/New_York'},{value:'Europe/London',label:'Europe/London'}];
function timeZoneLabel(value:string){if(value==='system')return systemTimeZone;const offset=-new Date().getTimezoneOffset();const probe=new Intl.DateTimeFormat('en-US',{timeZone:value,timeZoneName:'shortOffset'}).formatToParts(new Date()).find(part=>part.type==='timeZoneName');return `${value}${probe?`（${probe.value}）`:''}`;}
function zoneTime(value:string|number|Date,options:Intl.DateTimeFormatOptions){return new Date(value).toLocaleTimeString([],{...options,...(epgTimeZone.value==='system'?{}:{timeZone:epgTimeZone.value})});}
function setTimeZone(event:Event){epgTimeZone.value=(event.target as HTMLSelectElement).value;localStorage.setItem('live.epgTimeZone',epgTimeZone.value);}
const subtitleTracks=ref<PlayerTrack[]>([]);const switchReasons=ref<string[]>([]);
const channelInput=ref('');const channelQuery=ref('');const channelSort=ref<'default'|'name'|'number'|'custom'>('default');const customOrder=ref<string[]>([]);const listScrollTop=ref(0);const visibleLimit=ref(200);const autoSpeed=ref(false);const previewMuted=ref(false);const previewFullscreen=ref(false);const programDetail=ref<EpgProgram|null>(null);const sources=ref<LiveSourceConfig[]>([]);const sourceId=ref('');const groups=ref<LiveGroup[]>([]);const groupName=ref('');const selected=ref<LiveChannel|null>(null);const epg=ref<EpgProgram[]>([]);const allEpg=ref<EpgProgram[]>([]);const favorites=ref<LiveFavorite[]>([]);const speeds=ref<LiveRouteSpeed[]>([]);const showFavorites=ref(false);const loading=ref(false);const speedLoading=ref(false);const error=ref('');const playStatus=ref('');const fallbackEnabled=ref(true);const previewSurface=ref<HTMLElement|null>(null);const previewActive=ref(false);const activeRoute=ref<number|null>(null);const epgUpdatedAt=ref('');let reconnectAttempts=0;let previewRaf=0;let previewLease:NativeSurfaceLease|undefined;let liveSearchTimer:ReturnType<typeof setTimeout>|undefined;let liveMonitorTimer:ReturnType<typeof setInterval>|undefined;let speedTimer:ReturnType<typeof setInterval>|undefined;
const enabledSources=computed(()=>sources.value.filter(item=>item.enabled));const currentSource=computed(()=>sources.value.find(item=>item.id===sourceId.value));const favoriteKeys=computed(()=>new Set(favorites.value.map(item=>item.liveSourceId+'\u0000'+item.channelId)));const allChannels=computed(()=>groups.value.find(group=>group.name===groupName.value)?.channels??groups.value.flatMap(group=>group.channels));const channels=computed(()=>{const term=channelQuery.value.trim().toLowerCase();let values=(showFavorites.value?allChannels.value.filter(channel=>favoriteKeys.value.has(sourceId.value+'\u0000'+channel.id)):allChannels.value).filter(channel=>!term||channel.name.toLowerCase().includes(term)||channel.group.toLowerCase().includes(term));if(channelSort.value==='name')values=[...values].sort((a,b)=>a.name.localeCompare(b.name));if(channelSort.value==='number')values=[...values].sort((a,b)=>(Number(a.id.match(/\d+/)?.[0])||999999)-(Number(b.id.match(/\d+/)?.[0])||999999));if(channelSort.value==='custom')values=[...values].sort((a,b)=>{const ai=customOrder.value.indexOf(a.id),bi=customOrder.value.indexOf(b.id);return(ai<0?999999:ai)-(bi<0?999999:bi);});return values.slice(0,visibleLimit.value);});const virtualStart=computed(()=>Math.max(0,Math.floor(listScrollTop.value/76)-4));const virtualChannels=computed(()=>channels.value.slice(virtualStart.value,virtualStart.value+18));const virtualTop=computed(()=>virtualStart.value*76);const virtualBottom=computed(()=>Math.max(0,(channels.value.length-virtualStart.value-virtualChannels.value.length)*76));const routeCount=(channel:LiveChannel)=>new Set([channel.url,...(channel.urls??[])]).size;const isFavorite=(channel:LiveChannel)=>favoriteKeys.value.has(sourceId.value+'\u0000'+channel.id);const nowProgram=computed(()=>{const now=Date.now();return epg.value.find(item=>new Date(item.start).getTime()<=now&&new Date(item.stop).getTime()>now)??epg.value[0];});const upcoming=computed(()=>{const current=nowProgram.value;return epg.value.filter(item=>item!==current).slice(0,8);});const rankedSpeeds=computed(()=>[...speeds.value].sort((a,b)=>Number(!a.ok)-Number(!b.ok)||(a.latencyMs||Number.MAX_SAFE_INTEGER)-(b.latencyMs||Number.MAX_SAFE_INTEGER)||a.index-b.index));const epgState=computed(()=>!currentSource.value?.epg?'未配置 EPG':epgUpdatedAt.value?'EPG 已更新':'EPG 已配置');
interface LiveSession{groupName?:string;channelId?:string;routeIndex?:number|null;channelSort?:typeof channelSort.value;showFavorites?:boolean;}
interface LivePageSnapshot{sources:LiveSourceConfig[];sourceId:string;groups:LiveGroup[];groupName:string;selected:LiveChannel|null;epg:EpgProgram[];allEpg:EpgProgram[];favorites:LiveFavorite[];speeds:LiveRouteSpeed[];showFavorites:boolean;activeRoute:number|null;epgUpdatedAt:string;channelSort:'default'|'name'|'number'|'custom';customOrder:string[];}
function liveSessionKey(id=sourceId.value){return`live.session.${id}`;}
function readLiveSession(id:string):LiveSession{try{const value=JSON.parse(localStorage.getItem(liveSessionKey(id))??'{}') as LiveSession;return value&&typeof value==='object'?value:{};}catch{return{};}}
function saveLiveSession(extra:Partial<LiveSession>={}){if(!sourceId.value)return;localStorage.setItem('live.sourceId',sourceId.value);localStorage.setItem(liveSessionKey(),JSON.stringify({groupName:groupName.value,channelId:selected.value?.id,routeIndex:activeRoute.value,channelSort:channelSort.value,showFavorites:showFavorites.value,...extra}));}
function updateLiveView(){visibleLimit.value=200;listScrollTop.value=0;saveLiveSession();}
function scheduleChannelSearch(){if(liveSearchTimer)clearTimeout(liveSearchTimer);liveSearchTimer=setTimeout(()=>{channelQuery.value=channelInput.value;listScrollTop.value=0;},200);}function onChannelScroll(event:Event){listScrollTop.value=(event.currentTarget as HTMLElement).scrollTop;}function startChannelDrag(channel:LiveChannel){if(channelSort.value==='custom')draggedChannel.value=channel.id;}function dropChannel(channel:LiveChannel){if(channelSort.value!=='custom'||!draggedChannel.value||draggedChannel.value===channel.id)return;const ids=[...customOrder.value,...allChannels.value.map(item=>item.id).filter(id=>!customOrder.value.includes(id))];const from=ids.indexOf(draggedChannel.value),to=ids.indexOf(channel.id);if(from>=0&&to>=0){ids.splice(from,1);ids.splice(to,0,draggedChannel.value);customOrder.value=ids;localStorage.setItem('live.channelOrder.'+sourceId.value,JSON.stringify(ids));}draggedChannel.value='';}
const draggedChannel=ref('');
function originLabel(source:LiveSourceConfig|undefined){if(source?.origin==='local-file')return'本地播放列表';if(source?.origin==='remote-playlist')return'网络播放列表';if(source?.origin==='tvbox')return'TVBox / FongMi';return'直播来源';}
function channelProgram(channel:LiveChannel):EpgProgram|undefined{const now=Date.now();const ids=new Set([channel.tvgId,channel.id,channel.name].filter((item):item is string=>Boolean(item)));return allEpg.value.find(item=>ids.has(item.channelId)&&new Date(item.start).getTime()<=now&&new Date(item.stop).getTime()>now);}
function programTime(program:EpgProgram|undefined){return program?`${zoneTime(program.start,{hour:'2-digit',minute:'2-digit'})}–${zoneTime(program.stop,{hour:'2-digit',minute:'2-digit'})}`:'';}
async function loadFavorites(){favorites.value=await window.desktop.live.favorites();}
async function loadSources(){[sources.value]=await Promise.all([window.desktop.live.listSources(),loadFavorites()]);const saved=localStorage.getItem('live.sourceId')??'';if(!sourceId.value)sourceId.value=enabledSources.value.some(item=>item.id===saved)?saved:enabledSources.value[0]?.id??'';if(sourceId.value)await loadChannels(false);}
async function loadEpgOverview(){if(!sourceId.value)return;const [programsResult,settingsResult]=await Promise.allSettled([window.desktop.epg.list(sourceId.value),window.desktop.settings.list()]);allEpg.value=programsResult.status==='fulfilled'?programsResult.value:[];if(settingsResult.status==='fulfilled'){const value=settingsResult.value['epg.lastRefresh.'+sourceId.value];epgUpdatedAt.value=value?new Date(value).toLocaleString():'';}}
async function loadChannels(force=false){if(!sourceId.value)return;localStorage.setItem('live.sourceId',sourceId.value);const saved=readLiveSession(sourceId.value);try{const value=JSON.parse(localStorage.getItem('live.channelOrder.'+sourceId.value)??'[]') as unknown;customOrder.value=Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];}catch{customOrder.value=[];}loading.value=true;error.value='';selected.value=null;epg.value=[];allEpg.value=[];speeds.value=[];visibleLimit.value=200;try{groups.value=await window.desktop.live.channels(sourceId.value,force);groupName.value=groups.value.some(item=>item.name===saved.groupName)?saved.groupName!:groups.value[0]?.name??'';channelSort.value=saved.channelSort??'default';showFavorites.value=Boolean(saved.showFavorites);await loadEpgOverview();const restored=groups.value.flatMap(group=>group.channels).find(item=>item.id===saved.channelId);if(restored)await choose(restored,false);activeRoute.value=saved.routeIndex??null;saveLiveSession();}catch(value){error.value=value instanceof Error?value.message:String(value);groups.value=[];}finally{loading.value=false;}}
async function changeLiveSource(){await loadChannels(false);}
async function refreshPlaylist(){await loadChannels(true);}
async function choose(channel:LiveChannel,persist=true){selected.value=channel;error.value='';playStatus.value='';speeds.value=[];if(!previewActive.value)activeRoute.value=null;if(persist)saveLiveSession({channelId:channel.id});const ids=new Set([channel.tvgId,channel.id,channel.name].filter((item):item is string=>Boolean(item)));const local=allEpg.value.filter(item=>ids.has(item.channelId));if(local.length){epg.value=local;return;}try{epg.value=await window.desktop.epg.list(sourceId.value,channel.tvgId??channel.name);}catch(value){error.value=value instanceof Error?value.message:String(value);}}
async function syncPreview(visible=true){const element=previewSurface.value;if(!visible){if(previewLease){await previewLease.release();previewLease=undefined;}return;}if(!element)return;const rect=element.getBoundingClientRect();if(rect.width<1||rect.height<1)return;previewLease??=createNativeSurfaceLease('live-preview');try{await previewLease.sync({x:Math.round(rect.left),y:Math.round(rect.top),width:Math.max(1,Math.round(rect.width)),height:Math.max(1,Math.round(rect.height))},true);}catch(value){error.value=value instanceof Error?value.message:String(value);}}
function schedulePreview(){if(!previewActive.value||previewRaf)return;previewRaf=requestAnimationFrame(()=>{previewRaf=0;void syncPreview(true);});}
async function play(channel:LiveChannel,routeIndex?:number,openPlayer=false){error.value='';playStatus.value=routeIndex===undefined?'正在连接最近可用线路…':'正在连接指定线路…';if(openPlayer){previewActive.value=false;await syncPreview(false);await router.push('/player');emitPlaybackStage('connecting',`正在连接直播频道「${channel.name}」…`);}try{const result=await window.desktop.live.play({sourceId:sourceId.value,channelId:channel.id,...(routeIndex===undefined?{}:{routeIndex}),allowFallback:fallbackEnabled.value});if(!result.ok)throw new Error(result.detail??'播放失败');reconnectAttempts=0;activeRoute.value=result.routeIndex;saveLiveSession({channelId:channel.id,routeIndex:result.routeIndex});switchReasons.value=(result.attempts??[]).filter(item=>!item.ok).map(item=>`线路 ${item.index+1} 失败：${item.detail??'未知原因'}`);playStatus.value='线路 '+(result.routeIndex+1)+'/'+result.routeCount+' 已连接'+(switchReasons.value.length?`（回退 ${switchReasons.value.length} 次后接入）`:'');if(openPlayer){emitPlaybackStage('playing',`直播频道「${channel.name}」已连接`);return;}previewActive.value=true;await nextTick();schedulePreview();}catch(value){playStatus.value='';const message=value instanceof Error?value.message:String(value);error.value=message;if(openPlayer)emitPlaybackStage('failed','直播播放失败',message);}}
async function openPlayer(){if(!selected.value)return;const channel=selected.value;const navigationStarted=performance.now();previewActive.value=false;await syncPreview(false);await router.push('/player');const navigationMs=performance.now()-navigationStarted;void window.desktop.diagnostics.recordPerformance('playbackNavigationMs',navigationMs).catch(()=>false);if(window.desktop.app.isUiSmoke()&&navigationMs>150)throw new Error(`Playback navigation exceeded 150ms budget: ${navigationMs.toFixed(1)}ms`);emitPlaybackStage('connecting',`正在连接直播频道「${channel.name}」…`);void window.desktop.live.play({sourceId:sourceId.value,channelId:channel.id,...(activeRoute.value===null?{}:{routeIndex:activeRoute.value}),allowFallback:fallbackEnabled.value}).then(result=>{activeRoute.value=result.routeIndex;saveLiveSession({channelId:channel.id,routeIndex:result.routeIndex});emitPlaybackStage('playing',`直播频道「${channel.name}」已连接`);}).catch(value=>{const message=value instanceof Error?value.message:String(value);emitPlaybackStage('failed','直播播放失败',message);});}
async function testSpeed(channel:LiveChannel){speedLoading.value=true;error.value='';try{speeds.value=await window.desktop.live.speedTest(sourceId.value,channel.id);}catch(value){error.value=value instanceof Error?value.message:String(value);}finally{speedLoading.value=false;}}
async function toggleFavorite(channel:LiveChannel){await window.desktop.live.toggleFavorite(sourceId.value,channel.id);await loadFavorites();}
async function refreshEpg(){if(!sourceId.value)return;error.value='';try{await window.desktop.epg.refresh(sourceId.value);await loadEpgOverview();if(selected.value)await choose(selected.value);}catch(value){error.value=value instanceof Error?value.message:String(value);}}
const reservationDraft=ref<EpgProgram|null>(null);function openReservation(program:EpgProgram){reservationDraft.value=program;}async function confirmReservation(){const program=reservationDraft.value;if(!program||!selected.value)return;await window.desktop.reservation.save({liveSourceId:sourceId.value,channelId:selected.value.tvgId??selected.value.id,channelName:selected.value.name,programTitle:program.title,start:program.start});reservationDraft.value=null;}
async function togglePreviewMute(){previewMuted.value=!previewMuted.value;await window.desktop.playback.control({command:'mute',value:previewMuted.value});}
async function togglePreviewFullscreen(){previewFullscreen.value=!previewFullscreen.value;await window.desktop.playback.control({command:'fullscreen',value:previewFullscreen.value});}
async function monitorLive(){if(!previewActive.value||!selected.value)return;try{const [stats,trackList]=await Promise.all([window.desktop.playback.query('stats'),window.desktop.playback.query('tracks').catch(()=>[])]);reconnectAttempts=0;if(trackList.length)subtitleTracks.value=trackList.filter(track=>track.type==='sub');}catch{if(reconnectAttempts>=3){error.value='直播流已断开，自动重连 3 次仍失败。';previewActive.value=false;return;}reconnectAttempts+=1;playStatus.value=`直播流中断，正在第 ${reconnectAttempts}/3 次自动重连…`;await play(selected.value,activeRoute.value??undefined,false);}}
async function selectSubtitleTrack(event:Event){await window.desktop.playback.control({command:'subtitle-track',value:(event.target as HTMLSelectElement).value});}
function configureAutoSpeed(){if(speedTimer)clearInterval(speedTimer);speedTimer=undefined;if(autoSpeed.value)speedTimer=setInterval(()=>{if(selected.value)void testSpeed(selected.value);},60_000);}
function dialogEscape(event:KeyboardEvent){if(event.key!=='Escape')return;programDetail.value=null;reservationDraft.value=null;}
function onViewport(){schedulePreview();}
onMounted(async()=>{window.addEventListener('resize',onViewport);window.addEventListener('scroll',onViewport,true);window.addEventListener('keydown',dialogEscape);try{fallbackEnabled.value=(await window.desktop.settings.list())['live.autoFallback']!=='false';}catch{/* keep default */}const cached=pageState.read<LivePageSnapshot>('live');if(cached){const v=cached.value;sources.value=v.sources;sourceId.value=v.sourceId;groups.value=v.groups;groupName.value=v.groupName;selected.value=v.selected;epg.value=v.epg;allEpg.value=v.allEpg;favorites.value=v.favorites;speeds.value=v.speeds;showFavorites.value=v.showFavorites;activeRoute.value=v.activeRoute;epgUpdatedAt.value=v.epgUpdatedAt;channelSort.value=v.channelSort;customOrder.value=v.customOrder;previewActive.value=false;}else void loadSources();liveMonitorTimer=setInterval(()=>{void monitorLive();},5000);});
onBeforeRouteLeave(async()=>{const started=performance.now();previewActive.value=false;await syncPreview(false);const elapsed=performance.now()-started;void window.desktop.diagnostics.recordPerformance('surfaceHideMs',elapsed).catch(()=>false);if(window.desktop.app.isUiSmoke()&&elapsed>200)throw new Error(`Live native surface hide exceeded 200ms: ${elapsed.toFixed(1)}ms`);});
onBeforeUnmount(()=>{pageState.save<LivePageSnapshot>('live',{sources:[...sources.value],sourceId:sourceId.value,groups:[...groups.value],groupName:groupName.value,selected:selected.value,epg:[...epg.value],allEpg:[...allEpg.value],favorites:[...favorites.value],speeds:[...speeds.value],showFavorites:showFavorites.value,activeRoute:activeRoute.value,epgUpdatedAt:epgUpdatedAt.value,channelSort:channelSort.value,customOrder:[...customOrder.value]});window.removeEventListener('resize',onViewport);window.removeEventListener('scroll',onViewport,true);window.removeEventListener('keydown',dialogEscape);if(previewRaf)cancelAnimationFrame(previewRaf);if(liveSearchTimer)clearTimeout(liveSearchTimer);if(speedTimer)clearInterval(speedTimer);if(liveMonitorTimer)clearInterval(liveMonitorTimer);void syncPreview(false);});
</script>

<template>
  <section class="page live-page">
    <div class="page-heading split"><div><h1>直播 / Live TV</h1><p>按播放列表管理频道 · 自动优选线路 · XMLTV EPG</p></div><div class="toolbar-group"><select v-model="sourceId" @change="changeLiveSource"><option disabled value="">选择直播源</option><option v-for="source in enabledSources" :key="source.id" :value="source.id">{{source.name}}</option></select><button class="secondary-button" :disabled="loading||!sourceId" @click="refreshPlaylist">刷新播放列表</button><button class="secondary-button" @click="refreshEpg">刷新 EPG</button><RouterLink class="secondary-button" to="/sources">管理来源</RouterLink></div></div>
    <nav v-if="enabledSources.length" class="live-source-switcher" aria-label="切换直播源"><button v-for="source in enabledSources" :key="source.id" :class="{active:source.id===sourceId}" @click="sourceId=source.id;changeLiveSource()"><span>{{source.name}}</span><small>{{originLabel(source)}}</small></button></nav>
    <div v-if="currentSource" class="live-source-strip"><span>{{originLabel(currentSource)}}</span><strong>{{currentSource.name}}</strong><small>{{currentSource.sourceLabel||currentSource.endpoint}}</small><b class="epg-state" :class="{ok:Boolean(currentSource.epg)}">{{epgState}}</b><em v-if="epgUpdatedAt">{{epgUpdatedAt}}</em><label class="fallback-toggle"><input v-model="fallbackEnabled" type="checkbox"/>线路失败自动回退</label></div>
    <p v-if="error" class="error-banner">{{error}}</p><p v-if="playStatus" class="status-line">{{playStatus}}</p>
    <div v-if="!sourceId" class="empty-state"><h3>没有已启用直播源</h3><p>在“来源”页直接导入 M3U/M3U8/TXT/JSON 文件或网络播放列表。</p></div>
    <div v-else-if="loading" class="loading-panel">正在加载直播列表…</div>
    <div v-else class="live-console">
      <aside class="channel-pane panel">
        <div class="pane-heading"><div><span class="panel-kicker">频道列表</span><strong>共 {{allChannels.length}} 个频道</strong></div><button class="icon-button" @click="showFavorites=!showFavorites">{{showFavorites?'★':'☆'}}</button></div>
        <div class="channel-search-tools"><input v-model="channelInput" maxlength="100" placeholder="搜索频道" aria-label="搜索直播频道" @input="scheduleChannelSearch"/><select v-model="channelSort" aria-label="频道排序" @change="updateLiveView"><option value="default">默认排序</option><option value="name">按名称</option><option value="number">按编号</option><option value="custom">自定义排序</option></select></div><div class="channel-tabs"><button :class="{active:!showFavorites}" @click="showFavorites=false;updateLiveView()">全部</button><button :class="{active:showFavorites}" @click="showFavorites=true;updateLiveView()">收藏</button><select v-model="groupName" @change="updateLiveView"><option v-for="group in groups" :key="group.name" :value="group.name">{{group.name}}</option></select></div>
        <div class="channel-list refined virtual-channel-list" @scroll="onChannelScroll"><div :style="{height:virtualTop+'px'}"/><div v-for="channel in virtualChannels" :key="channel.id" class="channel-row" :class="{active:selected?.id===channel.id}" role="button" tabindex="0" :draggable="channelSort==='custom'" @dragstart="startChannelDrag(channel)" @dragover.prevent @drop="dropChannel(channel)" @click="choose(channel)" @dblclick="play(channel)" @keydown.enter="choose(channel)"><div class="channel-logo"><img v-if="channel.logo" :src="channel.logo" :alt="channel.name+' 台标'"/><span v-else>{{channel.name.slice(0,2)}}</span></div><span class="channel-copy"><strong>{{channel.name}}</strong><small><i class="channel-badge">#{{channels.indexOf(channel)+1}}</i><i class="channel-badge">{{channel.group}}</i><i v-if="routeCount(channel)>1" class="channel-badge">{{routeCount(channel)}} 线路</i></small><small v-if="channelProgram(channel)" class="now-line"><b>{{programTime(channelProgram(channel))}}</b> {{channelProgram(channel)?.title}}</small><small v-else>暂无当前节目单</small></span><button class="favorite-dot" :aria-label="isFavorite(channel)?'取消收藏':'收藏频道'" @click.stop="toggleFavorite(channel)">{{isFavorite(channel)?'★':'☆'}}</button></div><div :style="{height:virtualBottom+'px'}"/><button v-if="channels.length<allChannels.length" class="text-link wide" @click="visibleLimit+=200">加载更多频道</button><div v-if="channels.length===0" class="compact-empty">当前没有频道。</div></div>
      </aside>

      <section class="epg-pane panel">
        <div class="pane-heading"><div><span class="panel-kicker">节目单（EPG）</span><strong>时区：{{timeZoneLabel(epgTimeZone)}}</strong><small>{{epgState}}{{epgUpdatedAt?' · '+epgUpdatedAt:''}}</small></div><select v-model="epgTimeZone" aria-label="EPG 显示时区" @change="setTimeZone"><option v-for="option in timeZoneOptions" :key="option.value" :value="option.value">{{option.value==='system'?option.label+`（${systemTimeZone}）`:option.label}}</option></select><button class="secondary-button" @click="refreshEpg">立即更新</button></div>
        <div v-if="selected&&nowProgram" class="now-program"><span class="timeline-dot"/><div><small>正在播放</small><h2>{{nowProgram.title}}</h2><p>{{new Date(nowProgram.start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}} — {{new Date(nowProgram.stop).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}}</p><p v-if="nowProgram.description">{{nowProgram.description}}</p><button class="text-link" @click="programDetail=nowProgram">节目详情</button></div><button class="secondary-button" @click="play(selected)">页内播放</button></div>
        <div class="program-list"><div v-for="program in upcoming" :key="program.start+program.title" class="program-row"><time>{{zoneTime(program.start,{hour:'2-digit',minute:'2-digit'})}}</time><div><strong>{{program.title}}</strong><small>{{zoneTime(program.start,{hour:'2-digit',minute:'2-digit'})}} - {{zoneTime(program.stop,{hour:'2-digit',minute:'2-digit'})}}</small><p v-if="program.description">{{program.description}}</p><button class="text-link" @click="programDetail=program">节目详情</button></div><button :disabled="!currentSource?.epg" @click="openReservation(program)">预约</button></div><div v-if="selected&&epg.length===0" class="compact-empty">暂无匹配节目单。</div><div v-if="!selected" class="detail-empty"><span>◉</span><h3>选择频道查看节目单</h3></div></div>
      </section>

      <aside class="live-info panel">
        <template v-if="selected"><div class="pane-heading"><div><span class="panel-kicker">频道信息</span><h2>{{selected.name}}</h2></div><button class="icon-button" @click="toggleFavorite(selected)">{{isFavorite(selected)?'★':'☆'}}</button></div><div ref="previewSurface" class="live-preview native-live-preview"><div v-if="!previewActive" class="preview-center"><span>LIVE</span><strong>{{selected.name}}</strong><small>点击下方按钮在此区域预览</small></div></div><div class="preview-controls"><button @click="togglePreviewMute">{{previewMuted?'取消静音':'静音'}}</button><button @click="togglePreviewFullscreen">{{previewFullscreen?'退出全屏':'全屏'}}</button><select v-if="subtitleTracks.length" aria-label="直播字幕轨" @change="selectSubtitleTrack($event)"><option value="auto">字幕：自动</option><option value="no">字幕：关闭</option><option v-for="track in subtitleTracks" :key="track.id" :value="track.id">{{track.title||track.language||track.id}}</option></select></div><button class="primary-button wide" @click="openPlayer">▶ 播放</button><button class="secondary-button wide" @click="play(selected)">页内预览</button><label class="fallback-toggle"><input v-model="autoSpeed" type="checkbox" @change="configureAutoSpeed"/>每分钟自动测速</label><button class="secondary-button wide" :disabled="speedLoading" @click="testSpeed(selected)">{{speedLoading?'测速中…':'测速并显示线路'}}</button><div class="route-list"><div v-for="route in rankedSpeeds" :key="route.index" class="route-row" :class="{good:route.ok,active:activeRoute===route.index}"><span>线路 {{route.index+1}} · {{route.index===0?'1080p':'自动'}}</span><b>{{route.ok?(route.index===rankedSpeeds[0]?.index?'优选':'稳定'):'较慢/失败'}}</b><small>{{route.message||`${route.latencyMs}ms · ${route.kbps}kbps`}}</small><button @click="play(selected,route.index)">播放</button></div><div v-if="speeds.length===0" class="route-hint">共有 {{routeCount(selected)}} 条线路；自动优选会先测速排序，预检失败的线路仍会作为回退候选。</div><p v-if="switchReasons.length" class="route-hint switch-reasons">最近切线记录：{{switchReasons.join('；')}}</p></div></template><div v-else class="detail-empty"><span>◉</span><h3>选择频道</h3><p>频道信息、页内预览和线路质量会显示在这里。</p></div>
      </aside>
    </div>
  <dialog :open="Boolean(programDetail)" class="event-dialog"><article v-if="programDetail"><h3>{{programDetail.title}}</h3><p>{{new Date(programDetail.start).toLocaleString()}} — {{new Date(programDetail.stop).toLocaleString()}}</p><p>{{programDetail.description||'暂无节目简介。'}}</p><button @click="programDetail=null">关闭</button></article></dialog>
  <dialog :open="Boolean(reservationDraft)" class="reservation-dialog"><article v-if="reservationDraft"><h3>创建节目预约</h3><p>{{selected?.name}} · {{reservationDraft.title}}</p><p>{{new Date(reservationDraft.start).toLocaleString()}}</p><div class="row-actions"><button class="primary-button" @click="confirmReservation">确认预约</button><button class="secondary-button" @click="reservationDraft=null">取消</button></div></article></dialog></section>
</template>

<style scoped>
.live-source-switcher{display:flex;gap:7px;margin:-4px 0 10px;padding:4px;overflow:auto}.live-source-switcher button{display:flex;min-width:150px;flex-direction:column;align-items:flex-start;gap:2px;padding:8px 10px;border:1px solid var(--line);border-radius:9px;background:var(--surface-1);text-align:left}.live-source-switcher button.active{border-color:var(--accent);background:var(--accent-soft);color:var(--accent)}.live-source-switcher small{font-size:9px;color:var(--muted)}.live-source-strip{display:flex;align-items:center;gap:10px;margin:-4px 0 14px;padding:10px 14px;border:1px solid var(--line);border-radius:10px;background:var(--surface-1)}.live-source-strip>span,.epg-state{font-size:10px;padding:3px 7px;border-radius:999px;background:var(--surface-2);font-style:normal}.epg-state.ok{color:var(--success,#397a50)}.live-source-strip>small{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--muted);flex:1}.live-source-strip>em{font-size:10px;color:var(--muted);font-style:normal;white-space:nowrap}.fallback-toggle{display:flex;align-items:center;gap:6px;font-size:12px;white-space:nowrap}.native-live-preview{position:relative;overflow:hidden;isolation:isolate}.route-row{grid-template-columns:auto auto 1fr auto!important}.route-row.active{outline:1px solid var(--accent)}.route-row button{font-size:11px}.pane-heading small{display:block;color:var(--muted);margin-top:3px}.channel-copy small{display:flex;gap:4px;align-items:center;min-width:0}.channel-badge{font-style:normal;font-size:9px;padding:2px 5px;border-radius:999px;background:var(--surface-2);white-space:nowrap}.channel-copy .now-line{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.now-line b{font-size:9px;margin-right:4px;color:var(--accent)}@media(max-width:900px){.live-source-strip{align-items:flex-start;flex-wrap:wrap}.live-source-strip>small{flex-basis:100%}}

.channel-search-tools,.preview-controls{display:flex;gap:6px;margin:6px 0}.channel-search-tools input{min-width:0;flex:1}.event-dialog{z-index:2000;max-width:520px;border:1px solid var(--line);border-radius:12px;background:var(--panel);color:inherit}.switch-reasons{color:var(--warn)}.pane-heading select{max-width:170px}
</style>
<style scoped>
.virtual-channel-list{height:520px;overflow:auto;contain:strict}.channel-row{content-visibility:auto;contain-intrinsic-size:76px}.reservation-dialog{position:fixed;inset:0;margin:auto;z-index:6000;max-width:420px;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--text)}.reservation-dialog article{display:grid;gap:10px;padding:18px}
</style>
