<script setup lang="ts">
import { computed,nextTick,onBeforeUnmount,onMounted,ref,watch } from 'vue';
import type { MusicQueueMode,MusicSource,MusicTrack,PlaybackSessionSnapshot,PlayerLoadStatus,PlayerStats } from '@free-new-desk/contracts';
import MusicArtworkTile from '../components/MusicArtworkTile.vue';
import MusicIcon from '../components/MusicIcon.vue';
import MusicNetworkSourceDialog from '../components/MusicNetworkSourceDialog.vue';

type LrcLine={time:number;text:string};
const TRACK_ROW_HEIGHT=48,VIRTUAL_OVERSCAN=8,VIRTUAL_WINDOW=48;
const sources=ref<MusicSource[]>([]),tracks=ref<MusicTrack[]>([]),libraryTracks=ref<MusicTrack[]>([]),sourceId=ref(''),query=ref(''),tab=ref<'tracks'|'albums'|'artists'>('tracks'),onlyFavorites=ref(false),loading=ref(false),status=ref(''),current=ref<MusicTrack|null>(null),artwork=ref(''),lyrics=ref<LrcLine[]>([]),rawLyrics=ref(''),stats=ref<PlayerStats|null>(null),clockPosition=ref(0),lyricsBox=ref<HTMLElement|null>(null),loadStatus=ref<PlayerLoadStatus|null>(null),runtime=ref<PlaybackSessionSnapshot>({generation:0,sessionId:'',requestId:'',domain:null,status:'idle',updatedAt:0}),queueIds=ref<string[]>([]),mode=ref<MusicQueueMode>((localStorage.getItem('music.mode') as MusicQueueMode)||'sequence'),volume=ref(Number(localStorage.getItem('music.volume')??80)),seeking=ref(false),seekValue=ref(0),trackScrollTop=ref(0),trackList=ref<HTMLElement|null>(null),networkSourceOpen=ref(false),draggedQueueIndex=ref(-1);
let timer:ReturnType<typeof setInterval>|undefined,consumedEof='',searchTimer:ReturnType<typeof setTimeout>|undefined,removeRuntime:(()=>void)|undefined,assetGeneration=0,searchGeneration=0,playGeneration=0,lastProgressSavedAt=0,clockAnchorPosition=0,clockAnchorAt=performance.now(),clockRaf=0,userLyricsScrollUntil=0,lastSeekAt=0,lastSeekTarget=-1;
const sourceMap=computed(()=>new Map(sources.value.map(item=>[item.id,item]))),trackMap=computed(()=>new Map(libraryTracks.value.map(item=>[item.id,item]))),queue=computed(()=>queueIds.value.map(id=>trackMap.value.get(id)).filter((item):item is MusicTrack=>Boolean(item))),filtered=computed(()=>onlyFavorites.value?tracks.value.filter(item=>item.favorite):tracks.value),virtualStart=computed(()=>Math.max(0,Math.floor(trackScrollTop.value/TRACK_ROW_HEIGHT)-VIRTUAL_OVERSCAN)),visibleTracks=computed(()=>filtered.value.slice(virtualStart.value,virtualStart.value+VIRTUAL_WINDOW)),virtualTop=computed(()=>virtualStart.value*TRACK_ROW_HEIGHT),virtualBottom=computed(()=>Math.max(0,(filtered.value.length-virtualStart.value-visibleTracks.value.length)*TRACK_ROW_HEIGHT)),artists=computed(()=>[...new Set(filtered.value.map(item=>item.artist||'未知艺人'))].sort((a,b)=>a.localeCompare(b))),albums=computed(()=>[...new Set(filtered.value.map(item=>item.album||'未知专辑'))].sort((a,b)=>a.localeCompare(b))),currentIndex=computed(()=>current.value?queue.value.findIndex(item=>item.id===current.value?.id):-1);
const albumEntities=computed(()=>{const map=new Map<string,{name:string;count:number;track:MusicTrack}>();for(const track of filtered.value){const name=track.album||'未知专辑',row=map.get(name);if(row)row.count+=1;else map.set(name,{name,count:1,track});}return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name));});
const artistEntities=computed(()=>{const map=new Map<string,{name:string;count:number;track:MusicTrack}>();for(const track of filtered.value){const name=track.artist||'未知艺人',row=map.get(name);if(row)row.count+=1;else map.set(name,{name,count:1,track});}return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name));});
const activeLyric=computed(()=>{const position=clockPosition.value;let active=-1;for(let index=0;index<lyrics.value.length;index+=1){if((lyrics.value[index]?.time??Infinity)<=position)active=index;else break;}return active;}),nowFormat=computed(()=>current.value?.cueTrack?`CUE #${String(current.value.cueTrack).padStart(2,'0')} · ${current.value.format}`:current.value?.format||'—'),nowSource=computed(()=>current.value?sourceMap.value.get(current.value.sourceId)?.name??'':'');
function formatTime(value:number|undefined){const total=Math.max(0,Math.floor(value??0));return `${Math.floor(total/60).toString().padStart(2,'0')}:${(total%60).toString().padStart(2,'0')}`;}
function parseLrc(text:string):LrcLine[]{const offset=Number(/\[offset:([+-]?\d+)\]/i.exec(text)?.[1]??0)/1000,rows:LrcLine[]=[];for(const line of text.split(/\r?\n/)){const tags=[...line.matchAll(/\[(\d{1,3}):(\d{2})(?:[.:](\d{1,3}))?\]/g)];if(!tags.length)continue;const body=line.replace(/\[[^\]]+\]/g,'').trim();for(const tag of tags)rows.push({time:Math.max(0,Number(tag[1]??0)*60+Number(tag[2]??0)+Number(`0.${tag[3]??0}`)+offset),text:body});}return rows.sort((a,b)=>a.time-b.time);}
function persistQueue(){localStorage.setItem('music.queue',JSON.stringify(queueIds.value.slice(0,2000)));} function restoreQueue(){try{const parsed=JSON.parse(localStorage.getItem('music.queue')??'[]') as unknown;if(Array.isArray(parsed))queueIds.value=parsed.filter((item):item is string=>typeof item==='string').slice(0,2000);}catch{queueIds.value=[];}}
function readProgress():Record<string,number>{try{const parsed=JSON.parse(localStorage.getItem('music.progress')??'{}') as unknown;if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))return parsed as Record<string,number>;}catch{}return{};} function saveProgress(trackId:string,position:number,duration?:number){const all=readProgress();if(!Number.isFinite(position)||position<3||(duration&&duration-position<10))delete all[trackId];else all[trackId]=Math.round(position*10)/10;localStorage.setItem('music.progress',JSON.stringify(Object.fromEntries(Object.entries(all).slice(-500))));}
function resetTrackScroll(){trackScrollTop.value=0;if(trackList.value)trackList.value.scrollTop=0;} function onTrackScroll(event:Event){trackScrollTop.value=(event.currentTarget as HTMLElement).scrollTop;}
async function loadSources(){sources.value=await window.desktop.music.listSources();if(sourceId.value&&!sources.value.some(item=>item.id===sourceId.value))sourceId.value='';} async function loadTracks(){const generation=++searchGeneration;loading.value=true;try{const result=await window.desktop.music.listTracks(sourceId.value||undefined,query.value.trim()||undefined,50_000);if(generation!==searchGeneration)return;tracks.value=result;resetTrackScroll();}catch(error){status.value=error instanceof Error?error.message:String(error);}finally{loading.value=false;}}
async function refreshLibrary(){await loadSources();libraryTracks.value=await window.desktop.music.listTracks(undefined,undefined,50_000);await loadTracks();}
async function addLocalSource(){loading.value=true;try{const result=await window.desktop.music.addLocalSource();if(!result.canceled){status.value=`已扫描 ${result.count??0} 首音乐${result.truncated?'（达到安全上限）':''}`;await refreshLibrary();if(result.source)sourceId.value=result.source.id;}}catch(error){status.value=error instanceof Error?error.message:String(error);}finally{loading.value=false;}}
async function onNetworkSourceSaved(source:MusicSource,count:number){networkSourceOpen.value=false;status.value=`已添加「${source.name}」，扫描到 ${count} 首音乐`;sourceId.value=source.id;onlyFavorites.value=false;await refreshLibrary();sourceId.value=source.id;await loadTracks();}
async function rescan(source:MusicSource){loading.value=true;source.scanState='scanning';try{const result=await window.desktop.music.scan(source.id);status.value=result.canceled?`${source.name}：扫描已取消，保留上次完整结果`:`${source.name}：扫描完成 ${result.count} 首`;await refreshLibrary();}catch(error){status.value=error instanceof Error?error.message:String(error);await loadSources();}finally{loading.value=false;}}
async function cancelScan(source:MusicSource){if(await window.desktop.music.cancelScan(source.id))status.value=`正在取消 ${source.name} 的扫描…`;} async function removeSource(source:MusicSource){if(!window.confirm(`删除音乐来源「${source.name}」？不会删除磁盘或服务器上的音乐文件。`))return;await window.desktop.music.removeSource(source.id);if(sourceId.value===source.id)sourceId.value='';await refreshLibrary();}
function scheduleSearch(){if(searchTimer)clearTimeout(searchTimer);searchTimer=setTimeout(()=>{void loadTracks();},250);} async function loadNowPlayingAssets(track:MusicTrack){const generation=++assetGeneration;artwork.value='';rawLyrics.value='';lyrics.value=[];const applies=()=>generation===assetGeneration&&current.value?.id===track.id;await Promise.all([window.desktop.music.artwork(track.id).then(cover=>{if(applies())artwork.value=cover??'';}).catch(()=>undefined),window.desktop.music.lyrics(track.id).then(lrc=>{if(applies()){rawLyrics.value=lrc;lyrics.value=parseLrc(lrc);}}).catch(()=>undefined)]);}
async function playTrack(track:MusicTrack,initiator:'user'|'auto-next'|'restore'='user'){const generation=++playGeneration;try{if(!queueIds.value.includes(track.id)){queueIds.value.push(track.id);queueIds.value=queueIds.value.slice(-2000);persistQueue();}status.value=`正在播放：${track.title}`;const result=await window.desktop.music.play({trackId:track.id,initiator});if(generation!==playGeneration)return;if(!result.ok)throw new Error(result.detail??'音乐加载失败');current.value=result.track;runtime.value=result.session;consumedEof='';if(initiator==='restore'){const position=readProgress()[track.id];if(typeof position==='number'&&Number.isFinite(position)&&position>2&&(!track.duration||position<track.duration-10))await window.desktop.playback.control({command:'seek',value:position,absolute:true});}await loadNowPlayingAssets(result.track);await nextTick();await poll();}catch(error){const message=error instanceof Error?error.message:String(error);if(generation===playGeneration&&!message.includes('PLAYBACK_SUPERSEDED'))status.value=message;}}
function queueAll(){const selected=filtered.value.slice(0,2000);queueIds.value=selected.map(item=>item.id);persistQueue();status.value=filtered.value.length>2000?`已加入前 2000 首到播放队列（当前筛选共 ${filtered.value.length} 首）`:`已加入 ${queueIds.value.length} 首到播放队列`;} function clearQueue(){queueIds.value=[];persistQueue();status.value='播放队列已清空';}
function removeQueueItem(index:number){queueIds.value.splice(index,1);queueIds.value=[...queueIds.value];persistQueue();} function dropQueue(target:number){const source=draggedQueueIndex.value;draggedQueueIndex.value=-1;if(source<0||source===target)return;const ids=[...queueIds.value],moved=ids.splice(source,1)[0];if(!moved)return;ids.splice(target,0,moved);queueIds.value=ids;persistQueue();}
async function toggleFavorite(track:MusicTrack){track.favorite=await window.desktop.music.toggleFavorite(track.id);} function nextQueueIndex(direction:1|-1):number{const items=queue.value;if(!items.length)return-1;if(mode.value==='repeat-one'&&currentIndex.value>=0)return currentIndex.value;if(mode.value==='shuffle'){if(items.length===1)return 0;let next=Math.floor(Math.random()*items.length);if(next===currentIndex.value)next=(next+1)%items.length;return next;}const base=currentIndex.value>=0?currentIndex.value:direction>0?-1:0;return(base+direction+items.length)%items.length;}
async function playAdjacent(direction:1|-1,initiator:'user'|'auto-next'='user'){const index=nextQueueIndex(direction),track=queue.value[index];if(track)await playTrack(track,initiator);} function setMode(next:MusicQueueMode){mode.value=next;localStorage.setItem('music.mode',next);} function cycleMode(){setMode(mode.value==='sequence'?'repeat-one':mode.value==='repeat-one'?'shuffle':'sequence');} function modeLabel(){return mode.value==='sequence'?'顺序播放':mode.value==='repeat-one'?'单曲循环':'随机播放';}
async function togglePause(){if(runtime.value.domain!=='music'){if(current.value)await playTrack(current.value,'restore');return;}await window.desktop.playback.control({command:'pause',value:!(stats.value?.paused??false)});await poll();} async function toggleMute(){await window.desktop.playback.control({command:'mute',value:!(stats.value?.muted??false)});await poll();} async function persistVolume(){const safe=Math.max(0,Math.min(100,Math.round(volume.value)));volume.value=safe;localStorage.setItem('music.volume',String(safe));await window.desktop.playback.control({command:'volume',value:safe});}
async function commitSeek(){const target=Number(seekValue.value);seeking.value=false;if(!Number.isFinite(target))return;const now=performance.now();if(Math.abs(target-lastSeekTarget)<.05&&now-lastSeekAt<120)return;lastSeekTarget=target;lastSeekAt=now;clockPosition.value=target;clockAnchorPosition=target;clockAnchorAt=now;await window.desktop.playback.control({command:'seek',value:target,absolute:true});}
async function onNaturalEnd(){if(current.value)saveProgress(current.value.id,0);if(mode.value==='repeat-one'&&current.value)await playTrack(current.value,'auto-next');else await playAdjacent(1,'auto-next');} function anchorClock(sample:PlayerStats){clockAnchorPosition=Math.max(0,sample.position??0);clockAnchorAt=performance.now();if(sample.paused)clockPosition.value=clockAnchorPosition;} function tickClock(){const sample=stats.value;if(sample&&runtime.value.domain==='music'){const elapsed=sample.paused?0:(performance.now()-clockAnchorAt)/1000,duration=Math.max(0,sample.duration??0);clockPosition.value=duration?Math.min(duration,clockAnchorPosition+elapsed):clockAnchorPosition+elapsed;if(!seeking.value)seekValue.value=clockPosition.value;}clockRaf=requestAnimationFrame(tickClock);}
function pauseLyricsFollow(){userLyricsScrollUntil=performance.now()+4000;} watch(activeLyric,async index=>{if(index<0||performance.now()<userLyricsScrollUntil)return;await nextTick();lyricsBox.value?.querySelector<HTMLElement>(`[data-lyric-index="${index}"]`)?.scrollIntoView({block:'center',behavior:'smooth'});});
async function poll(){try{const [s,l,r]=await Promise.all([window.desktop.playback.query('stats'),window.desktop.playback.query('load-status'),window.desktop.playback.runtimeSession()]);stats.value=s;loadStatus.value=l;runtime.value=r;anchorClock(s);if(r.domain!=='music')return;if(current.value&&Date.now()-lastProgressSavedAt>=5000){saveProgress(current.value.id,s.position,s.duration);lastProgressSavedAt=Date.now();}if(Math.abs(volume.value-s.volume)>1&&localStorage.getItem('music.volume')!==null)await window.desktop.playback.control({command:'volume',value:volume.value});else volume.value=Math.round(s.volume);const loadId=r.loadId??'';if(loadId&&r.requestId&&l.loadId===loadId&&l.status==='ended'&&l.error==='eof'&&consumedEof!==loadId){consumedEof=loadId;const claimed=await window.desktop.playback.claimNaturalEnd({loadId,requestId:r.requestId,domain:'music'});if(claimed)await onNaturalEnd();}}catch{}}
function selectArtist(artist:string){query.value=artist;tab.value='tracks';scheduleSearch();} function selectAlbum(album:string){query.value=album;tab.value='tracks';scheduleSearch();} function keydown(event:KeyboardEvent){const target=event.target as HTMLElement|null;if(target&&['INPUT','SELECT','TEXTAREA'].includes(target.tagName))return;if(event.code==='Space'&&runtime.value.domain==='music'){event.preventDefault();void togglePause();}else if(event.key==='ArrowLeft'&&runtime.value.domain==='music')void window.desktop.playback.control({command:'seek',value:-10});else if(event.key==='ArrowRight'&&runtime.value.domain==='music')void window.desktop.playback.control({command:'seek',value:10});}
onMounted(async()=>{restoreQueue();removeRuntime=window.desktop.playback.onRuntimeSessionChanged(value=>{runtime.value=value;if(value.domain!=='music'&&value.status==='playing')status.value=`当前播放器已切换到${value.domain==='live'?'直播':'点播'}模式`;});window.addEventListener('keydown',keydown);await refreshLibrary();const savedCurrent=localStorage.getItem('music.currentTrack');if(savedCurrent){const track=libraryTracks.value.find(item=>item.id===savedCurrent);if(track)current.value=track;}if(current.value)void loadNowPlayingAssets(current.value);timer=setInterval(()=>{void poll();},300);clockRaf=requestAnimationFrame(tickClock);void poll();});
onBeforeUnmount(()=>{assetGeneration+=1;playGeneration+=1;searchGeneration+=1;if(timer)clearInterval(timer);if(clockRaf)cancelAnimationFrame(clockRaf);if(searchTimer)clearTimeout(searchTimer);removeRuntime?.();window.removeEventListener('keydown',keydown);if(current.value){localStorage.setItem('music.currentTrack',current.value.id);if(runtime.value.domain==='music'&&stats.value)saveProgress(current.value.id,stats.value.position,stats.value.duration);}});
</script>

<template>
  <section class="music-page">
    <header class="music-heading"><div><h1>音乐</h1><p>私人音乐库 <span class="concept-tag">V1.4.12</span></p></div><div class="music-actions"><label class="music-search"><MusicIcon name="search" :size="16"/><input v-model="query" data-search-input placeholder="搜索曲目、艺人或专辑" @input="scheduleSearch"/></label><button class="soft-button" @click="addLocalSource">添加本地音乐</button><button class="accent-button" @click="networkSourceOpen=true">添加网络来源</button></div></header>
    <div class="music-layout">
      <aside class="music-library panel-like"><h3>音乐库</h3><button :class="{active:!sourceId&&!onlyFavorites&&tab==='tracks'}" @click="sourceId='';onlyFavorites=false;tab='tracks';loadTracks()"><MusicIcon name="library"/><span>全部曲目</span><b>{{tracks.length}}</b></button><button :class="{active:tab==='artists'}" @click="tab='artists';onlyFavorites=false"><MusicIcon name="artist"/><span>艺人</span><b>{{artists.length}}</b></button><button :class="{active:tab==='albums'}" @click="tab='albums';onlyFavorites=false"><MusicIcon name="album"/><span>专辑</span><b>{{albums.length}}</b></button><button :class="{active:onlyFavorites}" @click="onlyFavorites=true;tab='tracks';resetTrackScroll()"><MusicIcon name="heart"/><span>我的收藏</span><b>{{tracks.filter(t=>t.favorite).length}}</b></button><div class="source-title"><h3>来源</h3><button title="添加本地来源" @click="addLocalSource"><MusicIcon name="plus" :size="14"/></button></div>
        <div v-if="sources.length" class="source-list"><div v-for="source in sources" :key="source.id" class="source-row" :class="{selected:sourceId===source.id}" @click="sourceId=source.id;onlyFavorites=false;loadTracks()"><span class="source-dot" :class="source.scanState"/><div><strong>{{source.name}}</strong><small>{{source.kind==='local'?'本地音乐':source.kind==='webdav'?'WebDAV':'SMB'}} · {{source.scanState==='error'?'不可用':source.scanState==='scanning'?'扫描中':'已就绪'}}</small></div><span class="source-tools"><button v-if="source.scanState==='scanning'" title="取消扫描" @click.stop="cancelScan(source)"><MusicIcon name="stop" :size="13"/></button><button v-else title="重新扫描" @click.stop="rescan(source)"><MusicIcon name="refresh" :size="13"/></button><button title="删除来源" @click.stop="removeSource(source)"><MusicIcon name="trash" :size="13"/></button></span></div></div><div v-else class="empty-source">还没有音乐来源</div><div class="scan-footer"><span><MusicIcon name="check" :size="12"/>{{loading?'正在扫描或加载':'音乐库已就绪'}}</span><button @click="refreshLibrary"><MusicIcon name="refresh" :size="12"/>刷新音乐库</button></div>
      </aside>
      <main class="music-center panel-like"><div class="music-tabs"><button :class="{active:tab==='tracks'}" @click="tab='tracks'">曲目</button><button :class="{active:tab==='albums'}" @click="tab='albums'">专辑</button><button :class="{active:tab==='artists'}" @click="tab='artists'">艺人</button><span/><button class="text-action" @click="queueAll">全部加入队列</button></div>
        <div v-if="tab==='tracks'" class="track-section"><div class="table-title"><strong>{{onlyFavorites?'我的收藏':'全部曲目'}}</strong><span>{{filtered.length}} 首</span></div><div class="track-head"><span></span><span></span><span>标题</span><span>艺人</span><span>专辑</span><span>格式</span><span>时长</span><span></span></div><div ref="trackList" class="track-list" @scroll="onTrackScroll"><div class="virtual-spacer" :style="{height:`${virtualTop}px`}"/><div v-for="track in visibleTracks" :key="track.id" class="track-row" :class="{playing:current?.id===track.id&&runtime.domain==='music'}" role="button" tabindex="0" @dblclick="playTrack(track)" @keydown.enter="playTrack(track)"><span class="playing-bars"><MusicIcon :name="current?.id===track.id&&runtime.domain==='music'?'pause':'play'" :size="13"/></span><MusicArtworkTile :track-id="track.id" :alt="track.title" :online="false" compact/><span class="track-title"><strong>{{track.title}}</strong><small>{{track.cueTrack?`CUE #${String(track.cueTrack).padStart(2,'0')} · `:''}}{{track.relativePath}}</small></span><span>{{track.artist||'未知艺人'}}</span><span>{{track.album||'未知专辑'}}</span><span><em>{{track.cueTrack?'CUE':track.format}}</em></span><span class="track-duration">{{formatTime(track.duration)}}</span><span class="row-buttons"><button :aria-label="track.favorite?'取消收藏':'收藏'" @click.stop="toggleFavorite(track)"><MusicIcon :name="track.favorite?'heart-fill':'heart'" :size="15"/></button><button aria-label="播放" @click.stop="playTrack(track)"><MusicIcon name="play" :size="15"/></button></span></div><div class="virtual-spacer" :style="{height:`${virtualBottom}px`}"/><div v-if="!filtered.length" class="music-empty">{{sources.length?'没有匹配曲目':'点击“添加本地音乐”或“添加网络来源”建立音乐库。'}}</div></div></div>
        <div v-else-if="tab==='albums'" class="entity-grid"><button v-for="entry in albumEntities" :key="entry.name" @click="selectAlbum(entry.name)"><MusicArtworkTile :track-id="entry.track.id" :alt="entry.name"/><strong>{{entry.name}}</strong><small>{{entry.count}} 首</small></button></div>
        <div v-else class="entity-grid"><button v-for="entry in artistEntities" :key="entry.name" @click="selectArtist(entry.name)"><MusicArtworkTile :track-id="entry.track.id" :alt="entry.name" circular/><strong>{{entry.name}}</strong><small>{{entry.count}} 首</small></button></div>
        <section class="queue-box"><div class="queue-heading"><strong>播放队列 · {{queue.length}} 首</strong><span/><button @click="cycleMode"><MusicIcon name="queue" :size="14"/>{{modeLabel()}}</button><button @click="clearQueue"><MusicIcon name="trash" :size="14"/>清空</button></div><div class="queue-items"><div v-for="(track,index) in queue" :key="track.id" class="queue-item" :class="{current:track.id===current?.id}" draggable="true" @dragstart="draggedQueueIndex=index" @dragend="draggedQueueIndex=-1" @dragover.prevent @drop="dropQueue(index)"><span>{{index+1}}</span><button class="queue-title" @click="playTrack(track)"><strong>{{track.title}}</strong></button><span>{{track.artist||'未知艺人'}}</span><span>{{track.album||'未知专辑'}}</span><button class="queue-remove" aria-label="从队列移除" @click="removeQueueItem(index)"><MusicIcon name="trash" :size="13"/></button><span class="queue-grip"><MusicIcon name="grip" :size="14"/></span></div><div v-if="!queue.length" class="queue-empty">双击曲目或点击播放，将音乐加入队列。</div></div></section>
      </main>
      <aside class="now-playing panel-like"><h3>正在播放</h3><div class="cover-frame"><img v-if="artwork" :src="artwork" :alt="current?.title??'封面'"/><div v-else class="cover-placeholder"><MusicIcon name="album" :size="64"/></div></div><h2>{{current?.title??'尚未播放'}}</h2><p>{{current?.artist||'选择一首曲目开始播放'}}<span v-if="current?.album"> · {{current.album}}</span></p><div class="quality"><span>{{nowFormat}}</span><span v-if="stats?.sampleRate">{{Math.round(stats.sampleRate/1000)}} kHz</span><span v-if="stats?.audioChannels">{{stats.audioChannels}} ch</span><small>{{nowSource}}</small></div><div class="lyrics-title"><strong>歌词</strong><span>{{rawLyrics?'歌词已加载':'暂无歌词'}}</span></div><div ref="lyricsBox" class="lyrics" :class="{empty:!lyrics.length}" @wheel="pauseLyricsFollow" @pointerdown="pauseLyricsFollow"><template v-if="lyrics.length"><p v-for="(line,index) in lyrics" :key="`${line.time}-${index}`" :data-lyric-index="index" :class="{active:index===activeLyric}">{{line.text||'♪'}}</p></template><p v-else>{{current?'未找到本地或在线歌词':'播放音乐后显示歌词'}}</p></div></aside>
    </div>
    <footer class="music-player"><div class="mini-now"><div class="mini-cover"><img v-if="artwork" :src="artwork" alt=""/><MusicIcon v-else name="album" :size="22"/></div><div><strong>{{current?.title??'Free New Desk 音乐'}}</strong><small>{{current?.artist||'私人音乐库'}}</small></div><button v-if="current" :aria-label="current.favorite?'取消收藏':'收藏'" @click="toggleFavorite(current)"><MusicIcon :name="current.favorite?'heart-fill':'heart'" :size="17"/></button></div><div class="center-controls"><div class="transport"><button :title="modeLabel()" @click="cycleMode"><MusicIcon :name="mode==='shuffle'?'shuffle':mode==='repeat-one'?'repeat-one':'repeat'" :size="18"/></button><button aria-label="上一首" @click="playAdjacent(-1)"><MusicIcon name="previous" :size="20"/></button><button class="play-main" :disabled="!current" :aria-label="stats?.paused?'播放':'暂停'" @click="togglePause"><MusicIcon :name="stats?.paused?'play':'pause'" :size="23"/></button><button aria-label="下一首" @click="playAdjacent(1)"><MusicIcon name="next" :size="20"/></button><button title="单曲循环" @click="setMode(mode==='repeat-one'?'sequence':'repeat-one')"><MusicIcon name="repeat-one" :size="18"/></button></div><div class="seek-row"><span>{{formatTime(seekValue)}}</span><input v-model.number="seekValue" type="range" min="0" :max="Math.max(1,stats?.duration??1)" step="0.1" @pointerdown="seeking=true" @pointerup="commitSeek" @change="commitSeek"/><span>{{formatTime(stats?.duration)}}</span></div></div><div class="volume"><button :aria-label="stats?.muted?'取消静音':'静音'" @click="toggleMute"><MusicIcon :name="stats?.muted?'mute':'volume'" :size="18"/></button><input v-model.number="volume" type="range" min="0" max="100" @change="persistVolume"/><button :title="modeLabel()" @click="cycleMode"><MusicIcon name="queue" :size="18"/></button></div></footer>
    <MusicNetworkSourceDialog :open="networkSourceOpen" @close="networkSourceOpen=false" @saved="onNetworkSourceSaved"/><p v-if="status" class="music-status">{{status}}</p>
  </section>
</template>

<style scoped>
.music-page{--music-accent:#a76318;display:grid;grid-template-rows:auto minmax(0,1fr) 92px;gap:12px;height:calc(100vh - 84px);min-height:650px;color:var(--text)}
.music-heading{display:flex;align-items:end;justify-content:space-between;padding:4px 2px}.music-heading h1{font-family:Georgia,'Times New Roman',serif;font-size:34px;font-weight:500;margin:0}.music-heading p{margin:3px 0 0;color:var(--muted)}.concept-tag{margin-left:8px;border:1px solid #d8b98f;border-radius:6px;padding:2px 7px;color:var(--music-accent);font-size:11px}.music-actions{display:flex;gap:10px;align-items:center}.music-search{display:flex;align-items:center;gap:7px;width:315px;padding:8px 12px;border:1px solid var(--line);border-radius:8px;background:var(--surface)}.music-search input{border:0;outline:0;background:transparent;width:100%;color:inherit}.soft-button,.accent-button{height:38px;padding:0 16px;border:1px solid var(--line);border-radius:8px;background:var(--surface);color:inherit}.accent-button{background:var(--music-accent);border-color:var(--music-accent);color:white}
.music-layout{display:grid;grid-template-columns:245px minmax(520px,1fr) 325px;gap:8px;min-height:0}.panel-like{border:1px solid var(--line);border-radius:8px;background:color-mix(in srgb,var(--surface) 96%,transparent);min-height:0}
.music-library{display:flex;flex-direction:column;padding:12px}.music-library h3,.now-playing>h3{margin:0 0 8px;font-size:13px}.music-library>button{display:grid;grid-template-columns:24px 1fr auto;gap:6px;align-items:center;border:0;background:transparent;color:inherit;padding:10px;border-bottom:1px solid var(--line);text-align:left}.music-library>button.active{color:var(--music-accent);background:rgba(167,99,24,.06)}.music-library>button b{color:var(--music-accent);font-size:12px}.source-title{display:flex;justify-content:space-between;align-items:center;margin-top:18px}.source-title button,.source-tools button{border:1px solid var(--line);background:transparent;border-radius:6px;color:inherit}.source-list{overflow:auto}.source-row{display:grid;grid-template-columns:10px 1fr auto;gap:8px;align-items:center;padding:9px 6px;border-radius:7px;cursor:pointer}.source-row.selected{background:rgba(167,99,24,.08)}.source-dot{width:8px;height:8px;border-radius:50%;background:#2aa34a}.source-dot.error{background:#c94a46}.source-dot.scanning{background:#d89b2b}.source-row div{min-width:0}.source-row strong,.source-row small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.source-row small{color:var(--muted);font-size:10px}.source-tools{opacity:0;display:flex;gap:4px}.source-row:hover .source-tools{opacity:1}.scan-footer{margin-top:auto;display:flex;justify-content:space-between;gap:5px;padding-top:10px;border-top:1px solid var(--line);font-size:10px;color:var(--muted)}.scan-footer span,.scan-footer button{display:flex;align-items:center;gap:5px}.scan-footer button{border:0;background:transparent;color:inherit}.empty-source{padding:12px;color:var(--muted);font-size:11px}
.music-center{display:grid;grid-template-rows:46px minmax(0,1fr) 170px;overflow:hidden}.music-tabs{display:grid;grid-template-columns:auto auto auto 1fr auto;align-items:end;border-bottom:1px solid var(--line);padding:0 10px}.music-tabs button{border:0;background:transparent;color:inherit;padding:12px 16px 10px}.music-tabs button.active{color:var(--music-accent);border-bottom:2px solid var(--music-accent)}.music-tabs .text-action{font-size:11px;color:var(--muted)}
.track-section{min-height:0;display:grid;grid-template-rows:42px 34px minmax(0,1fr)}.table-title{display:flex;justify-content:space-between;align-items:center;padding:0 15px}.table-title span{color:var(--muted);font-size:11px}.track-head,.track-row{display:grid;grid-template-columns:24px 36px minmax(160px,1.5fr) minmax(90px,.9fr) minmax(90px,1fr) 58px 48px 64px;align-items:center;gap:8px;padding:0 12px}.track-head{font-size:10px;color:var(--muted);border-bottom:1px solid var(--line)}.track-list{overflow:auto}.track-row{width:100%;height:48px;min-height:48px;box-sizing:border-box;border:0;border-bottom:1px solid var(--line);background:transparent;color:inherit;text-align:left;cursor:pointer}.track-row:hover,.track-row.playing{background:rgba(167,99,24,.06)}.track-row.playing{color:var(--music-accent)}.track-title{min-width:0}.track-title strong,.track-title small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.track-title small{font-size:9px;color:var(--muted)}.track-row em{font-style:normal;border:1px solid var(--line);border-radius:5px;padding:2px 6px;font-size:9px}.track-duration{font-variant-numeric:tabular-nums;color:var(--muted);font-size:10px}.row-buttons{display:flex;justify-content:end;gap:4px}.playing-bars{color:var(--music-accent)}.virtual-spacer{width:1px;pointer-events:none}.music-empty,.queue-empty{display:grid;place-items:center;height:100%;color:var(--muted);font-size:12px}
.entity-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:12px;padding:16px;overflow:auto}.entity-grid button{display:grid;gap:6px;border:0;background:transparent;color:inherit;text-align:left}.entity-grid .artwork-tile{width:100%}.entity-grid small{color:var(--muted)}
.queue-box{border-top:1px solid var(--line);min-height:0;display:grid;grid-template-rows:36px 1fr}.queue-heading{display:grid;grid-template-columns:auto 1fr auto auto;align-items:center;gap:12px;padding:0 12px}.queue-heading button{display:flex;align-items:center;gap:5px;border:0;background:transparent;color:var(--muted);font-size:10px}.queue-items{overflow:auto}.queue-item{display:grid;grid-template-columns:25px minmax(120px,1.2fr) minmax(90px,1fr) minmax(90px,1fr) 28px 22px;width:100%;gap:8px;padding:7px 12px;align-items:center;color:inherit;font-size:11px}.queue-item.current{color:var(--music-accent);background:rgba(167,99,24,.05)}.queue-title,.queue-remove{border:0;background:transparent;color:inherit;min-width:0}.queue-title{text-align:left}.queue-title strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.queue-remove{display:grid;place-items:center}.queue-grip{display:grid;place-items:center;color:var(--muted);cursor:grab}.queue-item:active .queue-grip{cursor:grabbing}
.now-playing{padding:12px;overflow:hidden;display:flex;flex-direction:column}.cover-frame{width:100%;aspect-ratio:1;max-height:315px;border-radius:5px;overflow:hidden;background:#162434}.cover-frame img{width:100%;height:100%;object-fit:cover}.cover-placeholder{display:grid;place-items:center;width:100%;height:100%;color:color-mix(in srgb,var(--music-accent) 70%,var(--text));background:radial-gradient(circle at 30% 30%,color-mix(in srgb,var(--music-accent) 35%,#1b6a78),#111b2a 65%)}.now-playing h2{font-family:Georgia,'Times New Roman',serif;font-weight:500;font-size:27px;text-align:center;margin:10px 0 2px}.now-playing>p{text-align:center;color:var(--muted);margin:0 0 7px}.quality{display:flex;justify-content:center;gap:5px;flex-wrap:wrap;color:var(--muted);font-size:10px}.quality span{border:1px solid var(--line);padding:2px 5px;border-radius:4px}.quality small{width:100%;text-align:center}.lyrics-title{display:flex;justify-content:space-between;margin-top:14px;padding-top:8px;border-top:1px solid var(--line);font-size:11px}.lyrics-title span{color:var(--muted)}.lyrics{overflow:auto;text-align:center;padding:7px 4px;scrollbar-width:thin}.lyrics p{margin:8px 0;color:var(--muted);transition:.15s}.lyrics p.active{color:var(--music-accent);font-weight:700;font-size:15px}.lyrics.empty{display:grid;place-items:center}
.music-player{display:grid;grid-template-columns:260px 1fr 240px;align-items:center;border:1px solid var(--line);border-radius:8px;background:var(--surface);padding:8px 16px}.mini-now{display:grid;grid-template-columns:50px 1fr auto;gap:10px;align-items:center;min-width:0}.mini-cover{width:50px;height:50px;border-radius:4px;overflow:hidden;background:#233343;display:grid;place-items:center}.mini-cover img{width:100%;height:100%;object-fit:cover}.mini-now strong,.mini-now small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mini-now small{color:var(--muted)}.mini-now>button,.transport button,.volume button,.row-buttons button,.source-tools button{display:grid;place-items:center;border:0;background:transparent;color:inherit;border-radius:5px;padding:4px}.mini-now>button:hover,.transport button:hover,.volume button:hover,.row-buttons button:hover,.source-tools button:hover,.queue-remove:hover{background:color-mix(in srgb,var(--music-accent) 10%,transparent)}.center-controls{display:grid;gap:5px;max-width:540px;margin:auto;width:100%}.transport{display:flex;justify-content:center;gap:25px;align-items:center}.transport .play-main{width:48px;height:48px;border-radius:50%;background:var(--music-accent);color:white}.seek-row{display:grid;grid-template-columns:38px 1fr 38px;gap:7px;align-items:center;font-size:10px;color:var(--muted)}.seek-row input,.volume input{accent-color:var(--music-accent)}.volume{display:flex;align-items:center;justify-content:end;gap:9px}.volume input{width:145px}.music-status{position:fixed;right:24px;bottom:105px;max-width:420px;margin:0;padding:7px 11px;border:1px solid var(--line);border-radius:7px;background:var(--surface);box-shadow:0 5px 18px rgba(0,0,0,.12);font-size:10px;color:var(--muted)}
@media(forced-colors:active){.panel-like,.music-player,.track-row,.queue-item{border-color:CanvasText}.track-row.playing,.queue-item.current{outline:1px solid Highlight}.transport .play-main{background:Highlight;color:HighlightText}}
@media(max-height:760px){.music-page{min-height:560px;grid-template-rows:auto minmax(0,1fr) 84px}.cover-frame{max-height:220px}.now-playing h2{font-size:22px;margin-top:6px}}
@media(max-width:1250px){.music-layout{grid-template-columns:210px 1fr 270px}.music-player{grid-template-columns:220px 1fr 190px}}@media(max-width:1050px){.music-layout{grid-template-columns:190px 1fr}.now-playing{display:none}.music-player{grid-template-columns:200px 1fr 150px}}
</style>
