<script setup lang="ts">
import { computed,onMounted,onUnmounted,ref } from 'vue';
import { useRoute,useRouter } from 'vue-router';
import type { DetailResult,SourceHealth,VideoCard } from '@free-new-desk/contracts';
import { isVodFavorite,listVodFavorites,toggleVodFavorite } from '../favorites';
import { emitPlaybackStage } from '../playback-events';
import { usePageStateStore } from '../stores/page-state';

type Group={sourceId:string;sourceName:string;items:VideoCard[]};
type SourceOption={id:string;name:string};
type LiveMatch={sourceId:string;sourceName:string;channelId:string;name:string;group:string};
interface SearchPageSnapshot{keyword:string;suggestionPool:string[];sourceFilter:string;sourceOptions:SourceOption[];liveMatches:LiveMatch[];searchHistory:string[];groups:Group[];detail:DetailResult|null;detailSource:string;detailSourceName:string;favorite:boolean;expandedGroups:string[];expandedLive:boolean;}
const router=useRouter();const route=useRoute();const pageState=usePageStateStore();
const keyword=ref('');const suggestionPool=ref<string[]>([]);const sourceFilter=ref('all');const sourceOptions=ref<SourceOption[]>([]);const liveMatches=ref<LiveMatch[]>([]);const searchHistory=ref<string[]>([]);const groups=ref<Group[]>([]);const loading=ref(false);const searchCompleted=ref(0);const searchTotal=ref(0);const error=ref('');const detail=ref<DetailResult|null>(null);const detailSource=ref('');const detailSourceName=ref('');const favorite=ref(false);const expandedGroups=ref(new Set<string>());const expandedLive=ref(false);let generation=0;const PAGE_SIZE=12;
const filteredGroups=computed(()=>sourceFilter.value==='all'?groups.value:groups.value.filter(group=>group.sourceId===sourceFilter.value));
const visibleLiveMatches=computed(()=>sourceFilter.value==='all'?liveMatches.value:liveMatches.value.filter(item=>item.sourceId===sourceFilter.value));
const suggestions=computed(()=>{const value=keyword.value.trim().toLowerCase();return[...new Set([...suggestionPool.value,...searchHistory.value])].filter(item=>!value||item.toLowerCase().includes(value)).slice(0,8);});
const resultCount=computed(()=>groups.value.reduce((sum,group)=>sum+group.items.length,0));
const hasResults=computed(()=>filteredGroups.value.length>0||visibleLiveMatches.value.length>0);
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'})[char]??char);}
function highlightName(name:string){const term=keyword.value.trim();const safe=escapeHtml(name);if(!term)return safe;const escapedTerm=escapeHtml(term).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return safe.replace(new RegExp(escapedTerm,'gi'),match=>`<mark>${match}</mark>`);}
function visibleGroupItems(group:Group):VideoCard[]{return expandedGroups.value.has(group.sourceId)?group.items:group.items.slice(0,PAGE_SIZE);}
function toggleGroup(group:Group){const next=new Set(expandedGroups.value);next.has(group.sourceId)?next.delete(group.sourceId):next.add(group.sourceId);expandedGroups.value=next;}
function clearInput(){generation+=1;keyword.value='';groups.value=[];liveMatches.value=[];detail.value=null;error.value='';searchCompleted.value=0;searchTotal.value=0;loading.value=false;}
function removeHistoryItem(term:string){searchHistory.value=searchHistory.value.filter(item=>item!==term);localStorage.setItem('search.history',JSON.stringify(searchHistory.value));}
function prioritySources(values:SourceOption[],health:SourceHealth[]):SourceOption[]{const map=new Map(health.map(item=>[item.sourceId,item]));return[...values].sort((a,b)=>{const ah=map.get(a.id),bh=map.get(b.id);const ar=ah?.ok===true?0:ah?.ok===false?2:1,br=bh?.ok===true?0:bh?.ok===false?2:1;return ar-br+(Number(ah?.latencyMs??999999)-Number(bh?.latencyMs??999999));});}
async function search(){const term=keyword.value.trim();if(!term)return;const current=++generation;loading.value=true;error.value='';detail.value=null;favorite.value=false;groups.value=[];liveMatches.value=[];expandedGroups.value=new Set();expandedLive.value=false;searchCompleted.value=0;const health=await window.desktop.source.health().catch(()=>[] as SourceHealth[]);const pointSources=prioritySources(sourceOptions.value,health);searchTotal.value=pointSources.length;let cursor=0;
  const worker=async()=>{while(current===generation&&cursor<pointSources.length){const source=pointSources[cursor++];if(!source)continue;try{const result=await window.desktop.source.search(source.id,term,1);if(current===generation&&result.items.length){groups.value=[...groups.value,{sourceId:source.id,sourceName:source.name,items:result.items}];}}catch{/* Failed and timed-out sources are intentionally omitted from the search UI. */}finally{if(current===generation)searchCompleted.value+=1;}}};
  const pointWork=Promise.all(Array.from({length:Math.min(4,Math.max(1,pointSources.length))},worker));
  const liveWork=(async()=>{const liveSources=await window.desktop.live.listSources().catch(()=>[]);await Promise.allSettled(liveSources.filter(item=>item.enabled).map(async source=>{const channelGroups=await window.desktop.live.channels(source.id).catch(()=>[]);const matches=channelGroups.flatMap(group=>group.channels.filter(channel=>channel.name.toLowerCase().includes(term.toLowerCase())).map(channel=>({sourceId:source.id,sourceName:source.name,channelId:channel.id,name:channel.name,group:group.name})));if(current===generation&&matches.length)liveMatches.value=[...liveMatches.value,...matches];}));})();
  try{await Promise.allSettled([pointWork,liveWork]);if(current===generation){searchHistory.value=[term,...searchHistory.value.filter(item=>item!==term)].slice(0,20);localStorage.setItem('search.history',JSON.stringify(searchHistory.value));}}finally{if(current===generation)loading.value=false;}}
function useSuggestion(value:string){keyword.value=value;void search();}
function clearHistory(){searchHistory.value=[];localStorage.removeItem('search.history');}
function cancel(){generation+=1;loading.value=false;}
async function open(sourceId:string,item:VideoCard){error.value='';try{detailSource.value=sourceId;detailSourceName.value=groups.value.find(group=>group.sourceId===sourceId)?.sourceName??sourceId;detail.value=await window.desktop.source.detail(sourceId,[item.id]);favorite.value=await isVodFavorite(sourceId,detail.value.id);}catch(value){error.value=value instanceof Error?value.message:String(value);}}
async function toggleFavorite(){if(!detail.value)return;favorite.value=await toggleVodFavorite(detailSource.value,detailSourceName.value,detail.value);}
async function play(flag:string,id:string,name:string){if(!detail.value)return;error.value='';const request={sourceId:detailSource.value,videoId:detail.value.id,videoName:detail.value.name,flag,episodeId:id,episodeName:name};const navigationStarted=performance.now();await router.push('/player');const navigationMs=performance.now()-navigationStarted;void window.desktop.diagnostics.recordPerformance('playbackNavigationMs',navigationMs).catch(()=>false);if(window.desktop.app.isUiSmoke()&&navigationMs>150)throw new Error(`Playback navigation exceeded 150ms budget: ${navigationMs.toFixed(1)}ms`);emitPlaybackStage('source-resolving','正在解析搜索结果播放线路…');void window.desktop.playback.play(request).then(()=>emitPlaybackStage('playing','媒体已打开')).catch(value=>{const message=value instanceof Error?value.message:String(value);emitPlaybackStage('failed','播放失败',message);});}
async function playLive(item:LiveMatch){error.value='';const navigationStarted=performance.now();await router.push('/player');const navigationMs=performance.now()-navigationStarted;void window.desktop.diagnostics.recordPerformance('playbackNavigationMs',navigationMs).catch(()=>false);if(window.desktop.app.isUiSmoke()&&navigationMs>150)throw new Error(`Playback navigation exceeded 150ms budget: ${navigationMs.toFixed(1)}ms`);emitPlaybackStage('connecting',`正在连接直播频道「${item.name}」…`);void window.desktop.live.play({sourceId:item.sourceId,channelId:item.channelId,allowFallback:true}).then(()=>emitPlaybackStage('playing',`直播频道「${item.name}」已连接`)).catch(value=>{const message=value instanceof Error?value.message:String(value);emitPlaybackStage('failed','直播播放失败',message);});}
onMounted(async()=>{try{searchHistory.value=JSON.parse(localStorage.getItem('search.history')??'[]') as string[];}catch{searchHistory.value=[];}const routeTerm=typeof route.query.q==='string'?route.query.q.trim():'';const cached=pageState.read<SearchPageSnapshot>('search');if(cached&&!routeTerm){const v=cached.value;keyword.value=v.keyword;suggestionPool.value=v.suggestionPool;sourceFilter.value=v.sourceFilter;sourceOptions.value=v.sourceOptions;liveMatches.value=v.liveMatches;searchHistory.value=v.searchHistory;groups.value=v.groups;detail.value=v.detail;detailSource.value=v.detailSource;detailSourceName.value=v.detailSourceName;favorite.value=v.favorite;expandedGroups.value=new Set(v.expandedGroups);expandedLive.value=v.expandedLive;return;}const[sourceValues,favorites,history]=await Promise.all([window.desktop.source.list(),listVodFavorites().catch(()=>[]),window.desktop.history.list(30).catch(()=>[])]);sourceOptions.value=sourceValues.filter(item=>item.enabled&&item.searchable!==false).map(item=>({id:item.id,name:item.name}));suggestionPool.value=[...favorites.map(item=>item.label??item.name),...history.map(item=>item.videoName)];if(typeof route.query.q==='string'&&route.query.q.trim()){keyword.value=route.query.q.slice(0,100);await search();}});
onUnmounted(()=>{pageState.save<SearchPageSnapshot>('search',{keyword:keyword.value,suggestionPool:[...suggestionPool.value],sourceFilter:sourceFilter.value,sourceOptions:[...sourceOptions.value],liveMatches:[...liveMatches.value],searchHistory:[...searchHistory.value],groups:[...groups.value],detail:detail.value,detailSource:detailSource.value,detailSourceName:detailSourceName.value,favorite:favorite.value,expandedGroups:[...expandedGroups.value],expandedLive:expandedLive.value});generation+=1;});
</script>

<template>
  <section class="page search-page">
    <div class="page-heading split"><div><h1>聚合搜索</h1><p>优先检索兼容且响应快的已启用来源，成功结果会边返回边显示。</p></div><div class="toolbar-group"><div class="search-box large"><span>⌕</span><input v-model="keyword" autofocus maxlength="100" placeholder="输入影片或频道关键词" aria-label="聚合搜索关键词" data-search-input @keyup.enter="search"/><button v-if="keyword||groups.length||liveMatches.length" class="clear-button" aria-label="清除搜索" title="清除输入与结果" @click="clearInput">×</button></div><select v-model="sourceFilter" aria-label="来源筛选"><option value="all">全部来源</option><option v-for="item in sourceOptions" :key="item.id" :value="item.id">{{item.name}}</option></select><button class="primary-button" :disabled="loading||!keyword.trim()" @click="search">搜索</button><button v-if="loading" class="secondary-button" @click="cancel">取消</button></div></div>
    <div v-if="suggestions.length&&!groups.length&&!liveMatches.length&&!loading" class="search-suggestions"><span>搜索历史</span><span v-for="item in suggestions" :key="item" class="suggestion-chip"><button @click="useSuggestion(item)">{{item}}</button><button class="chip-remove" :aria-label="`删除历史 ${item}`" title="删除该条历史" @click="removeHistoryItem(item)">×</button></span><button class="text-link" @click="clearHistory">清空历史</button></div>
    <p v-if="hasResults" class="status-line" role="status">搜索状态：已显示 {{groups.length}} 个点播来源 · {{resultCount}} 条点播结果 · {{liveMatches.length}} 个直播频道</p><p v-if="error" class="error-banner">{{error}}</p>
    <div class="search-workspace">
      <div class="search-results">
        <div v-if="loading" class="status-line">正在聚合搜索… 已完成 {{searchCompleted}} / {{searchTotal}} 个点播来源；快来源结果会立即显示。</div>
        <template v-if="hasResults"><section v-if="visibleLiveMatches.length" class="panel search-group"><div class="panel-heading"><div><span class="panel-kicker">直播频道</span><h2>{{visibleLiveMatches.length}} 条匹配</h2></div><button v-if="visibleLiveMatches.length>6" class="text-link" @click="expandedLive=!expandedLive">{{expandedLive?'收起':'查看全部'}}</button></div><div class="live-search-list"><button v-for="item in (expandedLive?visibleLiveMatches:visibleLiveMatches.slice(0,6))" :key="item.sourceId+item.channelId" @click="playLive(item)"><strong>{{item.name}}</strong><small>{{item.sourceName}} · {{item.group}}</small></button></div></section><section v-for="group in filteredGroups" :key="group.sourceId" class="panel search-group"><div class="panel-heading"><div><span class="panel-kicker">{{group.sourceName}}</span><h2>{{group.items.length}} 条结果</h2></div></div><div class="poster-grid cinematic search-grid"><button v-for="item in visibleGroupItems(group)" :key="item.id" class="poster-card" :class="{selected:detailSource===group.sourceId&&detail?.id===item.id}" @click="open(group.sourceId,item)"><div class="poster-art"><img v-if="item.poster" :src="item.poster" :alt="item.name+' 海报'" loading="lazy"/><div v-else class="poster-placeholder">▶</div><span v-if="item.remark" class="poster-badge">{{item.remark}}</span></div><strong v-html="highlightName(item.name)"></strong></button></div><button v-if="group.items.length>PAGE_SIZE" class="text-link" @click="toggleGroup(group)">{{expandedGroups.has(group.sourceId)?'收起':`查看全部 ${group.items.length} 条`}}</button></section></template>
        <div v-else-if="!loading&&keyword.trim()" class="empty-state"><div class="empty-icon">⌕</div><h3>没有搜索到成功结果</h3><p>失败、超时或空结果来源不会显示在主结果区。</p></div><div v-else-if="!loading" class="empty-state"><div class="empty-icon">⌕</div><h3>输入关键词开始聚合搜索</h3><p>成功结果会按来源增量显示。</p></div>
      </div>
      <aside class="detail-rail search-detail"><template v-if="detail"><img v-if="detail.poster" class="detail-poster" :src="detail.poster" :alt="detail.name+' 海报'"/><div v-else class="detail-poster placeholder">▶</div><h2>{{detail.name}}</h2><small>{{detailSourceName}}</small><p>{{detail.description||'该来源未提供简介。'}}</p><button class="secondary-button wide" @click="toggleFavorite">{{favorite?'★ 已收藏':'☆ 收藏'}}</button><div class="episode-heading"><strong>播放线路</strong><span>{{detail.episodes.length}}</span></div><div class="episode-grid"><button v-for="(episode,index) in detail.episodes" :key="episode.flag+episode.id" @click="play(episode.flag,episode.id,episode.name)">{{index+1}}</button></div></template><div v-else class="detail-empty"><span>⌕</span><h3>选择搜索结果</h3><p>详情与播放线路会显示在这里。</p></div></aside>
    </div>
  </section>
</template>

<style scoped>
.search-suggestions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:0 0 12px}.search-suggestions>button:not(.text-link){padding:5px 9px;border:1px solid var(--line);border-radius:999px;background:var(--panel)}.suggestion-chip{display:inline-flex;align-items:center;border:1px solid var(--line);border-radius:999px;background:var(--panel);overflow:hidden}.suggestion-chip button{border:0;background:transparent;padding:5px 4px 5px 9px}.failure-chip>span{padding:5px 4px 5px 9px;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.failure-chip button{padding:5px 9px 5px 4px}.chip-remove{padding:5px 9px 5px 4px!important;color:var(--muted)}.clear-button{border:0;background:transparent;font-size:16px;color:var(--muted);padding:0 4px}.live-search-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px}.live-search-list button{display:flex;flex-direction:column;gap:3px;padding:10px;border:1px solid var(--line);border-radius:9px;background:var(--soft);text-align:left}.live-search-list small{color:var(--muted)}strong:has(mark) mark{background:var(--accent-soft);color:var(--accent-strong);padding:0 1px;border-radius:2px}
</style>
