<script setup lang="ts">
import { computed,nextTick,onBeforeUnmount,onMounted,ref } from 'vue';
import { useRoute } from 'vue-router';
import type { ProgramReservation } from '@free-new-desk/contracts';

type CacheStats={bytes:number;files:number;maxBytes:number;namespaces:Array<{namespace:string;bytes:number;files:number}>};
type DiagnosticEvent={time:string;level:string;category:string;message:string};
const route=useRoute();
type UpdateInfo={current:string;latest:string;available:boolean;url:string;channel:'stable'|'daily';checkedAt:string};

const info=ref<{version:string;platform:string;arch:string;theme:string}|null>(null);
const settings=ref<Record<string,string>>({});
const diagnostics=ref<Record<string,string|number|boolean>>({});
const reservations=ref<ProgramReservation[]>([]);
const cacheStats=ref<CacheStats>({bytes:0,files:0,maxBytes:0,namespaces:[]});
const events=ref<DiagnosticEvent[]>([]);
const theme=ref('system');
const fontScale=ref('1');
const showAllReservations=ref(false);
const cacheLimit=ref(String(1024*1024*1024));
const message=ref('');
const updateInfo=ref<UpdateInfo|null>(null);
const updateChannel=ref<'stable'|'daily'>('stable');
const autoCheck=ref(true);
const updateSchedule=ref<'off'|'daily'|'weekly'>('daily');
const diagnosticProgress=ref(0);const eventLimit=ref(24);const eventFilter=ref('');const selectedEvent=ref<DiagnosticEvent|null>(null);
const busy=ref(false);
const defaultVolume=ref(80);const autoNext=ref(true);const liveAutoFallback=ref(true);const proxyMode=ref<'proxy'|'direct'>('proxy');const timeoutSeconds=ref(15);
const selfTestRunning=ref(false);const selfTestProgress=ref(0);const selfTestResults=ref<Array<{name:string;ok:boolean;detail:string}>>([]);let selfTestCancel=false;const selfTestTotal=6;
function persistDefaultVolume(){localStorage.setItem('player.volume',String(defaultVolume.value));message.value='新会话默认音量已保存';}
async function saveAutoNext(){autoNext.value=!autoNext.value;await window.desktop.settings.set('player.autoNext',String(autoNext.value));message.value=`播完自动下一集：${autoNext.value?'开启':'关闭'}`;}
async function saveLiveFallback(){liveAutoFallback.value=!liveAutoFallback.value;await window.desktop.settings.set('live.autoFallback',String(liveAutoFallback.value));message.value=`直播自动切换线路：${liveAutoFallback.value?'开启':'关闭'}`;}
async function saveProxyMode(){await window.desktop.settings.set('network.proxyMode',proxyMode.value);message.value=proxyMode.value==='direct'?'代理模式已保存：直连（重启应用后生效）':'代理模式已保存：内置代理（重启应用后生效）';}
async function saveTimeout(){const value=Math.round(Number(timeoutSeconds.value));if(!Number.isFinite(value)||value<3||value>120){message.value='连接超时必须在 3–120 秒之间';timeoutSeconds.value=15;return;}await window.desktop.settings.set('network.timeoutSeconds',String(value));message.value=`连接超时已保存：${value} 秒`;}
async function runSelfTest(){if(selfTestRunning.value){selfTestCancel=true;message.value='正在取消自检…';return;}selfTestCancel=false;selfTestRunning.value=true;selfTestResults.value=[];selfTestProgress.value=0;message.value='正在运行自检…';try{for(let index=0;index<selfTestTotal;index++){if(selfTestCancel){message.value='自检已取消';return;}try{selfTestResults.value=[...selfTestResults.value,await window.desktop.diagnostics.selfTestItem(index)];}catch(error){selfTestResults.value=[...selfTestResults.value,{name:`第 ${index+1} 项`,ok:false,detail:error instanceof Error?error.message:String(error)}];}selfTestProgress.value=Math.round((index+1)/selfTestTotal*100);}const failed=selfTestResults.value.filter(item=>!item.ok).length;message.value=failed?`自检完成：${selfTestTotal-failed}/${selfTestTotal} 项通过`:`自检完成：全部 ${selfTestTotal} 项通过`;}finally{selfTestRunning.value=false;}}

const cachePercent=computed(()=>cacheStats.value.maxBytes?Math.min(100,Math.round(cacheStats.value.bytes/cacheStats.value.maxBytes*100)):0);
const activeReservations=computed(()=>reservations.value.filter(item=>Date.parse(item.start)>Date.now()-2*60*60*1000));const shownReservations=computed(()=>{const sorted=[...reservations.value].sort((a,b)=>Date.parse(b.start)-Date.parse(a.start));return showAllReservations.value?sorted:sorted.filter(item=>Date.parse(item.start)>Date.now()-24*60*60*1000).slice(0,8);});const reservationConflicts=computed(()=>{const sorted=[...activeReservations.value].sort((a,b)=>Date.parse(a.start)-Date.parse(b.start));const ids=new Set<string>();for(let i=1;i<sorted.length;i++){const prev=sorted[i-1],cur=sorted[i];if(prev&&cur&&Math.abs(Date.parse(cur.start)-Date.parse(prev.start))<30*60*1000){ids.add(prev.id);ids.add(cur.id);}}return ids;});const filteredEvents=computed(()=>events.value.filter(item=>(item.level+' '+item.category+' '+item.message).toLowerCase().includes(eventFilter.value.trim().toLowerCase())));const lastCheck=computed(()=>settings.value['update.lastCheck']?new Date(settings.value['update.lastCheck']).toLocaleString():'尚未检查');
function formatBytes(value:number){if(value<=0)return'0 B';const units=['B','KB','MB','GB'];let n=value,i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return n.toFixed(i?1:0)+' '+units[i];}
function namespaceLabel(value:string){const labels:Record<string,string>={image:'图片缓存',images:'图片缓存',epg:'EPG 节目单',http:'网络请求',source:'来源数据',proxy:'代理数据'};return labels[value]??value;}
function applyTheme(value:string){const resolved=value==='dark'||(value==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light';document.documentElement.style.colorScheme=resolved;document.documentElement.dataset.themePreference=value;document.documentElement.dataset.theme=resolved;}
function applyFontScale(value:string){const parsed=Number(value);const scale=Number.isFinite(parsed)?Math.max(.9,Math.min(1.5,parsed)):1;document.documentElement.style.setProperty('--font-scale',String(scale));}
function parseLastUpdate(value:string|undefined):UpdateInfo|null{if(!value)return null;try{const item=JSON.parse(value) as UpdateInfo;return item&&typeof item.current==='string'&&typeof item.latest==='string'?item:null;}catch{return null;}}
async function load(){busy.value=true;try{const [appInfo,settingValues,diag,reservationValues,cacheValues,eventValues]=await Promise.all([window.desktop.app.getInfo(),window.desktop.settings.list(),window.desktop.diagnostics.get(),window.desktop.reservation.list(),window.desktop.cache.stats(),window.desktop.diagnostics.events(24)]);info.value=appInfo;settings.value=settingValues;diagnostics.value=diag;reservations.value=reservationValues;cacheStats.value=cacheValues;events.value=eventValues;theme.value=settings.value.theme??'system';applyTheme(theme.value);fontScale.value=settings.value['ui.fontScale']??'1';applyFontScale(fontScale.value);cacheLimit.value=settings.value['cache.maxBytes']??String(cacheStats.value.maxBytes||1024*1024*1024);updateChannel.value=settings.value['update.channel']==='daily'?'daily':'stable';autoCheck.value=settings.value['update.autoCheck']!=='false';updateSchedule.value=(settings.value['update.schedule']==='weekly'?'weekly':settings.value['update.schedule']==='off'?'off':'daily');updateInfo.value=parseLastUpdate(settings.value['update.lastResult']);autoNext.value=settings.value['player.autoNext']!=='false';liveAutoFallback.value=settings.value['live.autoFallback']!=='false';proxyMode.value=settings.value['network.proxyMode']==='direct'?'direct':'proxy';const timeoutRaw=Number(settings.value['network.timeoutSeconds']);timeoutSeconds.value=Number.isFinite(timeoutRaw)&&timeoutRaw>=3&&timeoutRaw<=120?timeoutRaw:15;const persistedVolume=Number(localStorage.getItem('player.volume'));defaultVolume.value=Number.isFinite(persistedVolume)&&localStorage.getItem('player.volume')!==null?Math.min(100,Math.max(0,persistedVolume)):80;}finally{busy.value=false;}}
async function saveTheme(){await window.desktop.settings.set('theme',theme.value);applyTheme(theme.value);message.value='主题设置已保存并应用';}
async function saveFontScale(){await window.desktop.settings.set('ui.fontScale',fontScale.value);applyFontScale(fontScale.value);message.value='界面字号已保存并应用';}
async function saveCache(){await window.desktop.settings.set('cache.maxBytes',cacheLimit.value);cacheStats.value=await window.desktop.cache.stats();message.value='缓存容量已保存';}
async function clearCache(namespace?:string){if(!namespace&&!window.confirm('确认清理全部缓存？图片、EPG 与网络缓存将被清空，来源与收藏不受影响。'))return;await window.desktop.cache.clear(namespace);cacheStats.value=await window.desktop.cache.stats();message.value=namespace?`${namespaceLabel(namespace)}已清理`:'全部缓存已清理';}
async function saveUpdatePrefs(){await Promise.all([window.desktop.settings.set('update.channel',updateChannel.value),window.desktop.settings.set('update.autoCheck',String(updateSchedule.value!=='off')),window.desktop.settings.set('update.schedule',updateSchedule.value)]);settings.value=await window.desktop.settings.list();message.value=`更新设置已保存：${updateChannel.value==='daily'?'每日通道':'稳定版'} · ${updateSchedule.value==='off'?'关闭自动检查':updateSchedule.value==='weekly'?'每周检查':'每日检查'}`;}
async function checkUpdate(){busy.value=true;try{updateInfo.value=await window.desktop.update.check(updateChannel.value);settings.value=await window.desktop.settings.list();message.value=updateInfo.value.available?`发现新版本 ${updateInfo.value.latest}`:`当前 ${updateInfo.value.current} 已是此通道最新版本`;}catch(error){message.value=error instanceof Error?error.message:String(error);}finally{busy.value=false;}}
async function openReleases(){await window.desktop.update.openReleases();}
async function exportDiagnostics(){diagnosticProgress.value=10;message.value='正在收集系统与来源信息…';try{await new Promise(resolve=>setTimeout(resolve,100));diagnosticProgress.value=45;message.value='正在打包日志与播放器状态…';const result=await window.desktop.diagnostics.export();diagnosticProgress.value=100;message.value=result.canceled?'已取消导出':`诊断包已导出：${result.path}`;}catch(error){message.value=error instanceof Error?error.message:String(error);}finally{setTimeout(()=>{diagnosticProgress.value=0;},1500);}}
async function openPath(kind:'logs'|'temp'|`cache:${string}`){try{const result=await window.desktop.maintenance.openPath(kind);message.value=result.error?`打开失败：${result.error}`:`已打开：${result.path}`;}catch(error){message.value=error instanceof Error?error.message:String(error);}}
async function refreshEvents(){events.value=await window.desktop.diagnostics.events(eventLimit.value);message.value='诊断事件已刷新';}
async function showAllEvents(){eventLimit.value=1000;await refreshEvents();}
async function copyValue(value:unknown){await window.desktop.app.action({copy:String(value??'')});message.value='版本号已复制到剪贴板';}
function reservationState(item:ProgramReservation){const start=Date.parse(item.start),now=Date.now();if(start<now-2*60*60*1000)return'已结束';if(start<=now)return'进行中';return'即将开始';}
async function removeReservation(id:string){await window.desktop.reservation.remove(id);reservations.value=await window.desktop.reservation.list();}
function dialogEscape(event:KeyboardEvent){if(event.key!=='Escape')return;if(selectedEvent.value){selectedEvent.value=null;return;}}
onMounted(async()=>{window.addEventListener('keydown',dialogEscape);await load();if(route.query.section==='update'){await nextTick();document.querySelector('.update-card')?.scrollIntoView({behavior:'smooth',block:'center'});}if(route.query.section==='diagnostics'){await nextTick();document.querySelector('.diagnostic-events')?.scrollIntoView({behavior:'smooth',block:'center'});}});
onBeforeUnmount(()=>{window.removeEventListener('keydown',dialogEscape);});
</script>

<template>
  <section class="page settings-page">
    <section class="page-banner settings-banner"><div><h1>设置与诊断</h1><p>管理外观、更新通道、分类缓存与系统诊断，所有更新只来自本仓库。</p></div><div class="banner-stilllife"><i/><b/></div></section>

    <div class="settings-card-grid">
      <article class="setting-card"><span class="panel-kicker">外观</span><h2>主题</h2><div class="segmented"><button :class="{active:theme==='system'}" @click="theme='system';saveTheme()">系统</button><button :class="{active:theme==='light'}" @click="theme='light';saveTheme()">浅色</button><button :class="{active:theme==='dark'}" @click="theme='dark';saveTheme()">深色</button></div><label>界面字号<select v-model="fontScale" aria-label="界面字号" @change="saveFontScale"><option value="0.9">90%</option><option value="1">100%</option><option value="1.1">110%</option><option value="1.25">125%</option><option value="1.5">150%</option></select></label></article>

      <article class="setting-card"><span class="panel-kicker">播放</span><h2>播放行为</h2><label>新会话默认音量<input type="range" min="0" max="100" v-model.number="defaultVolume" aria-label="默认音量" @change="persistDefaultVolume"/><b class="inline-value">{{defaultVolume}}</b></label><label class="check-line"><input type="checkbox" :checked="autoNext" @change="saveAutoNext"/>播完自动播放下一集</label><label class="check-line"><input type="checkbox" :checked="liveAutoFallback" @change="saveLiveFallback"/>直播失败自动切换线路</label></article>

      <article class="setting-card"><span class="panel-kicker">网络</span><h2>代理与超时</h2><label>代理模式<select v-model="proxyMode" aria-label="代理模式" @change="saveProxyMode"><option value="proxy">内置代理（默认）</option><option value="direct">直连</option></select></label><label>连接超时（秒）<input v-model.number="timeoutSeconds" type="number" min="3" max="120" step="1" aria-label="连接超时秒数" @change="saveTimeout"/></label><small>代理与超时用于来源/EPG/配置下载请求；切换代理模式后重启应用生效。</small></article>

      <article class="setting-card update-card"><span class="panel-kicker">更新与通道</span><h2>{{updateInfo?.available?`发现 ${updateInfo.latest}`:updateChannel==='daily'?'每日通道':'稳定版'}}</h2><div class="segmented"><button :class="{active:updateChannel==='stable'}" @click="updateChannel='stable';saveUpdatePrefs()">稳定版</button><button :class="{active:updateChannel==='daily'}" @click="updateChannel='daily';saveUpdatePrefs()">每日</button></div><label>自动检查<select v-model="updateSchedule" @change="saveUpdatePrefs"><option value="off">关闭</option><option value="daily">每日</option><option value="weekly">每周</option></select></label><small>上次检查：{{lastCheck}}</small><div class="row-actions"><button class="secondary-button" :disabled="busy" @click="checkUpdate">立即检查</button><button class="text-link" @click="openReleases">GitHub Releases</button></div></article>

      <article class="setting-card cache-card"><span class="panel-kicker">缓存管理</span><h2>{{formatBytes(cacheStats.bytes)}}</h2><span>{{cacheStats.files}} 个文件 · {{cachePercent}}% 上限</span><select v-model="cacheLimit" @change="saveCache"><option :value="String(512*1024*1024)">上限 512 MB</option><option :value="String(1024*1024*1024)">上限 1 GB</option><option :value="String(2*1024*1024*1024)">上限 2 GB</option><option :value="String(4*1024*1024*1024)">上限 4 GB</option></select><div class="cache-namespaces"><div v-for="item in cacheStats.namespaces" :key="item.namespace"><span><strong>{{namespaceLabel(item.namespace)}}</strong><small>{{formatBytes(item.bytes)}} · {{item.files}} 项</small></span><span class="row-actions"><button @click="openPath(`cache:${item.namespace}`)">打开</button><button @click="clearCache(item.namespace)">清理</button></span></div><div v-if="cacheStats.namespaces.length===0" class="compact-empty">暂无缓存。</div></div><button class="secondary-button" @click="clearCache()">清理全部缓存</button></article>

      <article class="setting-card version-info"><span class="panel-kicker">组件版本（点击复制）</span><dl><div v-for="entry in [{k:'应用',v:info?.version},{k:'Source Engine',v:diagnostics.sourceEngineVersion},{k:'JVM Spider Host',v:diagnostics.jvmSpiderHostVersion},{k:'Plugin SDK',v:diagnostics.pluginSdkVersion},{k:'Electron',v:diagnostics.electron},{k:'Node',v:diagnostics.node},{k:'数据库',v:'Schema '+(diagnostics.databaseVersion??'—')},{k:'Windows',v:diagnostics.windowsBuild}]" :key="entry.k" role="button" tabindex="0" @click="copyValue(entry.v)" @keyup.enter="copyValue(entry.v)"><dt>{{entry.k}}</dt><dd>{{entry.v??'—'}}</dd></div></dl></article>
      <article class="setting-card java-runtime-card"><span class="panel-kicker">Java Runtime</span><h2>{{diagnostics.javaAvailable?`Java ${diagnostics.javaMajor??'17+'}`:'未检测到 Java 17+'}}</h2><span>{{diagnostics.javaAvailable?(diagnostics.javaVersion??'已发现'):'JAR 来源当前不可执行'}}</span><small :title="String(diagnostics.javaCommand??'')">{{diagnostics.javaAvailable?String(diagnostics.javaCommand??'java'):'请安装 Java 17+ 或设置 FREE_NEW_DESK_JAVA'}}</small><span>JAR：{{diagnostics.jarSourceCount??0}} 个 · 受限 {{diagnostics.jarRestrictedCount??0}} 个</span></article>
    </div>

    <section class="panel system-panel"><div class="panel-heading"><div><span class="panel-kicker">系统信息</span><h2>运行环境</h2></div></div><div class="system-grid"><div><small>CPU</small><strong>{{diagnostics.cpu??'—'}}</strong><span>{{diagnostics.cpuCores??'—'}} 线程</span></div><div><small>GPU</small><strong :title="String(diagnostics.gpu??'—')">{{String(diagnostics.gpu??'—').slice(0,52)}}</strong><span>硬件解码：{{diagnostics.hardwareDecode??'—'}}</span></div><div><small>内存</small><strong>{{diagnostics.memoryGB??'—'}} GB</strong><span>系统总内存</span></div><div><small>数据库</small><strong>Schema {{diagnostics.databaseVersion??'—'}}</strong><span>{{diagnostics.sourceCount??0}} 点播 · {{diagnostics.liveSourceCount??0}} 直播来源</span></div></div></section>

    <div class="maintenance-grid"><button class="maintenance-card" @click="exportDiagnostics"><strong>导出诊断包</strong><span>日志、来源健康与播放器运行状态</span></button><button class="maintenance-card" @click="runSelfTest"><strong>{{selfTestRunning?'取消自检':'运行自检'}}</strong><span>逐项检查来源/数据库/缓存/日志/播放器/网络</span></button><button class="maintenance-card" @click="openPath('logs')"><strong>打开日志目录</strong><span>查看 app.log 与轮转日志</span></button><button class="maintenance-card" @click="openPath('temp')"><strong>打开临时目录</strong><span>检查临时文件与诊断中间文件</span></button></div>
    <div v-if="selfTestResults.length||selfTestRunning" class="panel selftest-panel"><div class="panel-heading"><div><span class="panel-kicker">运行自检</span><h2>{{selfTestRunning?`正在检查（${selfTestResults.length}/${selfTestTotal}）`:`自检结果（${selfTestResults.filter(item=>item.ok).length}/${selfTestTotal} 通过）`}}</h2></div></div><progress v-if="selfTestRunning||selfTestProgress>=100" :value="selfTestRunning?selfTestProgress:100" max="100" aria-label="自检进度"/><dl class="selftest-list"><div v-for="item in selfTestResults" :key="item.name"><dt>{{item.name}}</dt><dd :class="item.ok?'good':'danger'">{{item.ok?'通过':'失败'}} · {{item.detail}}</dd></div></dl></div>
    <progress v-if="diagnosticProgress" :value="diagnosticProgress" max="100" aria-label="诊断包导出进度"/><p v-if="message" class="status-line" role="status" aria-live="polite">{{message}}</p>

    <section class="settings-bottom-grid">
      <article class="panel"><div class="panel-heading"><div><span class="panel-kicker">节目预约</span><h2>{{activeReservations.length}} 项</h2></div></div><div v-if="shownReservations.length" class="reservation-list"><div v-for="item in shownReservations" :key="item.id"><time>{{new Date(item.start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}}</time><span class="reservation-state" :class="reservationState(item)">{{reservationState(item)}}</span><div><strong>{{item.programTitle}}</strong><small>{{item.channelName}} · {{new Date(item.start).toLocaleDateString()}} <b v-if="reservationConflicts.has(item.id)" class="error-text">时间冲突</b></small></div><button @click="removeReservation(item.id)">取消</button></div></div><div v-else class="compact-empty">暂无节目预约。</div><button v-if="reservations.length>shownReservations.length||showAllReservations" class="text-link" @click="showAllReservations=!showAllReservations">{{showAllReservations?'收起':'查看全部'}}</button></article>
      <article class="panel diagnostic-events"><div class="panel-heading"><div><span class="panel-kicker">诊断事件</span><h2>最近运行记录</h2></div><div class="row-actions"><input v-model="eventFilter" placeholder="过滤事件" aria-label="过滤诊断事件"/><select v-model.number="eventLimit" @change="refreshEvents"><option :value="24">24 条</option><option :value="100">100 条</option><option :value="1000">1000 条</option></select><button class="text-link" @click="refreshEvents">刷新</button><button class="text-link" @click="showAllEvents">查看全部</button></div></div><div v-if="events.length" class="event-list"><div v-for="item in filteredEvents" :key="item.time+item.category+item.message" role="button" tabindex="0" @click="selectedEvent=item" @keyup.enter="selectedEvent=item"><time>{{new Date(item.time).toLocaleTimeString()}}</time><span class="event-level" :class="item.level.toLowerCase()">{{item.level}}</span><div><strong>{{item.category}}</strong><small>{{item.message}}</small></div></div></div><div v-else class="compact-empty">暂无诊断事件。</div></article>
    </section><dialog :open="Boolean(selectedEvent)" class="event-dialog"><article v-if="selectedEvent"><h3>诊断事件详情</h3><pre>{{JSON.stringify(selectedEvent,null,2)}}</pre><div class="row-actions"><button class="secondary-button" @click="copyValue(JSON.stringify(selectedEvent,null,2))">复制详情</button><button @click="selectedEvent=null">关闭</button></div></article></dialog>
  </section>
</template>

<style scoped>
.update-card,.cache-card{display:flex;flex-direction:column;gap:9px}.check-line{display:flex;gap:7px;align-items:center;font-size:12px}.cache-namespaces{display:flex;flex-direction:column;gap:5px;max-height:150px;overflow:auto}.cache-namespaces>div:not(.compact-empty){display:flex;justify-content:space-between;align-items:center;gap:8px;padding:6px 0;border-bottom:1px solid var(--line)}.cache-namespaces span,.cache-namespaces strong,.cache-namespaces small{display:block}.cache-namespaces small{color:var(--muted);font-size:10px}.event-list{max-height:320px;overflow:auto}.event-list>div{display:grid;grid-template-columns:72px 48px 1fr;gap:8px;align-items:start;padding:7px 0;border-bottom:1px solid var(--line)}.event-list time{font-size:10px;color:var(--muted)}.event-level{font-size:9px;font-weight:700}.event-list strong,.event-list small{display:block}.event-list small{color:var(--muted);word-break:break-word}.event-level.info{color:#27834b}.event-level.warn,.event-level.error,.event-level.fatal{color:var(--warning,#9a681f)}.reservation-state{font-size:10px;font-weight:700}.reservation-state.即将开始{color:#b85c00}.reservation-state.进行中{color:#27834b}.reservation-state.已结束{color:var(--muted)}.event-dialog{z-index:2000;max-width:620px;border:1px solid var(--line);border-radius:12px;background:var(--panel);color:inherit}.event-dialog pre{white-space:pre-wrap;word-break:break-word}
.selftest-panel{display:grid;gap:8px;margin-top:10px}.selftest-list{margin:0}.selftest-list>div{display:flex;justify-content:space-between;gap:14px;padding:7px 0;border-top:1px solid var(--line)}.selftest-list dd{margin:0;font-size:12px;text-align:right}.selftest-list dd.good{color:var(--good)}.selftest-list dd.danger{color:var(--danger)}.setting-card .inline-value{min-width:28px;text-align:right;font-variant-numeric:tabular-nums}
</style>