<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref } from 'vue';
import { useRoute,useRouter } from 'vue-router';
import type { DetailResult,HomeResult,SourceConfig,VideoCard } from '@free-new-desk/contracts';
import { isVodFavorite,toggleVodFavorite } from '../favorites';
import { emitPlaybackStage } from '../playback-events';
import { usePageStateStore } from '../stores/page-state';

const router=useRouter();const route=useRoute();const pageState=usePageStateStore();
const showFilters=ref(false);const contextItem=ref<VideoCard|null>(null);const contextX=ref(0);const contextY=ref(0);const sources=ref<SourceConfig[]>([]);const sourceId=ref('');const items=ref<VideoCard[]>([]);const homeMeta=ref<HomeResult|null>(null);const detail=ref<DetailResult|null>(null);const favorite=ref(false);const keyword=ref('');const loading=ref(false);const error=ref('');const categoryId=ref('');const manualCategoryId=ref('');const categoryPage=ref(1);const categoryHasMore=ref(false);const totalPages=ref(1);const totalItems=ref<number|null>(null);const pageInput=ref(1);const filterValues=ref<Record<string,string>>({});const mode=ref<'home'|'category'|'search'>('home');const viewMode=ref<'grid'|'list'>(localStorage.getItem('vod.viewMode')==='list'?'list':'grid');const selectedFlag=ref('');const nowPlaying=ref<{videoId:string;episodeId:string}|null>(null);const sortMode=ref<'default'|'rating'|'newest'|'popular'|'name'>('default');const episodePage=ref(1);const fixedCategories=['全部','电影','电视剧','综艺','动漫','纪录片','短剧'];let searchTimer:ReturnType<typeof setTimeout>|undefined;
function setViewMode(next:'grid'|'list'){viewMode.value=next;localStorage.setItem('vod.viewMode',next);}
interface VodSession{categoryId?:string;page?:number;filters?:Record<string,string>;sortMode?:typeof sortMode.value;showFilters?:boolean;detailId?:string|undefined;}
interface VodPageSnapshot{sources:SourceConfig[];sourceId:string;items:VideoCard[];homeMeta:HomeResult|null;detail:DetailResult|null;favorite:boolean;categoryId:string;manualCategoryId:string;categoryPage:number;categoryHasMore:boolean;totalPages:number;totalItems:number|null;pageInput:number;filterValues:Record<string,string>;mode:'home'|'category'|'search';sortMode:'default'|'rating'|'newest'|'popular'|'name';episodePage:number;selectedFlag:string;showFilters:boolean;}
function sessionKey(id=sourceId.value){return`vod.session.${id}`;}
function readSession(id:string):VodSession{try{const value=JSON.parse(localStorage.getItem(sessionKey(id))??'{}') as VodSession;return value&&typeof value==='object'?value:{};}catch{return{};}}
function saveSession(extra:Partial<VodSession>={}){if(!sourceId.value)return;const value:VodSession={categoryId:categoryId.value,page:categoryPage.value,filters:{...filterValues.value},sortMode:sortMode.value,showFilters:showFilters.value,...extra};localStorage.setItem(sessionKey(),JSON.stringify(value));localStorage.setItem('vod.sourceId',sourceId.value);}
const sortedItems=computed(()=>{if(findSortOption(sortMode.value))return items.value;return items.value.map((item,index)=>({item,index})).sort((a,b)=>{let order=0;if(sortMode.value==='name')order=a.item.name.localeCompare(b.item.name);else if(sortMode.value==='rating')order=(Number(b.item.rating)||0)-(Number(a.item.rating)||0);else if(sortMode.value==='popular')order=(Number(b.item.remark?.match(/\d+/)?.[0])||0)-(Number(a.item.remark?.match(/\d+/)?.[0])||0);return order||a.index-b.index;}).map(entry=>entry.item);});const missingCategories=computed(()=>fixedCategories.slice(1).filter(name=>!categories.value.some(item=>item.name.includes(name))));const pagedEpisodes=computed(()=>visibleEpisodes.value.slice((episodePage.value-1)*20,episodePage.value*20));const episodePages=computed(()=>Math.max(1,Math.ceil(visibleEpisodes.value.length/20)));const enabledSources=computed(()=>sources.value.filter(source=>source.enabled));const selectedSource=computed(()=>sources.value.find(source=>source.id===sourceId.value));const categories=computed(()=>homeMeta.value?.categories??[]);const activeFilters=computed(()=>categoryId.value?(homeMeta.value?.filters?.[categoryId.value]??[]):[]);const displayFilters=computed(()=>{const values=[...activeFilters.value];const fallback=[{key:'class',name:'类型',options:['剧情','喜剧','动作','爱情','科幻','悬疑','惊悚','犯罪','冒险','奇幻','动画','纪录片'].map(value=>({label:value,value}))},{key:'area',name:'地区',options:['中国大陆','中国香港','中国台湾','美国','英国','法国','日本','韩国','印度','泰国','其他'].map(value=>({label:value,value}))},{key:'year',name:'年份',options:['2026','2025','2024','2023','2022','2021','2020','2010年代','2000年代','更早'].map(value=>({label:value,value}))}];for(const item of fallback)if(!values.some(value=>value.key===item.key))values.push(item);return values;});const episodeFlags=computed(()=>[...new Set(detail.value?.episodes.map(item=>item.flag)??[])]);const visibleEpisodes=computed(()=>detail.value?.episodes.filter(item=>!selectedFlag.value||item.flag===selectedFlag.value)??[]);const firstPageButton=computed(()=>pageButtons.value[0]??1);const lastPageButton=computed(()=>pageButtons.value.at(-1)??1);const pageButtons=computed(()=>{const start=Math.max(1,categoryPage.value-2);const end=Math.min(totalPages.value,categoryPage.value+2);return Array.from({length:Math.max(0,end-start+1)},(_,index)=>start+index);});const nextPageAvailable=computed(()=>mode.value==='category'&&items.value.length>0&&(categoryHasMore.value||categoryPage.value<totalPages.value));const nextPageLabel=computed(()=>nextPageAvailable.value?`加载下一页（第 ${categoryPage.value+1} 页）`:`已到最后一页（第 ${categoryPage.value} 页）`);
function clearDetail(persist:boolean|MouseEvent=true){detail.value=null;favorite.value=false;selectedFlag.value='';episodePage.value=1;if(persist===true)saveSession({detailId:undefined});}function resetCategory(){categoryId.value='';manualCategoryId.value='';categoryPage.value=1;pageInput.value=1;categoryHasMore.value=false;totalPages.value=1;totalItems.value=null;filterValues.value={};}
async function loadHome(force=false){if(!sourceId.value)return;loading.value=true;error.value='';clearDetail(false);resetCategory();mode.value='home';try{const result=await window.desktop.source.home(sourceId.value,force);homeMeta.value=result;items.value=result.items;saveSession({detailId:undefined});void router.replace({query:{source:sourceId.value}});}catch(value){error.value=value instanceof Error?value.message:String(value);items.value=[];homeMeta.value=null;}finally{loading.value=false;}}
async function loadCategory(page=1,force=false){if(!sourceId.value||!categoryId.value)return;loading.value=true;error.value='';clearDetail(false);mode.value='category';try{const entries=Object.entries(filterValues.value).filter(([,value])=>value!=='');let combinations:Array<Record<string,string>>=[{}];for(const [key,value] of entries){const options=value.split(',').filter(Boolean);combinations=combinations.flatMap(base=>options.map(option=>({...base,[key]:option}))).slice(0,20);}const results=await Promise.all((combinations.length?combinations:[{}]).map(filters=>window.desktop.source.category(sourceId.value,categoryId.value,Math.max(1,page),filters,force)));const result={...results[0]!,items:[...new Map(results.flatMap(value=>value.items).map(item=>[item.id,item])).values()],hasMore:results.some(value=>value.hasMore),totalPages:Math.max(...results.map(value=>value.totalPages??value.page)),totalItems:results.length===1?results[0]?.totalItems:undefined};items.value=result.items;categoryPage.value=result.page;pageInput.value=result.page;categoryHasMore.value=result.hasMore;totalPages.value=Math.max(1,result.totalPages??(result.hasMore?result.page+1:result.page));totalItems.value=result.totalItems??null;saveSession({detailId:undefined});void router.replace({query:{source:sourceId.value,category:categoryId.value,page:String(result.page)}});}catch(value){error.value=value instanceof Error?value.message:String(value);items.value=[];}finally{loading.value=false;}}
function toggleFilter(key:string,value:string){const current=new Set((filterValues.value[key]??'').split(',').filter(Boolean));current.has(value)?current.delete(value):current.add(value);filterValues.value[key]=[...current].join(',');void applyFilters();}
async function selectCategory(id:string){categoryId.value=id;manualCategoryId.value=id;categoryPage.value=1;pageInput.value=1;filterValues.value={};await loadCategory(1);}async function openManualCategory(){const id=manualCategoryId.value.trim();if(!id)return;categoryId.value=id;filterValues.value={};await loadCategory(1);}async function applyFilters(){await loadCategory(1);}async function jumpPage(){const requested=Math.floor(pageInput.value||1);if(requested<1||requested>totalPages.value){error.value=`页码必须在 1–${totalPages.value} 之间`;return;}await loadCategory(requested);}
async function toggleFiltersPanel(){const next=!showFilters.value;showFilters.value=next;if(next&&!categoryId.value&&categories.value.length){await selectCategory(categories.value[0]!.id);showFilters.value=true;}saveSession();}
function scheduleSearch(){if(searchTimer)clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(keyword.value.trim())void router.push({path:'/search',query:{q:keyword.value.trim()}});},300);}
async function search(){const value=keyword.value.trim();if(!value)return;await router.push({path:'/search',query:{q:value}});}
async function loadSource(force=false){if(!sourceId.value)return;localStorage.setItem('vod.sourceId',sourceId.value);const saved=readSession(sourceId.value);loading.value=true;error.value='';try{const home=await window.desktop.source.home(sourceId.value,force);homeMeta.value=home;showFilters.value=Boolean(saved.showFilters);sortMode.value=saved.sortMode??'default';categoryId.value=saved.categoryId??'';manualCategoryId.value=categoryId.value;filterValues.value=saved.filters??{};if(categoryId.value)await loadCategory(Math.max(1,saved.page??1),force);else{mode.value='home';items.value=home.items;categoryPage.value=1;pageInput.value=1;totalItems.value=null;categoryHasMore.value=false;totalPages.value=1;}if(saved.detailId)await openVideo({id:saved.detailId,name:saved.detailId} as VideoCard,force);else saveSession({detailId:undefined});}catch(value){error.value=value instanceof Error?value.message:String(value);items.value=[];homeMeta.value=null;}finally{loading.value=false;}}
async function changeSource(){await loadSource(false);}
async function refreshSource(){await loadSource(true);}
async function openVideo(item:VideoCard,force=false){error.value='';try{detail.value=await window.desktop.source.detail(sourceId.value,[item.id],force);selectedFlag.value=detail.value.episodes[0]?.flag??'';favorite.value=await isVodFavorite(sourceId.value,detail.value.id);saveSession({detailId:detail.value.id});}catch(value){error.value=value instanceof Error?value.message:String(value);}}
function findSortOption(mode:typeof sortMode.value){const filter=activeFilters.value.find(item=>/sort|order|排序|按/.test(`${item.key} ${item.name}`.toLowerCase()));if(!filter)return null;const patterns={rating:/评分|rating|score/i,newest:/最新|时间|new|time|date/i,popular:/热门|热度|播放|hits|popular/i,name:/名称|name/i};const option=mode==='default'?undefined:filter.options.find(item=>patterns[mode].test(`${item.label} ${item.value}`));return option?{filter,option}:null;}
async function changeSort(){if(sortMode.value==='default'){saveSession();return;}const remote=findSortOption(sortMode.value);if(remote&&categoryId.value){filterValues.value[remote.filter.key]=remote.option.value;await loadCategory(1);return;}const supported=sortMode.value==='name'||(sortMode.value==='rating'&&items.value.some(item=>item.rating))||(sortMode.value==='popular'&&items.value.some(item=>/\d/.test(item.remark??'')));if(!supported){const label={rating:'评分',newest:'上架时间',popular:'播放量',name:'名称'}[sortMode.value];error.value=`当前来源未提供${label}排序字段，已保持来源默认顺序。`;sortMode.value='default';}saveSession();}
async function toggleFavorite(){if(!detail.value||!selectedSource.value)return;favorite.value=await toggleVodFavorite(sourceId.value,selectedSource.value.name,detail.value);}async function play(flag:string,episodeId:string,episodeName:string){if(!detail.value)return;error.value='';const request={sourceId:sourceId.value,videoId:detail.value.id,videoName:detail.value.name,flag,episodeId,episodeName,...(detail.value.poster?{poster:detail.value.poster}:{}),episodeListJson:JSON.stringify(detail.value.episodes)};nowPlaying.value={videoId:detail.value.id,episodeId};localStorage.setItem('vod.nowPlaying',JSON.stringify(nowPlaying.value));const navigationStarted=performance.now();await router.push('/player');const navigationMs=performance.now()-navigationStarted;void window.desktop.diagnostics.recordPerformance('playbackNavigationMs',navigationMs).catch(()=>false);if(window.desktop.app.isUiSmoke()&&navigationMs>150)throw new Error(`Playback navigation exceeded 150ms budget: ${navigationMs.toFixed(1)}ms`);emitPlaybackStage('source-resolving','正在获取点播线路…');void window.desktop.playback.play(request).then(()=>emitPlaybackStage('playing','媒体已打开')).catch(value=>{const message=value instanceof Error?value.message:String(value);emitPlaybackStage('failed','播放失败',message);});}
async function openAndPlay(item:VideoCard){await openVideo(item);await playFirst();}
function openContext(event:MouseEvent,item:VideoCard){contextItem.value=item;contextX.value=event.clientX;contextY.value=event.clientY;}
async function contextAction(action:'favorite'|'copy'|'play'|'window'){const item=contextItem.value;contextItem.value=null;if(!item)return;if(action==='copy')await window.desktop.app.action({copy:item.name});else if(action==='play')await openAndPlay(item);else if(action==='favorite'){await openVideo(item);await toggleFavorite();}else await window.desktop.app.openRoute(`/vod?source=${encodeURIComponent(sourceId.value)}&video=${encodeURIComponent(item.id)}`);}
function closeTransient(event:KeyboardEvent){if(event.key==='Escape'){showFilters.value=false;contextItem.value=null;clearDetail();}}
async function playFirst(){const episode=visibleEpisodes.value[0]??detail.value?.episodes[0];if(episode)await play(episode.flag,episode.id,episode.name);}
onMounted(async()=>{window.addEventListener('keydown',closeTransient);try{const parsed=JSON.parse(localStorage.getItem('vod.nowPlaying')??'null') as {videoId?:string;episodeId?:string}|null;if(parsed&&typeof parsed.videoId==='string'&&typeof parsed.episodeId==='string')nowPlaying.value={videoId:parsed.videoId,episodeId:parsed.episodeId};}catch{nowPlaying.value=null;}const cached=pageState.read<VodPageSnapshot>('vod');if(cached&&!route.query.source&&!route.query.category&&!route.query.video){const v=cached.value;sources.value=v.sources;sourceId.value=v.sourceId;items.value=v.items;homeMeta.value=v.homeMeta;detail.value=v.detail;favorite.value=v.favorite;categoryId.value=v.categoryId;manualCategoryId.value=v.manualCategoryId;categoryPage.value=v.categoryPage;categoryHasMore.value=v.categoryHasMore;totalPages.value=v.totalPages;totalItems.value=v.totalItems;pageInput.value=v.pageInput;filterValues.value={...v.filterValues};mode.value=v.mode;sortMode.value=v.sortMode;episodePage.value=v.episodePage;selectedFlag.value=v.selectedFlag;showFilters.value=v.showFilters;return;}sources.value=await window.desktop.source.list();const routeSource=typeof route.query.source==='string'?route.query.source:'';const savedSource=localStorage.getItem('vod.sourceId')??'';sourceId.value=[routeSource,savedSource].find(id=>enabledSources.value.some(item=>item.id===id))??enabledSources.value[0]?.id??'';if(sourceId.value){if(typeof route.query.category==='string'){const saved=readSession(sourceId.value);localStorage.setItem(sessionKey(sourceId.value),JSON.stringify({...saved,categoryId:route.query.category,page:Number(route.query.page)||1,detailId:typeof route.query.video==='string'?route.query.video:saved.detailId}));}await loadSource(false);if(typeof route.query.video==='string'&&detail.value?.id!==route.query.video)await openVideo({id:route.query.video,name:route.query.video} as VideoCard);}});
onBeforeUnmount(()=>{pageState.save<VodPageSnapshot>('vod',{sources:[...sources.value],sourceId:sourceId.value,items:[...items.value],homeMeta:homeMeta.value,detail:detail.value,favorite:favorite.value,categoryId:categoryId.value,manualCategoryId:manualCategoryId.value,categoryPage:categoryPage.value,categoryHasMore:categoryHasMore.value,totalPages:totalPages.value,totalItems:totalItems.value,pageInput:pageInput.value,filterValues:{...filterValues.value},mode:mode.value,sortMode:sortMode.value,episodePage:episodePage.value,selectedFlag:selectedFlag.value,showFilters:showFilters.value});window.removeEventListener('keydown',closeTransient);if(searchTimer)clearTimeout(searchTimer);});
</script>

<template>
  <section class="page vod-page">
    <div class="page-heading split"><div><h1>点播</h1><p>海量影视资源，支持多源解析、分类筛选与 TVBox 兼容接口。</p></div><div class="toolbar-group"><select v-model="sourceId" class="source-select" @change="changeSource"><option disabled value="">选择来源</option><option v-for="source in enabledSources" :key="source.id" :value="source.id">{{source.name}}</option></select><button class="secondary-button" :disabled="loading||!sourceId" @click="refreshSource">刷新来源</button><div class="search-box"><span>⌕</span><input v-model="keyword" maxlength="100" placeholder="搜索影片、演员、导演" data-search-input @input="scheduleSearch" @keyup.enter="search"/></div><button class="secondary-button" @click="search">搜索</button></div></div>

    <div class="vod-workspace">
      <div class="vod-main">
        <div class="section-tabs"><button :class="{active:mode==='home'&&!showFilters}" @click="showFilters=false;loadHome()">分类</button><button :class="{active:showFilters}" @click="toggleFiltersPanel">筛选</button><button :class="{active:mode==='home'&&!categoryId}" @click="showFilters=false;loadHome()">推荐</button><RouterLink to="/history">最近观看</RouterLink></div>
        <div v-if="sourceId" class="category-strip"><button class="chip" :class="{active:!categoryId&&mode==='home'}" @click="loadHome()">全部</button><button v-for="category in categories" :key="category.id" class="chip" :class="{active:categoryId===category.id}" @click="selectCategory(category.id)">{{category.name}}</button><button v-for="name in missingCategories" :key="'missing-'+name" class="chip" disabled :title="`当前来源未声明${name}分类`">{{name}}</button><template v-if="categories.length===0"><input v-model="manualCategoryId" class="inline-category" placeholder="分类 ID" @keyup.enter="openManualCategory"/><button class="chip" :disabled="!manualCategoryId.trim()" @click="openManualCategory">打开分类</button></template></div>
        <div v-if="showFilters&&!categoryId" class="filter-hint">当前来源尚未返回可用分类。请先点“刷新来源”；如果来源支持 CMS 分类，软件会自动尝试兼容的分类元数据接口。</div>
        <div v-if="showFilters&&categoryId&&displayFilters.length" class="filter-stack filter-drawer"><div v-for="filter in displayFilters" :key="filter.key" class="filter-row"><span>{{filter.name}}</span><button class="filter-option" :class="{active:!filterValues[filter.key]}" @click="filterValues[filter.key]='';applyFilters()">全部</button><button v-for="option in filter.options" :key="option.value" class="filter-option" :class="{active:(filterValues[filter.key]??'').split(',').includes(option.value)}" @click="toggleFilter(filter.key,option.value)">{{option.label}}</button></div></div>

        <p v-if="error" class="error-banner">{{error}}</p>
        <div v-if="!sourceId" class="empty-state"><div class="empty-icon">＋</div><h3>没有已启用来源</h3><p>前往“来源”导入 TVBox/FongMi 配置。</p></div>
        <div v-else-if="loading" class="loading-panel">正在加载内容…</div>
        <template v-else>
          <div class="results-bar"><span>共 {{totalItems??items.length}} 个结果</span><select v-model="sortMode" aria-label="点播排序" @change="changeSort"><option value="default">来源默认</option><option value="rating">评分最高</option><option value="newest">最新上架</option><option value="popular">最多播放</option><option value="name">名称</option></select><div v-if="mode==='category'" class="pagination numeric-pages"><button :disabled="categoryPage<=1" @click="loadCategory(categoryPage-1)">‹</button><span v-if="firstPageButton>1">…</span><button v-for="page in pageButtons" :key="page" :class="{active:page===categoryPage}" @click="loadCategory(page)">{{page}}</button><span v-if="lastPageButton<totalPages">…</span><button :disabled="!nextPageAvailable" @click="loadCategory(categoryPage+1)">›</button><input v-model.number="pageInput" type="number" min="1" aria-label="跳转页码" :max="totalPages" @keyup.enter="jumpPage"/><button @click="jumpPage">跳转</button></div><div class="view-toggle"><button :class="{active:viewMode==='grid'}" title="网格" @click="setViewMode('grid')">▦</button><button :class="{active:viewMode==='list'}" title="列表" @click="setViewMode('list')">☷</button></div></div>
          <div v-if="items.length" :class="viewMode==='grid'?'poster-grid cinematic':'vod-list-view'"><button v-for="item in sortedItems" :key="item.id" class="poster-card" :class="{selected:detail?.id===item.id,list:viewMode==='list'}" @click="openVideo(item)" @dblclick="openAndPlay(item)" @contextmenu.prevent="openContext($event,item)"><div class="poster-art"><img v-if="item.poster" :src="item.poster" :alt="item.name+' 海报'" loading="lazy"/><div v-else class="poster-placeholder">▶</div><span v-if="item.rating" class="score-badge">{{item.rating}}</span><span v-if="item.remark" class="poster-badge">{{item.remark}}</span></div><div class="poster-copy"><strong>{{item.name}}</strong><small v-if="viewMode==='list'">{{item.remark||'点击查看详情'}}</small></div></button></div>
          <button v-if="mode==='category'&&items.length" class="secondary-button load-next-page" :disabled="!nextPageAvailable" @click="loadCategory(categoryPage+1)">{{nextPageLabel}}</button><div v-if="items.length===0" class="empty-state compact"><h3>当前来源没有返回内容</h3><p>尝试切换分类、筛选条件或搜索。</p></div><div v-if="contextItem" class="vod-context-menu" :style="{left:contextX+'px',top:contextY+'px'}"><button @click="contextAction('play')">立即播放</button><button @click="contextAction('favorite')">收藏 / 取消收藏</button><button @click="contextAction('copy')">复制标题</button><button @click="contextAction('window')">新窗口打开</button></div>
        </template>
      </div>

      <aside class="vod-detail detail-rail">
        <template v-if="detail">
          <button class="rail-close" @click="clearDetail">×</button><img v-if="detail.poster" class="detail-poster" :src="detail.poster" :alt="detail.name+' 海报'"/><div v-else class="detail-poster placeholder">▶</div><div class="title-score"><h2>{{detail.name}}</h2><b v-if="detail.rating">★ {{detail.rating}}</b></div><small>{{detail.remark}}</small><div v-if="detail.year||detail.area||detail.type" class="detail-meta"><span v-if="detail.year">{{detail.year}}</span><span v-if="detail.area">{{detail.area}}</span><span v-if="detail.type">{{detail.type}}</span></div><p>{{detail.description||'该来源未提供简介。'}}</p><div v-if="detail.director||detail.actors?.length" class="people-meta"><p v-if="detail.director"><b>导演</b>{{detail.director}}</p><p v-if="detail.actors?.length"><b>演员</b><span class="actor-list"><i v-for="actor in detail.actors" :key="actor"><em>{{actor.slice(0,1)}}</em>{{actor}}</i></span></p></div><button class="primary-button wide" :disabled="detail.episodes.length===0" @click="playFirst">▶ 立即播放</button><button class="secondary-button wide" @click="toggleFavorite">{{favorite?'★ 已收藏':'☆ 收藏'}}</button><div v-if="episodeFlags.length>1" class="route-tabs"><strong>播放线路</strong><button v-for="flag in episodeFlags" :key="flag" :class="{active:selectedFlag===flag}" @click="selectedFlag=flag">{{flag}}</button></div><div class="episode-heading"><strong>剧集列表</strong><span>{{visibleEpisodes.length}} 集</span></div><div class="episode-grid"><button v-for="(episode,index) in pagedEpisodes" :key="episode.flag+episode.id" :class="{'now-playing':nowPlaying&&nowPlaying.videoId===detail.id&&nowPlaying.episodeId===episode.id}" :title="nowPlaying&&nowPlaying.videoId===detail.id&&nowPlaying.episodeId===episode.id?'当前正在播放':''" @click="play(episode.flag,episode.id,episode.name)">{{episode.name||index+1}}</button></div><div v-if="episodePages>1" class="episode-pagination"><button :disabled="episodePage<=1" @click="episodePage--">上一组</button><span>{{episodePage}} / {{episodePages}}</span><button :disabled="episodePage>=episodePages" @click="episodePage++">下一组</button></div>
        </template>
        <div v-else class="detail-empty"><span>▶</span><h3>选择一个条目</h3><p>影片详情、线路和剧集会显示在这里。</p></div>
      </aside>
    </div>
  </section>
</template>

<style scoped>
.view-toggle{display:flex;gap:3px}.view-toggle button{min-width:32px;height:30px;border:1px solid var(--line);background:var(--surface-1);border-radius:6px}.view-toggle button.active{background:var(--accent-soft);color:var(--accent)}.vod-list-view{display:flex;flex-direction:column;gap:7px}.poster-card.list{display:grid;grid-template-columns:70px 1fr;align-items:center;text-align:left;gap:12px;padding:7px}.poster-card.list .poster-art{aspect-ratio:2/3}.poster-copy{min-width:0}.poster-copy small{display:block;color:var(--muted);margin-top:4px}.score-badge{position:absolute;left:6px;top:6px;padding:2px 6px;border-radius:999px;background:rgba(18,18,18,.76);color:#fff;font-size:10px;font-weight:700}.numeric-pages input{width:54px;height:30px}.numeric-pages button.active{background:var(--accent);color:#fff}.title-score{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.title-score h2{margin:0}.title-score b{white-space:nowrap;color:var(--accent)}.detail-meta,.route-tabs{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.detail-meta span,.route-tabs button{padding:3px 7px;border-radius:999px;background:var(--surface-2);font-size:11px}.route-tabs strong{width:100%;font-size:11px}.route-tabs button.active{background:var(--accent-soft);color:var(--accent)}.people-meta{padding:8px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.people-meta p{margin:4px 0;font-size:12px}.people-meta b{display:inline-block;min-width:34px;margin-right:7px}.filter-hint{margin:8px 0;padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:var(--surface-2);color:var(--muted);font-size:12px;line-height:1.5}
.actor-list{display:flex;flex-wrap:wrap;gap:6px}.actor-list i{display:flex;align-items:center;gap:4px;font-style:normal}.actor-list em{display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:var(--accent-soft);font-style:normal}.episode-pagination{display:flex;justify-content:center;align-items:center;gap:8px;margin-top:8px}.episode-grid .now-playing{border-color:var(--accent);color:var(--accent-strong);background:var(--accent-soft);outline:1px solid var(--accent)}
</style>
<style scoped>
.vod-context-menu{position:fixed;z-index:5000;display:grid;min-width:150px;padding:6px;border:1px solid var(--line);border-radius:8px;background:var(--surface);box-shadow:0 12px 32px rgba(0,0,0,.2)}.vod-context-menu button{border:0;background:transparent;text-align:left;padding:8px;border-radius:5px}.vod-context-menu button:hover{background:var(--soft)}.filter-drawer{max-height:260px;overflow:auto}
.load-next-page{display:flex;margin:16px auto 4px}
</style>
