import path from 'node:path';
export const PLUGIN_API_VERSION='1' as const;
export interface PluginManifest {id:string;name:string;version:string;apiVersion:typeof PLUGIN_API_VERSION;entry:string;description?:string;permissions:{network:string[]};}
export interface PluginHostContext {sourceId:string;pluginId:string;config:unknown;}
export interface PluginSourceModule {init?(ctx:PluginHostContext):unknown|Promise<unknown>;home():unknown|Promise<unknown>;category(categoryId:string,page:number,filters?:Record<string,string>):unknown|Promise<unknown>;detail(ids:string[]):unknown|Promise<unknown>;search(keyword:string,page?:number):unknown|Promise<unknown>;play(flag:string,id:string):unknown|Promise<unknown>;destroy?():unknown|Promise<unknown>;}
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
export function parsePluginManifest(input:unknown):PluginManifest {if(!input||typeof input!=='object')throw new Error('Plugin manifest must be an object');const raw=input as Record<string,unknown>;const id=text(raw.id);const name=text(raw.name);const version=text(raw.version);const apiVersion=text(raw.apiVersion);const entry=text(raw.entry);if(!/^[a-z0-9][a-z0-9._-]{2,63}$/i.test(id))throw new Error('Plugin id is invalid');if(!name||name.length>80)throw new Error('Plugin name is invalid');if(!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version))throw new Error('Plugin version must use SemVer');if(apiVersion!==PLUGIN_API_VERSION)throw new Error(`Unsupported plugin API version: ${apiVersion||'<missing>'}`);if(!entry||path.isAbsolute(entry)||entry.split(/[\\/]/).includes('..'))throw new Error('Plugin entry must stay inside the plugin directory');const permissionsRaw=raw.permissions&&typeof raw.permissions==='object'?raw.permissions as Record<string,unknown>:{};const network=Array.isArray(permissionsRaw.network)?permissionsRaw.network.map(text).filter(Boolean):[];for(const rule of network)if(!/^\*\.[A-Za-z0-9.-]+$/.test(rule)&&!/^[A-Za-z0-9.-]+$/.test(rule))throw new Error(`Invalid network permission: ${rule}`);return {id,name,version,apiVersion:PLUGIN_API_VERSION,entry,...(text(raw.description)?{description:text(raw.description)}:{}),permissions:{network:[...new Set(network.map(item=>item.toLowerCase()))]}};}
export function resolvePluginEntry(root:string,manifest:PluginManifest):string {const base=path.resolve(root);const target=path.resolve(base,manifest.entry);if(target!==base&&!target.startsWith(base+path.sep))throw new Error('Plugin entry escapes its directory');return target;}
export function isNetworkAllowed(manifest:PluginManifest,url:string):boolean {let host:string;try{host=new URL(url).hostname.toLowerCase();}catch{return false;}return manifest.permissions.network.some(rule=>rule.startsWith('*.')?host===rule.slice(2)||host.endsWith(`.${rule.slice(2)}`):host===rule);}
