import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {buildCurrentProgramIndex,buildLiveChannelIndex} from '../../apps/desktop/src/renderer/live-index.ts';
const text=path=>readFile(new URL('../../'+path,import.meta.url),'utf8');

test('current package metadata is versioned as 1.4.17',async()=>{for(const p of ['package.json','apps/desktop/package.json']){const data=JSON.parse(await text(p));assert.equal(data.version,'1.4.17',p);}});
test('v1.4.11 suppresses stale playback responses from the main player client',async()=>{const client=await text('apps/desktop/src/main/player-client.ts');const events=await text('apps/desktop/src/renderer/playback-events.ts');assert.match(client,/#loadGeneration/);assert.match(client,/PlaybackSupersededError/);assert.match(client,/#assertCurrent/);assert.match(client,/PlaybackSessionController/);assert.match(events,/PLAYBACK_SUPERSEDED/);assert.match(events,/if\(superseded\(message,error\)\)return/);});
test('v1.4.11 live routing keeps last known good routes and quarantines stalled routes',async()=>{const preload=await text('apps/desktop/src/preload/index.cts');assert.match(preload,/lastKnownGoodRoutes/);assert.match(preload,/quarantinedRoutes/);assert.match(preload,/rankedLiveCandidates/);assert.match(preload,/recoverLiveRoute/);assert.match(preload,/assertLiveGeneration\(generation\)/);assert.match(preload,/pausedForCache/);assert.match(preload,/onRouteChanged/);});
test('v1.4.11 native fullscreen exposes state and live-channel key signals',async()=>{const native=await text('native/player-host/src/main.cpp');const contracts=await text('packages/contracts/src/index.ts');const preload=await text('apps/desktop/src/preload/index.cts');const live=await text('apps/desktop/src/renderer/views/LiveView.vue');assert.match(native,/fullscreen/);assert.match(native,/inputKey/);assert.match(native,/inputSequence/);assert.match(native,/enable_live_fullscreen_keys/);assert.match(contracts,/inputKey/);assert.match(contracts,/inputSequence/);assert.match(preload,/consumeNativeInput/);assert.match(preload,/switchLiveChannel/);assert.match(live,/dialogEscape/);assert.match(live,/onRouteChanged/);});
test('v1.4.11 native surface lease restores embedded video after fullscreen exits',async()=>{const surface=await text('apps/desktop/src/renderer/native-surface.ts');assert.match(surface,/createNativeSurfaceLease/);assert.match(surface,/onFullscreenChanged/);assert.match(surface,/sendSync\(state,state\.lastBounds!,true(?:,true)?\)/);assert.match(surface,/scale:window\.devicePixelRatio/);});
test('v1.4.11 diagnostics cover playback stages with p50 p95 and max',async()=>{const main=await text('apps/desktop/src/main/index.ts');for(const metric of ['playerHostStartMs','playerHostReadyMs','playbackRequestQueueMs','playbackRequestDispatchMs','playerLoadOpenMs','surfaceClaimMs','surfaceAttachMs','fullscreenEnterMs','fullscreenExitRestoreMs','routeProbeMs','routeSelectMs','routeSwitchMs','stallDurationMs','automaticRouteSwitchCount','cancelledPlaybackRequestCount','stalePlaybackResponseCount'])assert.match(main,new RegExp(`'${metric}'`),metric);for(const field of ['p50','p95','max'])assert.match(main,new RegExp(`${field}:`),field);});
test('v1.4.11 playback session is shared across vod live music and player views',async()=>{const [store,vod,live,search,player,music]=await Promise.all(['apps/desktop/src/renderer/stores/playback-session.ts','apps/desktop/src/renderer/views/VodView.vue','apps/desktop/src/renderer/views/LiveView.vue','apps/desktop/src/renderer/views/SearchView.vue','apps/desktop/src/renderer/views/PlayerView.vue','apps/desktop/src/renderer/views/MusicView.vue'].map(text));for(const field of ['generation','requestId','loadId','kind','sourceId','channelId','routeIndex','routeCount','fullscreen','pip','lastReason'])assert.match(store,new RegExp(field),field);for(const source of [vod,live,search,player])assert.match(source,/usePlaybackSessionStore/);assert.match(music,/clockRuntime as runtime/);assert.match(music,/startPlaybackClock/);});
test('v1.4.11 live indexes handle 5000 channels and EPG boundaries deterministically',()=>{const groups=Array.from({length:50},(_,group)=>({channels:Array.from({length:100},(_,index)=>({id:`channel-${group*100+index}`}))}));const indexed=buildLiveChannelIndex(groups);assert.equal(indexed.channels.length,5000);assert.equal(indexed.byId.get('channel-4999')?.id,'channel-4999');assert.equal(indexed.indexById.get('channel-4999'),4999);const programs=[{channelId:'channel-4999',title:'first',start:'2026-09-06T07:00:00.000Z',stop:'2026-09-06T08:00:00.000Z'},{channelId:'channel-4999',title:'second',start:'2026-09-06T08:00:00.000Z',stop:'2026-09-06T09:00:00.000Z'}];assert.equal(buildCurrentProgramIndex(programs,Date.parse('2026-09-06T07:59:59.999Z')).get('channel-4999')?.title,'first');assert.equal(buildCurrentProgramIndex(programs,Date.parse('2026-09-06T08:00:00.000Z')).get('channel-4999')?.title,'second');});
test('v1.4.11 packaged UI matrix covers three scales and high contrast',async()=>{const [single,matrix]=await Promise.all([text('scripts/test-packaged-ui.ps1'),text('scripts/test-packaged-ui-matrix.ps1')]);for(const scale of ['1','1.25','1.5'])assert.match(matrix,new RegExp(scale.replace('.','\\.')));assert.match(matrix,/HighContrast/);assert.match(matrix,/matrix-summary\.json/);assert.match(single,/capturePrefix/);});
test('v1.4.11 fullscreen controls use native OSD that remains visible above PlayerHost',async()=>{const preload=await text('apps/desktop/src/preload/index.cts');assert.match(preload,/showLiveChannelGuide/);assert.match(preload,/空格：播放\/暂停/);assert.match(preload,/检测到持续卡顿/);});

test('v1.4.14 music transport icon buttons expose accessible labels',async()=>{const music=await text('apps/desktop/src/renderer/views/MusicView.vue');for(const label of ['切换播放模式','播放','暂停','取消静音','静音'])assert.match(music,new RegExp(label),label);});
