import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const text=path=>readFile(new URL('../../'+path,import.meta.url),'utf8');
test('v1.4.8 source bulk controls and compatibility actions are present',async()=>{const s=await text('apps/desktop/src/renderer/views/SourcesView.vue');assert.match(s,/启用兼容来源/);assert.match(s,/停止不兼容来源/);assert.match(s,/source\.setEnabledBulk/);assert.match(s,/health\.value\.filter\(item=>item\.ok===compatible\)/);});
test('v1.4.8 navigation places Player between Live and Search',async()=>{const s=await text('apps/desktop/src/renderer/App.vue');assert.ok(s.indexOf("path:'/live'")<s.indexOf("path:'/player'"));assert.ok(s.indexOf("path:'/player'")<s.indexOf("path:'/search'"));});
test('v1.4.8 source engine keeps strong consistency while bulk IPC performs one sync',async()=>{const client=await text('apps/desktop/src/main/source-engine-client.ts');const main=await text('apps/desktop/src/main/index.ts');assert.doesNotMatch(client,/#replacePending|#flushReplaceAll/);assert.match(client,/async replaceAll\(sources:SourceConfig\[\]\):Promise<void>\{await this\.#result/);const handler=main.match(/source:setEnabledBulk[\s\S]*?source:remove/)?.[0]??'';assert.equal((handler.match(/syncSources\(\)/g)??[]).length,1);});
test('v1.4.8 playback pages navigate before awaiting slow media open',async()=>{for(const p of ['apps/desktop/src/renderer/views/VodView.vue','apps/desktop/src/renderer/views/SearchView.vue']){const s=await text(p);const nav=s.indexOf("await router.push('/player')");assert.ok(nav>=0,`missing Player navigation in ${p}`);const playbackCandidates=[s.indexOf('void window.desktop.playback.play',nav),s.indexOf('void window.desktop.live.play',nav)].filter(index=>index>=0);assert.ok(playbackCandidates.length>0,`missing fire-and-forget media open in ${p}`);assert.ok(nav<Math.min(...playbackCandidates),`media open starts before Player navigation in ${p}`);assert.match(s.slice(nav,Math.min(...playbackCandidates)),/emitPlaybackStage/);}});
test('v1.4.8 native surface uses owner and generation guards',async()=>{const s=await text('apps/desktop/src/renderer/native-surface.ts');assert.match(s,/currentOwner/);assert.match(s,/currentGeneration/);assert.match(s,/visible:false/);});
test('v1.4.8 PlayerClient only serializes loads',async()=>{const s=await text('apps/desktop/src/main/player-client.ts');assert.match(s,/#enqueueLoad/);const command=s.match(/async command[\s\S]*?\n  }/)?.[0]??'';const query=s.match(/async query\(query:PlayerQuery\)[\s\S]*?\n  }/)?.[0]??'';assert.doesNotMatch(command,/#enqueueLoad/);assert.doesNotMatch(query,/#enqueueLoad/);});
test('v1.4.8 native pipe handler is not globally locked during load',async()=>{const s=await text('native/player-host/src/named_pipe_server.cpp');assert.doesNotMatch(s,/lock\(handlerMutex_/);});
test('v1.4.8 search is progressive, cache-backed and success-only',async()=>{const s=await text('apps/desktop/src/renderer/views/SearchView.vue');assert.match(s,/window\.desktop\.source\.search\(source\.id,term,1\)/);assert.match(s,/result\.items\.length/);assert.match(s,/searchCompleted/);assert.doesNotMatch(s,/groups\.value=result/);});
test('v1.4.8 packaged UI smoke checks Player before Search and new source controls',async()=>{const s=await text('apps/desktop/src/renderer/main.ts');assert.match(s,/live','player','search/);assert.match(s,/停止不兼容来源/);});
test('v1.4.8 bulk endpoint uses one sqlite transaction and one Source Engine sync',async()=>{const data=await text('services/data-service/src/index.ts');const main=await text('apps/desktop/src/main/index.ts');assert.match(data,/setSourcesEnabledBulk/);assert.match(data,/BEGIN IMMEDIATE/);assert.match(main,/source:setEnabledBulk/);const handler=main.match(/source:setEnabledBulk[\s\S]*?source:remove/)?.[0]??'';assert.equal((handler.match(/syncSources\(\)/g)??[]).length,1);});

test('v1.4.8 uses VOD and LIVE mpv cache profiles',async()=>{const contracts=await text('packages/contracts/src/index.ts');const native=await text('native/player-host/src/main.cpp');const main=await text('apps/desktop/src/main/index.ts');assert.match(contracts,/profile:z\.enum\(\['vod','live'\]\)/);assert.match(native,/demuxer-readahead-secs/);assert.match(native,/cache-pause-wait/);assert.match(main,/profile:'vod'/);assert.match(main,/profile:'live'/);});
test('v1.4.8 caches resolved VOD playback and remembers successful live routes',async()=>{const main=await text('apps/desktop/src/main/index.ts');assert.match(main,/playbackResolutionCache/);assert.match(main,/PLAYBACK_RESOLUTION_TTL_MS/);assert.match(main,/liveRouteCache/);assert.match(main,/LIVE_ROUTE_TTL_MS/);assert.match(main,/lastKnownGood/);assert.doesNotMatch(main,/else\{try\{order=orderedRouteIndexes\(await speedLive\(channel\)\)/);});
test('v1.4.8 invalidates stale playback caches and exports performance evidence',async()=>{const main=await text('apps/desktop/src/main/index.ts');assert.match(main,/playbackResolutionCache\.clear\(\)/);assert.match(main,/clearLiveRouteCache/);assert.match(main,/performance-runtime\.json/);assert.match(main,/sourceResolveMs/);assert.match(main,/playerLoadMs/);});

test('v1.4.8 invalidates live route memory on config reimport and import-group removal',async()=>{const main=await text('apps/desktop/src/main/index.ts');assert.match(main,/for\(const live of liveSources\)\{store\.saveLiveSource\(live\);clearLiveRouteCache\(live\.id\);\}/);assert.match(main,/for\(const sourceId of removed\.liveSourceIds\)\{liveGroupsCache\.delete\(sourceId\);clearLiveRouteCache\(sourceId\);\}/);});
