import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const text=path=>readFile(new URL('../../'+path,import.meta.url),'utf8');
test('v1.4.9 live primary playback opens Player and preview is explicit',async()=>{const s=await text('apps/desktop/src/renderer/views/LiveView.vue');assert.match(s,/@click=\"openPlayer\">▶ 播放/);assert.match(s,/@click=\"play\(selected\)\">页内预览/);assert.match(s,/void window\.desktop\.live\.play/);});
test('v1.4.9 search UI contains only successful result groups',async()=>{const s=await text('apps/desktop/src/renderer/views/SearchView.vue');assert.doesNotMatch(s,/search-failures|失败来源重试区|retrySource/);assert.match(s,/Failed and timed-out sources are intentionally omitted/);});
test('v1.4.9 native route leave awaits release and enforces 200ms smoke budget',async()=>{for(const p of ['apps/desktop/src/renderer/views/LiveView.vue','apps/desktop/src/renderer/views/PlayerView.vue']){const s=await text(p);assert.match(s,/onBeforeRouteLeave\(async/);assert.match(s,/surfaceHideMs/);assert.match(s,/200ms/);}});
test('v1.4.9 native surface reports the renderer pixel scale to PlayerHost',async()=>{const surface=await text('apps/desktop/src/renderer/native-surface.ts');const native=await text('native/player-host/src/main.cpp');assert.match(surface,/scale:window\.devicePixelRatio/);assert.match(native,/json_number\(request, "scale"\)/);});
test('v1.4.9 navigation and playback navigation are instrumented with budgets',async()=>{const app=await text('apps/desktop/src/renderer/App.vue');const vod=await text('apps/desktop/src/renderer/views/VodView.vue');const search=await text('apps/desktop/src/renderer/views/SearchView.vue');assert.match(app,/navigationMs/);assert.match(app,/100ms budget/);assert.match(vod,/playbackNavigationMs/);assert.match(search,/playbackNavigationMs/);});
test('v1.4.9 packaged navigation budget uses mutation events instead of 10ms polling jitter',async()=>{const renderer=await text('apps/desktop/src/renderer/main.ts');assert.match(renderer,/MutationObserver/);assert.match(renderer,/waitForSmokeRoute/);assert.doesNotMatch(renderer,/await sleep\(10\)/);assert.match(renderer,/navigationMs>100/);});
test('v1.4.9 performance runtime exports UI metric p95 samples',async()=>{const main=await text('apps/desktop/src/main/index.ts');assert.match(main,/performanceSamples/);assert.match(main,/performanceSummary/);assert.match(main,/diagnostics:recordPerformance/);assert.match(main,/uiMetrics:performanceSummary\(\)/);});

test('v1.4.9 PlayerHost load is accepted asynchronously and exposes load-status',async()=>{const h=await text('native/player-host/include/mpv_loader.h');const cpp=await text('native/player-host/src/mpv_loader.cpp');const main=await text('native/player-host/src/main.cpp');const client=await text('apps/desktop/src/main/player-client.ts');assert.match(h,/startLoad/);assert.match(h,/MpvLoadState/);assert.match(h,/command_async_fn/);assert.match(cpp,/mpv_command_async/);assert.match(cpp,/MPV_EVENT_COMMAND_REPLY/);assert.doesNotMatch(cpp,/command\(\{"loadfile"/);assert.match(cpp,/eventLoop/);assert.doesNotMatch(cpp,/Timed out waiting for mpv to open media/);assert.match(main,/accepted/);assert.match(main,/load-status/);assert.match(client,/#waitForLoad/);});
test('v1.4.9 PlayerHost startup probing preserves the 200ms accept budget',async()=>{const client=await text('apps/desktop/src/main/player-client.ts');assert.match(client,/setTimeout\(probe,25\)/);});
test('v1.4.9 PlayerHost avoids redundant synchronous load configuration',async()=>{const main=await text('native/player-host/src/main.cpp');const loader=await text('native/player-host/src/mpv_loader.cpp');assert.match(main,/profile != activeProfile/);assert.match(loader,/headerFields_!=headerFields/);});
test('v1.4.9 concurrent PlayerHost calls share one startup',async()=>{const client=await text('apps/desktop/src/main/player-client.ts');assert.match(client,/#startPromise:Promise<void>/);assert.match(client,/if\(this\.#startPromise\)return await this\.#startPromise/);});
test('v1.4.9 warms PlayerHost after the main window is created',async()=>{const main=await text('apps/desktop/src/main/index.ts');assert.match(main,/createWindow\(\);void player\.query\('stats'\)/);});
test('v1.4.9 PlayerHost Windows test enforces 200ms async accept query and stop budgets',async()=>{const s=await text('scripts/test-player-host.ps1');assert.match(s,/player.load did not accept within 200ms/);assert.match(s,/stats responsiveness/);assert.match(s,/stop exceeded 200ms/);assert.match(s,/Missing media never transitioned to failed/);});
test('v1.4.9 headless audio fallback and immediate HWND are restricted to explicit smoke and test launches',async()=>{const native=await text('native/player-host/src/main.cpp');const loader=await text('native/player-host/src/mpv_loader.cpp');const client=await text('apps/desktop/src/main/player-client.ts');const ps=await text('scripts/test-player-host.ps1');assert.match(native,/--test-audio-output/);assert.match(loader,/force-window\",nullAudioOutput\?\"immediate\":\"yes\"/);assert.match(loader,/if\(nullAudioOutput\)setOption\(handle_,\"ao\",\"null\"\)/);assert.match(client,/process\.env\.FND_UI_SMOKE===\'1\'/);assert.match(ps,/--test-audio-output/);});
test('v1.4.9 exports first-frame and buffering performance signals',async()=>{const contracts=await text('packages/contracts/src/index.ts');const native=await text('native/player-host/src/main.cpp');const player=await text('apps/desktop/src/renderer/views/PlayerView.vue');assert.match(contracts,/pausedForCache/);assert.match(native,/paused-for-cache/);assert.match(player,/bufferingDurationMs/);assert.match(player,/firstFrameMs/);});

test('v1.4.9 VOD Live and Search restore from in-memory Pinia snapshots',async()=>{const store=await text('apps/desktop/src/renderer/stores/page-state.ts');assert.match(store,/defineStore\('page-state'/);for(const p of ['VodView.vue','LiveView.vue','SearchView.vue']){const s=await text('apps/desktop/src/renderer/views/'+p);assert.match(s,/usePageStateStore/);assert.match(s,/pageState\.read/);assert.match(s,/pageState\.save/);}});
test('v1.4.9 packaged UI smoke uses real local media and repeats native lifecycle cycle',async()=>{const main=await text('apps/desktop/src/main/index.ts');const preload=await text('apps/desktop/src/preload/index.cts');const renderer=await text('apps/desktop/src/renderer/main.ts');const ps=await text('scripts/test-packaged-ui.ps1');assert.match(main,/playback:smokeLoad/);assert.match(main,/createUiSmokeMedia/);assert.match(preload,/smokeLoad/);assert.match(renderer,/smokeLoad/);assert.match(renderer,/settings','live','player','search','player/);assert.match(renderer,/UI Smoke Transition/);assert.match(ps,/re-validated dynamically/);});
test('v1.4.9 packaged UI smoke rechecks the route marker after foreground stabilization',async()=>{const ps=await text('scripts/test-packaged-ui.ps1');assert.match(ps,/MainWindowTitle -ne \$lastTitle/);});
